
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_FILLED

#include "dial_filled.h"

#ifdef ENABLE_FACE_DIAL_FILLED

lv_obj_t *face_dial_filled;
lv_obj_t *face_dial_filled_0_84;
lv_obj_t *face_dial_filled_1_84;
lv_obj_t *face_dial_filled_2_84;
lv_obj_t *face_dial_filled_3_84;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_filled_dial_img_0_84_group[] = {
	&face_dial_filled_dial_img_0_84_0,
	&face_dial_filled_dial_img_0_84_1,
	&face_dial_filled_dial_img_0_84_2,
	&face_dial_filled_dial_img_0_84_3,
	&face_dial_filled_dial_img_0_84_4,
	&face_dial_filled_dial_img_0_84_5,
	&face_dial_filled_dial_img_0_84_6,
	&face_dial_filled_dial_img_0_84_7,
	&face_dial_filled_dial_img_0_84_8,
	&face_dial_filled_dial_img_0_84_9,
};


#endif

void init_face_dial_filled(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_DIAL_FILLED
    face_dial_filled = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_filled, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_filled, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_filled, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_filled, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_filled, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_filled, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_filled, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_filled, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_filled, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_filled_0_84 = lv_img_create(face_dial_filled);
    lv_img_set_src(face_dial_filled_0_84, &face_dial_filled_dial_img_0_84_0);
    lv_obj_set_width(face_dial_filled_0_84, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_filled_0_84, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_filled_0_84, 120);
    lv_obj_set_y(face_dial_filled_0_84, 0);
    lv_obj_add_flag(face_dial_filled_0_84, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_filled_0_84, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_filled_1_84 = lv_img_create(face_dial_filled);
    lv_img_set_src(face_dial_filled_1_84, &face_dial_filled_dial_img_0_84_0);
    lv_obj_set_width(face_dial_filled_1_84, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_filled_1_84, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_filled_1_84, 0);
    lv_obj_set_y(face_dial_filled_1_84, 0);
    lv_obj_add_flag(face_dial_filled_1_84, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_filled_1_84, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_filled_2_84 = lv_img_create(face_dial_filled);
    lv_img_set_src(face_dial_filled_2_84, &face_dial_filled_dial_img_0_84_0);
    lv_obj_set_width(face_dial_filled_2_84, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_filled_2_84, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_filled_2_84, 120);
    lv_obj_set_y(face_dial_filled_2_84, 148);
    lv_obj_add_flag(face_dial_filled_2_84, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_filled_2_84, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_filled_3_84 = lv_img_create(face_dial_filled);
    lv_img_set_src(face_dial_filled_3_84, &face_dial_filled_dial_img_0_84_0);
    lv_obj_set_width(face_dial_filled_3_84, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_filled_3_84, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_filled_3_84, 0);
    lv_obj_set_y(face_dial_filled_3_84, 148);
    lv_obj_add_flag(face_dial_filled_3_84, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_filled_3_84, LV_OBJ_FLAG_SCROLLABLE );


    callback("dial filled", &face_dial_filled_dial_img_preview_0, &face_dial_filled);

#endif
}

void update_time_dial_filled(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_FILLED
    if (!face_dial_filled)
    {
        return;
    }
	lv_img_set_src(face_dial_filled_0_84, face_dial_filled_dial_img_0_84_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_filled_1_84, face_dial_filled_dial_img_0_84_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_filled_2_84, face_dial_filled_dial_img_0_84_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_filled_3_84, face_dial_filled_dial_img_0_84_group[(minute / 10) % 10]);

#endif
}

void update_weather_dial_filled(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_FILLED
    if (!face_dial_filled)
    {
        return;
    }

#endif
}

void update_status_dial_filled(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_FILLED
    if (!face_dial_filled)
    {
        return;
    }

#endif
}

void update_activity_dial_filled(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_FILLED
    if (!face_dial_filled)
    {
        return;
    }

#endif
}

void update_health_dial_filled(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_FILLED
    if (!face_dial_filled)
    {
        return;
    }

#endif
}

void update_all_dial_filled(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_FILLED
    update_time_dial_filled(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_filled(temp, icon);
    update_status_dial_filled(battery, connection);
    update_activity_dial_filled(steps, distance, kcal);
    update_health_dial_filled(bpm, oxygen);
#endif
}

void update_check_dial_filled(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_FILLED
    if (root != face_dial_filled)
    {
        return;
    }
    update_time_dial_filled(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_filled(temp, icon);
    update_status_dial_filled(battery, connection);
    update_activity_dial_filled(steps, distance, kcal);
    update_health_dial_filled(bpm, oxygen);
#endif
}


