
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_FILLED

#ifndef _FACE_DIAL_FILLED_H
#define _FACE_DIAL_FILLED_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

// #define ENABLE_FACE_DIAL_FILLED // (dial filled) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_DIAL_FILLED
    extern lv_obj_t *face_dial_filled;
	extern lv_obj_t *face_dial_filled_0_84;
	extern lv_obj_t *face_dial_filled_1_84;
	extern lv_obj_t *face_dial_filled_2_84;
	extern lv_obj_t *face_dial_filled_3_84;


	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_0);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_1);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_2);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_3);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_4);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_5);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_6);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_7);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_8);
	LV_IMG_DECLARE(face_dial_filled_dial_img_0_84_9);
	LV_IMG_DECLARE(face_dial_filled_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_dial_filled(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **));
    void update_time_dial_filled(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_dial_filled(int temp, int icon);
    void update_status_dial_filled(int battery, bool connection);
    void update_activity_dial_filled(int steps, int distance, int kcal);
    void update_health_dial_filled(int bpm, int oxygen);
    void update_all_dial_filled(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_dial_filled(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
