
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_ASTRONAUT3

#include "dial_astronaut3.h"

#ifdef ENABLE_FACE_DIAL_ASTRONAUT3

lv_obj_t *face_dial_astronaut3;
lv_obj_t *face_dial_astronaut3_0_1241;
lv_obj_t *face_dial_astronaut3_1_79333;
lv_obj_t *face_dial_astronaut3_3_248325;
lv_obj_t *face_dial_astronaut3_4_260646;
lv_obj_t *face_dial_astronaut3_5_260646;
lv_obj_t *face_dial_astronaut3_6_260646;
lv_obj_t *face_dial_astronaut3_7_260646;
lv_obj_t *face_dial_astronaut3_8_263560;
lv_obj_t *face_dial_astronaut3_9_263560;
lv_obj_t *face_dial_astronaut3_10_263560;
lv_obj_t *face_dial_astronaut3_11_263560;
lv_obj_t *face_dial_astronaut3_12_257094;
lv_obj_t *face_dial_astronaut3_13_257094;
lv_obj_t *face_dial_astronaut3_14_984;
lv_obj_t *face_dial_astronaut3_15_260646;
lv_obj_t *face_dial_astronaut3_16_260646;
lv_obj_t *face_dial_astronaut3_17_260646;
lv_obj_t *face_dial_astronaut3_18_260646;
lv_obj_t *face_dial_astronaut3_19_260646;
lv_obj_t *face_dial_astronaut3_20_260646;
lv_obj_t *face_dial_astronaut3_21_262028;
lv_obj_t *face_dial_astronaut3_22_262028;
lv_obj_t *face_dial_astronaut3_23_262028;
lv_obj_t *face_dial_astronaut3_24_262028;
lv_obj_t *face_dial_astronaut3_25_262028;
lv_obj_t *face_dial_astronaut3_26_262028;
lv_obj_t *face_dial_astronaut3_27_262028;
lv_obj_t *face_dial_astronaut3_28_262028;
lv_obj_t *face_dial_astronaut3_29_262028;
lv_obj_t *face_dial_astronaut3_31_72791;
lv_obj_t *face_dial_astronaut3_40_41863;
lv_obj_t *face_dial_astronaut3_41_41863;
lv_obj_t *face_dial_astronaut3_42_260646;
lv_obj_t *face_dial_astronaut3_43_260646;
lv_obj_t *face_dial_astronaut3_44_260646;
lv_obj_t *face_dial_astronaut3_45_283640;
lv_obj_t *face_dial_astronaut3_46_254865;
lv_obj_t *face_dial_astronaut3_47_41863;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_astronaut3_dial_img_1_79333_group[] = {
	&face_dial_astronaut3_dial_img_1_79333_0,
	&face_dial_astronaut3_dial_img_1_79333_1,
	&face_dial_astronaut3_dial_img_1_79333_2,
	&face_dial_astronaut3_dial_img_1_79333_3,
	&face_dial_astronaut3_dial_img_1_79333_4,
	&face_dial_astronaut3_dial_img_1_79333_5,
	&face_dial_astronaut3_dial_img_1_79333_6,
	&face_dial_astronaut3_dial_img_1_79333_7,
	&face_dial_astronaut3_dial_img_1_79333_8,
	&face_dial_astronaut3_dial_img_1_79333_9,
	&face_dial_astronaut3_dial_img_1_79333_10,
	&face_dial_astronaut3_dial_img_1_79333_11,
	&face_dial_astronaut3_dial_img_1_79333_12,
	&face_dial_astronaut3_dial_img_1_79333_13,
	&face_dial_astronaut3_dial_img_1_79333_14,
};
const lv_img_dsc_t *face_dial_astronaut3_dial_img_2_74779_group[] = {
	&face_dial_astronaut3_dial_img_2_74779_0,
	&face_dial_astronaut3_dial_img_2_74779_1,
	&face_dial_astronaut3_dial_img_2_74779_2,
	&face_dial_astronaut3_dial_img_2_74779_3,
	&face_dial_astronaut3_dial_img_2_74779_4,
	&face_dial_astronaut3_dial_img_2_74779_5,
	&face_dial_astronaut3_dial_img_2_74779_6,
};
const lv_img_dsc_t *face_dial_astronaut3_dial_img_3_248325_group[] = {
	&face_dial_astronaut3_dial_img_3_248325_0,
	&face_dial_astronaut3_dial_img_3_248325_1,
	&face_dial_astronaut3_dial_img_3_248325_2,
	&face_dial_astronaut3_dial_img_3_248325_3,
	&face_dial_astronaut3_dial_img_3_248325_4,
	&face_dial_astronaut3_dial_img_3_248325_5,
	&face_dial_astronaut3_dial_img_3_248325_6,
};
const lv_img_dsc_t *face_dial_astronaut3_dial_img_4_260646_group[] = {
	&face_dial_astronaut3_dial_img_4_260646_0,
	&face_dial_astronaut3_dial_img_4_260646_1,
	&face_dial_astronaut3_dial_img_4_260646_2,
	&face_dial_astronaut3_dial_img_4_260646_3,
	&face_dial_astronaut3_dial_img_4_260646_4,
	&face_dial_astronaut3_dial_img_4_260646_5,
	&face_dial_astronaut3_dial_img_4_260646_6,
	&face_dial_astronaut3_dial_img_4_260646_7,
	&face_dial_astronaut3_dial_img_4_260646_8,
	&face_dial_astronaut3_dial_img_4_260646_9,
};
const lv_img_dsc_t *face_dial_astronaut3_dial_img_8_263560_group[] = {
	&face_dial_astronaut3_dial_img_8_263560_0,
	&face_dial_astronaut3_dial_img_8_263560_1,
	&face_dial_astronaut3_dial_img_8_263560_2,
	&face_dial_astronaut3_dial_img_8_263560_3,
	&face_dial_astronaut3_dial_img_8_263560_4,
	&face_dial_astronaut3_dial_img_8_263560_5,
	&face_dial_astronaut3_dial_img_8_263560_6,
	&face_dial_astronaut3_dial_img_8_263560_7,
	&face_dial_astronaut3_dial_img_8_263560_8,
	&face_dial_astronaut3_dial_img_8_263560_9,
};
const lv_img_dsc_t *face_dial_astronaut3_dial_img_12_257094_group[] = {
	&face_dial_astronaut3_dial_img_12_257094_0,
	&face_dial_astronaut3_dial_img_12_257094_1,
	&face_dial_astronaut3_dial_img_12_257094_2,
	&face_dial_astronaut3_dial_img_12_257094_3,
	&face_dial_astronaut3_dial_img_12_257094_4,
	&face_dial_astronaut3_dial_img_12_257094_5,
	&face_dial_astronaut3_dial_img_12_257094_6,
	&face_dial_astronaut3_dial_img_12_257094_7,
	&face_dial_astronaut3_dial_img_12_257094_8,
	&face_dial_astronaut3_dial_img_12_257094_9,
};
const lv_img_dsc_t *face_dial_astronaut3_dial_img_21_262028_group[] = {
	&face_dial_astronaut3_dial_img_21_262028_0,
	&face_dial_astronaut3_dial_img_21_262028_1,
	&face_dial_astronaut3_dial_img_21_262028_2,
	&face_dial_astronaut3_dial_img_21_262028_3,
	&face_dial_astronaut3_dial_img_21_262028_4,
	&face_dial_astronaut3_dial_img_21_262028_5,
	&face_dial_astronaut3_dial_img_21_262028_6,
	&face_dial_astronaut3_dial_img_21_262028_7,
	&face_dial_astronaut3_dial_img_21_262028_8,
	&face_dial_astronaut3_dial_img_21_262028_9,
};
const lv_img_dsc_t *face_dial_astronaut3_dial_img_weather[] = {
	&face_dial_astronaut3_dial_img_31_72791_0,
	&face_dial_astronaut3_dial_img_32_285883_0,
	&face_dial_astronaut3_dial_img_33_283901_0,
	&face_dial_astronaut3_dial_img_34_279660_0,
	&face_dial_astronaut3_dial_img_35_277672_0,
	&face_dial_astronaut3_dial_img_36_281650_0,
	&face_dial_astronaut3_dial_img_37_287873_0,
	&face_dial_astronaut3_dial_img_38_252879_0,
	&face_dial_astronaut3_dial_img_39_255110_0,
};


#endif

void init_face_dial_astronaut3(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    face_dial_astronaut3 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_astronaut3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_astronaut3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_astronaut3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_astronaut3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_astronaut3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_astronaut3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_astronaut3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_astronaut3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_astronaut3, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_astronaut3_0_1241 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_0_1241, &face_dial_astronaut3_dial_img_0_1241_0);
    lv_obj_set_width(face_dial_astronaut3_0_1241, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_0_1241, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_0_1241, 0);
    lv_obj_set_y(face_dial_astronaut3_0_1241, 0);
    lv_obj_add_flag(face_dial_astronaut3_0_1241, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_0_1241, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_1_79333 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_1_79333, &face_dial_astronaut3_dial_img_1_79333_0);
    lv_obj_set_width(face_dial_astronaut3_1_79333, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_1_79333, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_1_79333, 76);
    lv_obj_set_y(face_dial_astronaut3_1_79333, 130);
    lv_obj_add_flag(face_dial_astronaut3_1_79333, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_1_79333, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_3_248325 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_3_248325, &face_dial_astronaut3_dial_img_3_248325_0);
    lv_obj_set_width(face_dial_astronaut3_3_248325, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_3_248325, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_3_248325, 191);
    lv_obj_set_y(face_dial_astronaut3_3_248325, 163);
    lv_obj_add_flag(face_dial_astronaut3_3_248325, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_3_248325, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_4_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_4_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_4_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_4_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_4_260646, 194);
    lv_obj_set_y(face_dial_astronaut3_4_260646, 195);
    lv_obj_add_flag(face_dial_astronaut3_4_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_4_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_5_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_5_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_5_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_5_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_5_260646, 184);
    lv_obj_set_y(face_dial_astronaut3_5_260646, 195);
    lv_obj_add_flag(face_dial_astronaut3_5_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_5_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_6_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_6_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_6_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_6_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_6_260646, 222);
    lv_obj_set_y(face_dial_astronaut3_6_260646, 195);
    lv_obj_add_flag(face_dial_astronaut3_6_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_6_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_7_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_7_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_7_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_7_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_7_260646, 212);
    lv_obj_set_y(face_dial_astronaut3_7_260646, 195);
    lv_obj_add_flag(face_dial_astronaut3_7_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_7_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_8_263560 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_8_263560, &face_dial_astronaut3_dial_img_8_263560_0);
    lv_obj_set_width(face_dial_astronaut3_8_263560, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_8_263560, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_8_263560, 71);
    lv_obj_set_y(face_dial_astronaut3_8_263560, 73);
    lv_obj_add_flag(face_dial_astronaut3_8_263560, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_8_263560, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_9_263560 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_9_263560, &face_dial_astronaut3_dial_img_8_263560_0);
    lv_obj_set_width(face_dial_astronaut3_9_263560, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_9_263560, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_9_263560, 29);
    lv_obj_set_y(face_dial_astronaut3_9_263560, 73);
    lv_obj_add_flag(face_dial_astronaut3_9_263560, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_9_263560, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_10_263560 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_10_263560, &face_dial_astronaut3_dial_img_8_263560_0);
    lv_obj_set_width(face_dial_astronaut3_10_263560, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_10_263560, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_10_263560, 181);
    lv_obj_set_y(face_dial_astronaut3_10_263560, 73);
    lv_obj_add_flag(face_dial_astronaut3_10_263560, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_10_263560, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_11_263560 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_11_263560, &face_dial_astronaut3_dial_img_8_263560_0);
    lv_obj_set_width(face_dial_astronaut3_11_263560, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_11_263560, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_11_263560, 139);
    lv_obj_set_y(face_dial_astronaut3_11_263560, 73);
    lv_obj_add_flag(face_dial_astronaut3_11_263560, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_11_263560, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_12_257094 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_12_257094, &face_dial_astronaut3_dial_img_12_257094_0);
    lv_obj_set_width(face_dial_astronaut3_12_257094, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_12_257094, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_12_257094, 212);
    lv_obj_set_y(face_dial_astronaut3_12_257094, 121);
    lv_obj_add_flag(face_dial_astronaut3_12_257094, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_12_257094, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_13_257094 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_13_257094, &face_dial_astronaut3_dial_img_12_257094_0);
    lv_obj_set_width(face_dial_astronaut3_13_257094, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_13_257094, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_13_257094, 195);
    lv_obj_set_y(face_dial_astronaut3_13_257094, 121);
    lv_obj_add_flag(face_dial_astronaut3_13_257094, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_13_257094, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_14_984 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_14_984, &face_dial_astronaut3_dial_img_14_984_0);
    lv_obj_set_width(face_dial_astronaut3_14_984, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_14_984, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_14_984, 216);
    lv_obj_set_y(face_dial_astronaut3_14_984, 229);
    lv_obj_add_flag(face_dial_astronaut3_14_984, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_14_984, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_15_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_15_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_15_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_15_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_15_260646, 206);
    lv_obj_set_y(face_dial_astronaut3_15_260646, 229);
    lv_obj_add_flag(face_dial_astronaut3_15_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_15_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_16_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_16_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_16_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_16_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_16_260646, 196);
    lv_obj_set_y(face_dial_astronaut3_16_260646, 229);
    lv_obj_add_flag(face_dial_astronaut3_16_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_16_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_17_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_17_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_17_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_17_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_17_260646, 186);
    lv_obj_set_y(face_dial_astronaut3_17_260646, 229);
    lv_obj_add_flag(face_dial_astronaut3_17_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_17_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_18_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_18_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_18_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_18_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_18_260646, 65);
    lv_obj_set_y(face_dial_astronaut3_18_260646, 229);
    lv_obj_add_flag(face_dial_astronaut3_18_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_18_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_19_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_19_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_19_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_19_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_19_260646, 55);
    lv_obj_set_y(face_dial_astronaut3_19_260646, 229);
    lv_obj_add_flag(face_dial_astronaut3_19_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_19_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_20_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_20_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_20_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_20_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_20_260646, 45);
    lv_obj_set_y(face_dial_astronaut3_20_260646, 229);
    lv_obj_add_flag(face_dial_astronaut3_20_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_20_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_21_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_21_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_21_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_21_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_21_262028, 76);
    lv_obj_set_y(face_dial_astronaut3_21_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_21_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_21_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_22_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_22_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_22_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_22_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_22_262028, 65);
    lv_obj_set_y(face_dial_astronaut3_22_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_22_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_22_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_23_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_23_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_23_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_23_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_23_262028, 54);
    lv_obj_set_y(face_dial_astronaut3_23_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_23_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_23_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_24_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_24_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_24_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_24_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_24_262028, 43);
    lv_obj_set_y(face_dial_astronaut3_24_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_24_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_24_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_25_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_25_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_25_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_25_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_25_262028, 195);
    lv_obj_set_y(face_dial_astronaut3_25_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_25_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_25_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_26_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_26_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_26_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_26_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_26_262028, 184);
    lv_obj_set_y(face_dial_astronaut3_26_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_26_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_26_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_27_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_27_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_27_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_27_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_27_262028, 173);
    lv_obj_set_y(face_dial_astronaut3_27_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_27_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_27_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_28_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_28_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_28_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_28_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_28_262028, 162);
    lv_obj_set_y(face_dial_astronaut3_28_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_28_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_28_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_29_262028 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_29_262028, &face_dial_astronaut3_dial_img_21_262028_0);
    lv_obj_set_width(face_dial_astronaut3_29_262028, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_29_262028, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_29_262028, 151);
    lv_obj_set_y(face_dial_astronaut3_29_262028, 268);
    lv_obj_add_flag(face_dial_astronaut3_29_262028, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_29_262028, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_31_72791 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_31_72791, &face_dial_astronaut3_dial_img_31_72791_0);
    lv_obj_set_width(face_dial_astronaut3_31_72791, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_31_72791, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_31_72791, 102);
    lv_obj_set_y(face_dial_astronaut3_31_72791, 6);
    lv_obj_add_flag(face_dial_astronaut3_31_72791, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_31_72791, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_40_41863 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_40_41863, &face_dial_astronaut3_dial_img_40_41863_0);
    lv_obj_set_width(face_dial_astronaut3_40_41863, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_40_41863, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_40_41863, 116);
    lv_obj_set_y(face_dial_astronaut3_40_41863, 54);
    lv_obj_add_flag(face_dial_astronaut3_40_41863, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_40_41863, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_41_41863 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_41_41863, &face_dial_astronaut3_dial_img_40_41863_0);
    lv_obj_set_width(face_dial_astronaut3_41_41863, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_41_41863, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_41_41863, 106);
    lv_obj_set_y(face_dial_astronaut3_41_41863, 54);
    lv_obj_add_flag(face_dial_astronaut3_41_41863, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_41_41863, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_42_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_42_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_42_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_42_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_42_260646, 116);
    lv_obj_set_y(face_dial_astronaut3_42_260646, 48);
    lv_obj_add_flag(face_dial_astronaut3_42_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_42_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_43_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_43_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_43_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_43_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_43_260646, 106);
    lv_obj_set_y(face_dial_astronaut3_43_260646, 48);
    lv_obj_add_flag(face_dial_astronaut3_43_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_43_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_44_260646 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_44_260646, &face_dial_astronaut3_dial_img_4_260646_0);
    lv_obj_set_width(face_dial_astronaut3_44_260646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_44_260646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_44_260646, 96);
    lv_obj_set_y(face_dial_astronaut3_44_260646, 48);
    lv_obj_add_flag(face_dial_astronaut3_44_260646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_44_260646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_45_283640 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_45_283640, &face_dial_astronaut3_dial_img_45_283640_0);
    lv_obj_set_width(face_dial_astronaut3_45_283640, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_45_283640, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_45_283640, 126);
    lv_obj_set_y(face_dial_astronaut3_45_283640, 48);
    lv_obj_add_flag(face_dial_astronaut3_45_283640, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_45_283640, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_46_254865 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_46_254865, &face_dial_astronaut3_dial_img_46_254865_0);
    lv_obj_set_width(face_dial_astronaut3_46_254865, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_46_254865, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_46_254865, 126);
    lv_obj_set_y(face_dial_astronaut3_46_254865, 48);
    lv_obj_add_flag(face_dial_astronaut3_46_254865, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_46_254865, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut3_47_41863 = lv_img_create(face_dial_astronaut3);
    lv_img_set_src(face_dial_astronaut3_47_41863, &face_dial_astronaut3_dial_img_40_41863_0);
    lv_obj_set_width(face_dial_astronaut3_47_41863, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut3_47_41863, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut3_47_41863, 96);
    lv_obj_set_y(face_dial_astronaut3_47_41863, 54);
    lv_obj_add_flag(face_dial_astronaut3_47_41863, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut3_47_41863, LV_OBJ_FLAG_SCROLLABLE );


    callback("dial astronaut3", &face_dial_astronaut3_dial_img_preview_0, &face_dial_astronaut3);

#endif
}

void update_time_dial_astronaut3(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    if (!face_dial_astronaut3)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut3_3_248325, face_dial_astronaut3_dial_img_3_248325_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_dial_astronaut3_4_260646, face_dial_astronaut3_dial_img_4_260646_group[(month / 1) % 10]);
	lv_img_set_src(face_dial_astronaut3_5_260646, face_dial_astronaut3_dial_img_4_260646_group[(month / 10) % 10]);
	lv_img_set_src(face_dial_astronaut3_6_260646, face_dial_astronaut3_dial_img_4_260646_group[(day / 1) % 10]);
	lv_img_set_src(face_dial_astronaut3_7_260646, face_dial_astronaut3_dial_img_4_260646_group[(day / 10) % 10]);
	lv_img_set_src(face_dial_astronaut3_8_263560, face_dial_astronaut3_dial_img_8_263560_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_astronaut3_9_263560, face_dial_astronaut3_dial_img_8_263560_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_astronaut3_10_263560, face_dial_astronaut3_dial_img_8_263560_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_astronaut3_11_263560, face_dial_astronaut3_dial_img_8_263560_group[(minute / 10) % 10]);

#endif
}

void update_weather_dial_astronaut3(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    if (!face_dial_astronaut3)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut3_31_72791, face_dial_astronaut3_dial_img_weather[icon % 8]);

#endif
}

void update_status_dial_astronaut3(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    if (!face_dial_astronaut3)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut3_15_260646, face_dial_astronaut3_dial_img_4_260646_group[(battery / 1) % 10]);
	lv_img_set_src(face_dial_astronaut3_16_260646, face_dial_astronaut3_dial_img_4_260646_group[(battery / 10) % 10]);
	lv_img_set_src(face_dial_astronaut3_17_260646, face_dial_astronaut3_dial_img_4_260646_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_dial_astronaut3_17_260646, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_astronaut3_17_260646, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_dial_astronaut3(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    if (!face_dial_astronaut3)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut3_21_262028, face_dial_astronaut3_dial_img_21_262028_group[(kcal / 1) % 10]);
	lv_img_set_src(face_dial_astronaut3_22_262028, face_dial_astronaut3_dial_img_21_262028_group[(kcal / 10) % 10]);
	lv_img_set_src(face_dial_astronaut3_23_262028, face_dial_astronaut3_dial_img_21_262028_group[(kcal / 100) % 10]);
	lv_img_set_src(face_dial_astronaut3_24_262028, face_dial_astronaut3_dial_img_21_262028_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_dial_astronaut3_25_262028, face_dial_astronaut3_dial_img_21_262028_group[(steps / 1) % 10]);
	lv_img_set_src(face_dial_astronaut3_26_262028, face_dial_astronaut3_dial_img_21_262028_group[(steps / 10) % 10]);
	lv_img_set_src(face_dial_astronaut3_27_262028, face_dial_astronaut3_dial_img_21_262028_group[(steps / 100) % 10]);
	lv_img_set_src(face_dial_astronaut3_28_262028, face_dial_astronaut3_dial_img_21_262028_group[(steps / 1000) % 10]);
	lv_img_set_src(face_dial_astronaut3_29_262028, face_dial_astronaut3_dial_img_21_262028_group[(steps / 10000) % 10]);

#endif
}

void update_health_dial_astronaut3(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    if (!face_dial_astronaut3)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut3_18_260646, face_dial_astronaut3_dial_img_4_260646_group[(bpm / 1) % 10]);
	lv_img_set_src(face_dial_astronaut3_19_260646, face_dial_astronaut3_dial_img_4_260646_group[(bpm / 10) % 10]);
	lv_img_set_src(face_dial_astronaut3_20_260646, face_dial_astronaut3_dial_img_4_260646_group[(bpm / 100) % 10]);

#endif
}

void update_all_dial_astronaut3(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    update_time_dial_astronaut3(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_astronaut3(temp, icon);
    update_status_dial_astronaut3(battery, connection);
    update_activity_dial_astronaut3(steps, distance, kcal);
    update_health_dial_astronaut3(bpm, oxygen);
#endif
}

void update_check_dial_astronaut3(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    if (root != face_dial_astronaut3)
    {
        return;
    }
    update_time_dial_astronaut3(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_astronaut3(temp, icon);
    update_status_dial_astronaut3(battery, connection);
    update_activity_dial_astronaut3(steps, distance, kcal);
    update_health_dial_astronaut3(bpm, oxygen);
#endif
}


