
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_ASTRONAUT3

#ifndef _FACE_DIAL_ASTRONAUT3_H
#define _FACE_DIAL_ASTRONAUT3_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#define ENABLE_FACE_DIAL_ASTRONAUT3 // (dial astronaut3) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_DIAL_ASTRONAUT3
    extern lv_obj_t *face_dial_astronaut3;
	extern lv_obj_t *face_dial_astronaut3_0_1241;
	extern lv_obj_t *face_dial_astronaut3_1_79333;
	extern lv_obj_t *face_dial_astronaut3_3_248325;
	extern lv_obj_t *face_dial_astronaut3_4_260646;
	extern lv_obj_t *face_dial_astronaut3_5_260646;
	extern lv_obj_t *face_dial_astronaut3_6_260646;
	extern lv_obj_t *face_dial_astronaut3_7_260646;
	extern lv_obj_t *face_dial_astronaut3_8_263560;
	extern lv_obj_t *face_dial_astronaut3_9_263560;
	extern lv_obj_t *face_dial_astronaut3_10_263560;
	extern lv_obj_t *face_dial_astronaut3_11_263560;
	extern lv_obj_t *face_dial_astronaut3_12_257094;
	extern lv_obj_t *face_dial_astronaut3_13_257094;
	extern lv_obj_t *face_dial_astronaut3_14_984;
	extern lv_obj_t *face_dial_astronaut3_15_260646;
	extern lv_obj_t *face_dial_astronaut3_16_260646;
	extern lv_obj_t *face_dial_astronaut3_17_260646;
	extern lv_obj_t *face_dial_astronaut3_18_260646;
	extern lv_obj_t *face_dial_astronaut3_19_260646;
	extern lv_obj_t *face_dial_astronaut3_20_260646;
	extern lv_obj_t *face_dial_astronaut3_21_262028;
	extern lv_obj_t *face_dial_astronaut3_22_262028;
	extern lv_obj_t *face_dial_astronaut3_23_262028;
	extern lv_obj_t *face_dial_astronaut3_24_262028;
	extern lv_obj_t *face_dial_astronaut3_25_262028;
	extern lv_obj_t *face_dial_astronaut3_26_262028;
	extern lv_obj_t *face_dial_astronaut3_27_262028;
	extern lv_obj_t *face_dial_astronaut3_28_262028;
	extern lv_obj_t *face_dial_astronaut3_29_262028;
	extern lv_obj_t *face_dial_astronaut3_31_72791;
	extern lv_obj_t *face_dial_astronaut3_40_41863;
	extern lv_obj_t *face_dial_astronaut3_41_41863;
	extern lv_obj_t *face_dial_astronaut3_42_260646;
	extern lv_obj_t *face_dial_astronaut3_43_260646;
	extern lv_obj_t *face_dial_astronaut3_44_260646;
	extern lv_obj_t *face_dial_astronaut3_45_283640;
	extern lv_obj_t *face_dial_astronaut3_46_254865;
	extern lv_obj_t *face_dial_astronaut3_47_41863;


	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_0_1241_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_1);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_2);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_3);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_4);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_5);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_6);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_7);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_8);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_9);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_10);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_11);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_12);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_13);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_1_79333_14);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_2_74779_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_2_74779_1);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_2_74779_2);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_2_74779_3);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_2_74779_4);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_2_74779_5);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_2_74779_6);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_3_248325_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_3_248325_1);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_3_248325_2);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_3_248325_3);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_3_248325_4);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_3_248325_5);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_3_248325_6);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_1);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_2);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_3);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_4);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_5);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_6);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_7);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_8);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_4_260646_9);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_1);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_2);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_3);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_4);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_5);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_6);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_7);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_8);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_8_263560_9);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_1);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_2);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_3);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_4);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_5);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_6);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_7);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_8);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_12_257094_9);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_14_984_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_1);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_2);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_3);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_4);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_5);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_6);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_7);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_8);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_21_262028_9);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_31_72791_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_32_285883_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_33_283901_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_34_279660_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_35_277672_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_36_281650_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_37_287873_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_38_252879_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_39_255110_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_40_41863_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_45_283640_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_46_254865_0);
	LV_IMG_DECLARE(face_dial_astronaut3_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_dial_astronaut3(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **));
    void update_time_dial_astronaut3(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_dial_astronaut3(int temp, int icon);
    void update_status_dial_astronaut3(int battery, bool connection);
    void update_activity_dial_astronaut3(int steps, int distance, int kcal);
    void update_health_dial_astronaut3(int bpm, int oxygen);
    void update_all_dial_astronaut3(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_dial_astronaut3(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
