
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_LOCKSCREEN

#include "dial_lockscreen.h"

#ifdef ENABLE_FACE_DIAL_LOCKSCREEN

lv_obj_t *face_dial_lockscreen;
lv_obj_t *face_dial_lockscreen_0_184;
lv_obj_t *face_dial_lockscreen_2_76556;
lv_obj_t *face_dial_lockscreen_3_81000;
lv_obj_t *face_dial_lockscreen_4_81000;
lv_obj_t *face_dial_lockscreen_5_82534;
lv_obj_t *face_dial_lockscreen_6_82534;
lv_obj_t *face_dial_lockscreen_7_82534;
lv_obj_t *face_dial_lockscreen_8_82534;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_lockscreen_dial_img_1_71734_group[] = {
	&face_dial_lockscreen_dial_img_1_71734_0,
	&face_dial_lockscreen_dial_img_1_71734_1,
	&face_dial_lockscreen_dial_img_1_71734_2,
	&face_dial_lockscreen_dial_img_1_71734_3,
	&face_dial_lockscreen_dial_img_1_71734_4,
	&face_dial_lockscreen_dial_img_1_71734_5,
	&face_dial_lockscreen_dial_img_1_71734_6,
};
const lv_img_dsc_t *face_dial_lockscreen_dial_img_2_76556_group[] = {
	&face_dial_lockscreen_dial_img_2_76556_0,
	&face_dial_lockscreen_dial_img_2_76556_1,
	&face_dial_lockscreen_dial_img_2_76556_2,
	&face_dial_lockscreen_dial_img_2_76556_3,
	&face_dial_lockscreen_dial_img_2_76556_4,
	&face_dial_lockscreen_dial_img_2_76556_5,
	&face_dial_lockscreen_dial_img_2_76556_6,
};
const lv_img_dsc_t *face_dial_lockscreen_dial_img_3_81000_group[] = {
	&face_dial_lockscreen_dial_img_3_81000_0,
	&face_dial_lockscreen_dial_img_3_81000_1,
	&face_dial_lockscreen_dial_img_3_81000_2,
	&face_dial_lockscreen_dial_img_3_81000_3,
	&face_dial_lockscreen_dial_img_3_81000_4,
	&face_dial_lockscreen_dial_img_3_81000_5,
	&face_dial_lockscreen_dial_img_3_81000_6,
	&face_dial_lockscreen_dial_img_3_81000_7,
	&face_dial_lockscreen_dial_img_3_81000_8,
	&face_dial_lockscreen_dial_img_3_81000_9,
};
const lv_img_dsc_t *face_dial_lockscreen_dial_img_5_82534_group[] = {
	&face_dial_lockscreen_dial_img_5_82534_0,
	&face_dial_lockscreen_dial_img_5_82534_1,
	&face_dial_lockscreen_dial_img_5_82534_2,
	&face_dial_lockscreen_dial_img_5_82534_3,
	&face_dial_lockscreen_dial_img_5_82534_4,
	&face_dial_lockscreen_dial_img_5_82534_5,
	&face_dial_lockscreen_dial_img_5_82534_6,
	&face_dial_lockscreen_dial_img_5_82534_7,
	&face_dial_lockscreen_dial_img_5_82534_8,
	&face_dial_lockscreen_dial_img_5_82534_9,
};


#endif

void init_face_dial_lockscreen(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_DIAL_LOCKSCREEN
    face_dial_lockscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_lockscreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_lockscreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_lockscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_lockscreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_lockscreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_lockscreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_lockscreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_lockscreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_lockscreen, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_lockscreen_0_184 = lv_img_create(face_dial_lockscreen);
    lv_img_set_src(face_dial_lockscreen_0_184, &face_dial_lockscreen_dial_img_0_184_0);
    lv_obj_set_width(face_dial_lockscreen_0_184, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_lockscreen_0_184, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_lockscreen_0_184, 0);
    lv_obj_set_y(face_dial_lockscreen_0_184, 0);
    lv_obj_add_flag(face_dial_lockscreen_0_184, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_lockscreen_0_184, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_lockscreen_2_76556 = lv_img_create(face_dial_lockscreen);
    lv_img_set_src(face_dial_lockscreen_2_76556, &face_dial_lockscreen_dial_img_2_76556_0);
    lv_obj_set_width(face_dial_lockscreen_2_76556, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_lockscreen_2_76556, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_lockscreen_2_76556, 80);
    lv_obj_set_y(face_dial_lockscreen_2_76556, 30);
    lv_obj_add_flag(face_dial_lockscreen_2_76556, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_lockscreen_2_76556, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_lockscreen_3_81000 = lv_img_create(face_dial_lockscreen);
    lv_img_set_src(face_dial_lockscreen_3_81000, &face_dial_lockscreen_dial_img_3_81000_0);
    lv_obj_set_width(face_dial_lockscreen_3_81000, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_lockscreen_3_81000, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_lockscreen_3_81000, 143);
    lv_obj_set_y(face_dial_lockscreen_3_81000, 30);
    lv_obj_add_flag(face_dial_lockscreen_3_81000, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_lockscreen_3_81000, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_lockscreen_4_81000 = lv_img_create(face_dial_lockscreen);
    lv_img_set_src(face_dial_lockscreen_4_81000, &face_dial_lockscreen_dial_img_3_81000_0);
    lv_obj_set_width(face_dial_lockscreen_4_81000, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_lockscreen_4_81000, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_lockscreen_4_81000, 132);
    lv_obj_set_y(face_dial_lockscreen_4_81000, 30);
    lv_obj_add_flag(face_dial_lockscreen_4_81000, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_lockscreen_4_81000, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_lockscreen_5_82534 = lv_img_create(face_dial_lockscreen);
    lv_img_set_src(face_dial_lockscreen_5_82534, &face_dial_lockscreen_dial_img_5_82534_0);
    lv_obj_set_width(face_dial_lockscreen_5_82534, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_lockscreen_5_82534, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_lockscreen_5_82534, 79);
    lv_obj_set_y(face_dial_lockscreen_5_82534, 61);
    lv_obj_add_flag(face_dial_lockscreen_5_82534, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_lockscreen_5_82534, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_lockscreen_6_82534 = lv_img_create(face_dial_lockscreen);
    lv_img_set_src(face_dial_lockscreen_6_82534, &face_dial_lockscreen_dial_img_5_82534_0);
    lv_obj_set_width(face_dial_lockscreen_6_82534, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_lockscreen_6_82534, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_lockscreen_6_82534, 44);
    lv_obj_set_y(face_dial_lockscreen_6_82534, 61);
    lv_obj_add_flag(face_dial_lockscreen_6_82534, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_lockscreen_6_82534, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_lockscreen_7_82534 = lv_img_create(face_dial_lockscreen);
    lv_img_set_src(face_dial_lockscreen_7_82534, &face_dial_lockscreen_dial_img_5_82534_0);
    lv_obj_set_width(face_dial_lockscreen_7_82534, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_lockscreen_7_82534, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_lockscreen_7_82534, 160);
    lv_obj_set_y(face_dial_lockscreen_7_82534, 61);
    lv_obj_add_flag(face_dial_lockscreen_7_82534, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_lockscreen_7_82534, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_lockscreen_8_82534 = lv_img_create(face_dial_lockscreen);
    lv_img_set_src(face_dial_lockscreen_8_82534, &face_dial_lockscreen_dial_img_5_82534_0);
    lv_obj_set_width(face_dial_lockscreen_8_82534, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_lockscreen_8_82534, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_lockscreen_8_82534, 125);
    lv_obj_set_y(face_dial_lockscreen_8_82534, 61);
    lv_obj_add_flag(face_dial_lockscreen_8_82534, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_lockscreen_8_82534, LV_OBJ_FLAG_SCROLLABLE );


    callback("dial lockscreen", &face_dial_lockscreen_dial_img_preview_0, &face_dial_lockscreen);

#endif
}

void update_time_dial_lockscreen(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_LOCKSCREEN
    if (!face_dial_lockscreen)
    {
        return;
    }
	lv_img_set_src(face_dial_lockscreen_2_76556, face_dial_lockscreen_dial_img_2_76556_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_dial_lockscreen_3_81000, face_dial_lockscreen_dial_img_3_81000_group[(day / 1) % 10]);
	lv_img_set_src(face_dial_lockscreen_4_81000, face_dial_lockscreen_dial_img_3_81000_group[(day / 10) % 10]);
	lv_img_set_src(face_dial_lockscreen_5_82534, face_dial_lockscreen_dial_img_5_82534_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_lockscreen_6_82534, face_dial_lockscreen_dial_img_5_82534_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_lockscreen_7_82534, face_dial_lockscreen_dial_img_5_82534_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_lockscreen_8_82534, face_dial_lockscreen_dial_img_5_82534_group[(minute / 10) % 10]);

#endif
}

void update_weather_dial_lockscreen(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_LOCKSCREEN
    if (!face_dial_lockscreen)
    {
        return;
    }

#endif
}

void update_status_dial_lockscreen(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_LOCKSCREEN
    if (!face_dial_lockscreen)
    {
        return;
    }

#endif
}

void update_activity_dial_lockscreen(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_LOCKSCREEN
    if (!face_dial_lockscreen)
    {
        return;
    }

#endif
}

void update_health_dial_lockscreen(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_LOCKSCREEN
    if (!face_dial_lockscreen)
    {
        return;
    }

#endif
}

void update_all_dial_lockscreen(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_LOCKSCREEN
    update_time_dial_lockscreen(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_lockscreen(temp, icon);
    update_status_dial_lockscreen(battery, connection);
    update_activity_dial_lockscreen(steps, distance, kcal);
    update_health_dial_lockscreen(bpm, oxygen);
#endif
}

void update_check_dial_lockscreen(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_LOCKSCREEN
    if (root != face_dial_lockscreen)
    {
        return;
    }
    update_time_dial_lockscreen(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_lockscreen(temp, icon);
    update_status_dial_lockscreen(battery, connection);
    update_activity_dial_lockscreen(steps, distance, kcal);
    update_health_dial_lockscreen(bpm, oxygen);
#endif
}


