
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_ASTRONAUT

#ifndef _FACE_DIAL_ASTRONAUT_H
#define _FACE_DIAL_ASTRONAUT_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#define ENABLE_FACE_DIAL_ASTRONAUT // (dial astronaut) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    extern lv_obj_t *face_dial_astronaut;
	extern lv_obj_t *face_dial_astronaut_0_2768;
	extern lv_obj_t *face_dial_astronaut_1_24923;
	extern lv_obj_t *face_dial_astronaut_2_85197;
	extern lv_obj_t *face_dial_astronaut_3_85197;
	extern lv_obj_t *face_dial_astronaut_4_85197;
	extern lv_obj_t *face_dial_astronaut_5_85197;
	extern lv_obj_t *face_dial_astronaut_6_85197;
	extern lv_obj_t *face_dial_astronaut_7_85197;
	extern lv_obj_t *face_dial_astronaut_8_85197;
	extern lv_obj_t *face_dial_astronaut_9_85197;
	extern lv_obj_t *face_dial_astronaut_10_85197;
	extern lv_obj_t *face_dial_astronaut_12_94522;
	extern lv_obj_t *face_dial_astronaut_14_89131;
	extern lv_obj_t *face_dial_astronaut_16_89866;
	extern lv_obj_t *face_dial_astronaut_17_85197;
	extern lv_obj_t *face_dial_astronaut_18_85197;
	extern lv_obj_t *face_dial_astronaut_19_85197;
	extern lv_obj_t *face_dial_astronaut_20_85197;
	extern lv_obj_t *face_dial_astronaut_21_89292;
	extern lv_obj_t *face_dial_astronaut_22_89272;
	extern lv_obj_t *face_dial_astronaut_23_85197;
	extern lv_obj_t *face_dial_astronaut_24_85197;
	extern lv_obj_t *face_dial_astronaut_25_85197;
	extern lv_obj_t *face_dial_astronaut_26_88651;
	extern lv_obj_t *face_dial_astronaut_27_85197;
	extern lv_obj_t *face_dial_astronaut_28_85197;
	extern lv_obj_t *face_dial_astronaut_29_85197;
	extern lv_obj_t *face_dial_astronaut_31_2056;
	extern lv_obj_t *face_dial_astronaut_33_92190;
	extern lv_obj_t *face_dial_astronaut_35_113802;
	extern lv_obj_t *face_dial_astronaut_36_96224;
	extern lv_obj_t *face_dial_astronaut_37_96394;
	extern lv_obj_t *face_dial_astronaut_38_96394;
	extern lv_obj_t *face_dial_astronaut_39_96394;
	extern lv_obj_t *face_dial_astronaut_40_96394;
	extern lv_obj_t *face_dial_astronaut_42_86829;
	extern lv_obj_t *face_dial_astronaut_47_86861;
	extern lv_obj_t *face_dial_astronaut_48_86861;
	extern lv_obj_t *face_dial_astronaut_49_86861;
	extern lv_obj_t *face_dial_astronaut_50_86861;
	extern lv_obj_t *face_dial_astronaut_53_86861;
	extern lv_obj_t *face_dial_astronaut_54_86861;
	extern lv_obj_t *face_dial_astronaut_55_106772;
	extern lv_obj_t *face_dial_astronaut_56_25742;
	extern lv_obj_t *face_dial_astronaut_58_84569;


	LV_IMG_DECLARE(face_dial_astronaut_dial_img_0_2768_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_1_24923_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_1_24923_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_1_24923_2);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_1_24923_3);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_1_24923_4);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_1_24923_5);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_1_24923_6);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_2);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_3);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_4);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_5);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_6);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_7);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_8);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_2_85197_9);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_11_94008_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_12_94522_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_13_88917_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_14_89131_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_15_89638_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_16_89866_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_21_89292_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_22_89272_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_26_88651_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_30_1344_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_30_1344_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_31_2056_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_31_2056_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_32_91516_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_32_91516_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_33_92190_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_33_92190_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_34_106838_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_34_106838_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_34_106838_2);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_34_106838_3);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_34_106838_4);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_34_106838_5);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_34_106838_6);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_35_113802_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_35_113802_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_35_113802_2);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_35_113802_3);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_35_113802_4);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_35_113802_5);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_35_113802_6);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_36_96224_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_2);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_3);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_4);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_5);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_6);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_7);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_8);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_37_96394_9);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_42_86829_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_1);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_2);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_3);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_4);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_5);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_6);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_7);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_8);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_47_86861_9);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_51_25742_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_55_106772_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_58_84569_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_59_95772_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_60_95193_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_61_92864_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_62_90896_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_63_93384_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_64_119072_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_65_88153_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_66_90093_0);
	LV_IMG_DECLARE(face_dial_astronaut_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_dial_astronaut(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **));
    void update_time_dial_astronaut(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_dial_astronaut(int temp, int icon);
    void update_status_dial_astronaut(int battery, bool connection);
    void update_activity_dial_astronaut(int steps, int distance, int kcal);
    void update_health_dial_astronaut(int bpm, int oxygen);
    void update_all_dial_astronaut(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_dial_astronaut(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
