
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_ASTRONAUT

#include "dial_astronaut.h"

#ifdef ENABLE_FACE_DIAL_ASTRONAUT

lv_obj_t *face_dial_astronaut;
lv_obj_t *face_dial_astronaut_0_2768;
lv_obj_t *face_dial_astronaut_1_24923;
lv_obj_t *face_dial_astronaut_2_85197;
lv_obj_t *face_dial_astronaut_3_85197;
lv_obj_t *face_dial_astronaut_4_85197;
lv_obj_t *face_dial_astronaut_5_85197;
lv_obj_t *face_dial_astronaut_6_85197;
lv_obj_t *face_dial_astronaut_7_85197;
lv_obj_t *face_dial_astronaut_8_85197;
lv_obj_t *face_dial_astronaut_9_85197;
lv_obj_t *face_dial_astronaut_10_85197;
lv_obj_t *face_dial_astronaut_12_94522;
lv_obj_t *face_dial_astronaut_14_89131;
lv_obj_t *face_dial_astronaut_16_89866;
lv_obj_t *face_dial_astronaut_17_85197;
lv_obj_t *face_dial_astronaut_18_85197;
lv_obj_t *face_dial_astronaut_19_85197;
lv_obj_t *face_dial_astronaut_20_85197;
lv_obj_t *face_dial_astronaut_21_89292;
lv_obj_t *face_dial_astronaut_22_89272;
lv_obj_t *face_dial_astronaut_23_85197;
lv_obj_t *face_dial_astronaut_24_85197;
lv_obj_t *face_dial_astronaut_25_85197;
lv_obj_t *face_dial_astronaut_26_88651;
lv_obj_t *face_dial_astronaut_27_85197;
lv_obj_t *face_dial_astronaut_28_85197;
lv_obj_t *face_dial_astronaut_29_85197;
lv_obj_t *face_dial_astronaut_31_2056;
lv_obj_t *face_dial_astronaut_33_92190;
lv_obj_t *face_dial_astronaut_35_113802;
lv_obj_t *face_dial_astronaut_36_96224;
lv_obj_t *face_dial_astronaut_37_96394;
lv_obj_t *face_dial_astronaut_38_96394;
lv_obj_t *face_dial_astronaut_39_96394;
lv_obj_t *face_dial_astronaut_40_96394;
lv_obj_t *face_dial_astronaut_42_86829;
lv_obj_t *face_dial_astronaut_47_86861;
lv_obj_t *face_dial_astronaut_48_86861;
lv_obj_t *face_dial_astronaut_49_86861;
lv_obj_t *face_dial_astronaut_50_86861;
lv_obj_t *face_dial_astronaut_53_86861;
lv_obj_t *face_dial_astronaut_54_86861;
lv_obj_t *face_dial_astronaut_55_106772;
lv_obj_t *face_dial_astronaut_56_25742;
lv_obj_t *face_dial_astronaut_58_84569;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_astronaut_dial_img_1_24923_group[] = {
	&face_dial_astronaut_dial_img_1_24923_0,
	&face_dial_astronaut_dial_img_1_24923_1,
	&face_dial_astronaut_dial_img_1_24923_2,
	&face_dial_astronaut_dial_img_1_24923_3,
	&face_dial_astronaut_dial_img_1_24923_4,
	&face_dial_astronaut_dial_img_1_24923_5,
	&face_dial_astronaut_dial_img_1_24923_6,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_2_85197_group[] = {
	&face_dial_astronaut_dial_img_2_85197_0,
	&face_dial_astronaut_dial_img_2_85197_1,
	&face_dial_astronaut_dial_img_2_85197_2,
	&face_dial_astronaut_dial_img_2_85197_3,
	&face_dial_astronaut_dial_img_2_85197_4,
	&face_dial_astronaut_dial_img_2_85197_5,
	&face_dial_astronaut_dial_img_2_85197_6,
	&face_dial_astronaut_dial_img_2_85197_7,
	&face_dial_astronaut_dial_img_2_85197_8,
	&face_dial_astronaut_dial_img_2_85197_9,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_30_1344_group[] = {
	&face_dial_astronaut_dial_img_30_1344_0,
	&face_dial_astronaut_dial_img_30_1344_1,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_31_2056_group[] = {
	&face_dial_astronaut_dial_img_31_2056_0,
	&face_dial_astronaut_dial_img_31_2056_1,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_32_91516_group[] = {
	&face_dial_astronaut_dial_img_32_91516_0,
	&face_dial_astronaut_dial_img_32_91516_1,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_33_92190_group[] = {
	&face_dial_astronaut_dial_img_33_92190_0,
	&face_dial_astronaut_dial_img_33_92190_1,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_34_106838_group[] = {
	&face_dial_astronaut_dial_img_34_106838_0,
	&face_dial_astronaut_dial_img_34_106838_1,
	&face_dial_astronaut_dial_img_34_106838_2,
	&face_dial_astronaut_dial_img_34_106838_3,
	&face_dial_astronaut_dial_img_34_106838_4,
	&face_dial_astronaut_dial_img_34_106838_5,
	&face_dial_astronaut_dial_img_34_106838_6,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_35_113802_group[] = {
	&face_dial_astronaut_dial_img_35_113802_0,
	&face_dial_astronaut_dial_img_35_113802_1,
	&face_dial_astronaut_dial_img_35_113802_2,
	&face_dial_astronaut_dial_img_35_113802_3,
	&face_dial_astronaut_dial_img_35_113802_4,
	&face_dial_astronaut_dial_img_35_113802_5,
	&face_dial_astronaut_dial_img_35_113802_6,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_37_96394_group[] = {
	&face_dial_astronaut_dial_img_37_96394_0,
	&face_dial_astronaut_dial_img_37_96394_1,
	&face_dial_astronaut_dial_img_37_96394_2,
	&face_dial_astronaut_dial_img_37_96394_3,
	&face_dial_astronaut_dial_img_37_96394_4,
	&face_dial_astronaut_dial_img_37_96394_5,
	&face_dial_astronaut_dial_img_37_96394_6,
	&face_dial_astronaut_dial_img_37_96394_7,
	&face_dial_astronaut_dial_img_37_96394_8,
	&face_dial_astronaut_dial_img_37_96394_9,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_47_86861_group[] = {
	&face_dial_astronaut_dial_img_47_86861_0,
	&face_dial_astronaut_dial_img_47_86861_1,
	&face_dial_astronaut_dial_img_47_86861_2,
	&face_dial_astronaut_dial_img_47_86861_3,
	&face_dial_astronaut_dial_img_47_86861_4,
	&face_dial_astronaut_dial_img_47_86861_5,
	&face_dial_astronaut_dial_img_47_86861_6,
	&face_dial_astronaut_dial_img_47_86861_7,
	&face_dial_astronaut_dial_img_47_86861_8,
	&face_dial_astronaut_dial_img_47_86861_9,
};
const lv_img_dsc_t *face_dial_astronaut_dial_img_weather[] = {
	&face_dial_astronaut_dial_img_58_84569_0,
	&face_dial_astronaut_dial_img_59_95772_0,
	&face_dial_astronaut_dial_img_60_95193_0,
	&face_dial_astronaut_dial_img_61_92864_0,
	&face_dial_astronaut_dial_img_62_90896_0,
	&face_dial_astronaut_dial_img_63_93384_0,
	&face_dial_astronaut_dial_img_64_119072_0,
	&face_dial_astronaut_dial_img_65_88153_0,
	&face_dial_astronaut_dial_img_66_90093_0,
};


#endif

void init_face_dial_astronaut(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    face_dial_astronaut = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_astronaut, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_astronaut, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_astronaut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_astronaut, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_astronaut, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_astronaut, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_astronaut, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_astronaut, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_astronaut, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_astronaut_0_2768 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_0_2768, &face_dial_astronaut_dial_img_0_2768_0);
    lv_obj_set_width(face_dial_astronaut_0_2768, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_0_2768, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_0_2768, 9);
    lv_obj_set_y(face_dial_astronaut_0_2768, 71);
    lv_obj_add_flag(face_dial_astronaut_0_2768, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_0_2768, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_1_24923 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_1_24923, &face_dial_astronaut_dial_img_1_24923_0);
    lv_obj_set_width(face_dial_astronaut_1_24923, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_1_24923, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_1_24923, 125);
    lv_obj_set_y(face_dial_astronaut_1_24923, 176);
    lv_obj_add_flag(face_dial_astronaut_1_24923, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_1_24923, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_2_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_2_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_2_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_2_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_2_85197, 98);
    lv_obj_set_y(face_dial_astronaut_2_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_2_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_2_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_3_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_3_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_3_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_3_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_3_85197, 85);
    lv_obj_set_y(face_dial_astronaut_3_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_3_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_3_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_4_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_4_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_4_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_4_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_4_85197, 72);
    lv_obj_set_y(face_dial_astronaut_4_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_4_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_4_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_5_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_5_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_5_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_5_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_5_85197, 59);
    lv_obj_set_y(face_dial_astronaut_5_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_5_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_5_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_6_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_6_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_6_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_6_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_6_85197, 46);
    lv_obj_set_y(face_dial_astronaut_6_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_6_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_6_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_7_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_7_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_7_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_7_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_7_85197, 175);
    lv_obj_set_y(face_dial_astronaut_7_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_7_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_7_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_8_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_8_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_8_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_8_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_8_85197, 162);
    lv_obj_set_y(face_dial_astronaut_8_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_8_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_8_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_9_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_9_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_9_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_9_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_9_85197, 149);
    lv_obj_set_y(face_dial_astronaut_9_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_9_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_9_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_10_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_10_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_10_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_10_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_10_85197, 136);
    lv_obj_set_y(face_dial_astronaut_10_85197, 108);
    lv_obj_add_flag(face_dial_astronaut_10_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_10_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_12_94522 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_12_94522, &face_dial_astronaut_dial_img_12_94522_0);
    lv_obj_set_width(face_dial_astronaut_12_94522, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_12_94522, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_12_94522, 37);
    lv_obj_set_y(face_dial_astronaut_12_94522, 168);
    lv_obj_add_flag(face_dial_astronaut_12_94522, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_12_94522, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_14_89131 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_14_89131, &face_dial_astronaut_dial_img_14_89131_0);
    lv_obj_set_width(face_dial_astronaut_14_89131, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_14_89131, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_14_89131, 61);
    lv_obj_set_y(face_dial_astronaut_14_89131, 187);
    lv_obj_add_flag(face_dial_astronaut_14_89131, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_14_89131, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_16_89866 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_16_89866, &face_dial_astronaut_dial_img_16_89866_0);
    lv_obj_set_width(face_dial_astronaut_16_89866, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_16_89866, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_16_89866, 97);
    lv_obj_set_y(face_dial_astronaut_16_89866, 187);
    lv_obj_add_flag(face_dial_astronaut_16_89866, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_16_89866, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_17_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_17_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_17_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_17_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_17_85197, 49);
    lv_obj_set_y(face_dial_astronaut_17_85197, 183);
    lv_obj_add_flag(face_dial_astronaut_17_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_17_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_18_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_18_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_18_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_18_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_18_85197, 37);
    lv_obj_set_y(face_dial_astronaut_18_85197, 183);
    lv_obj_add_flag(face_dial_astronaut_18_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_18_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_19_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_19_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_19_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_19_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_19_85197, 85);
    lv_obj_set_y(face_dial_astronaut_19_85197, 183);
    lv_obj_add_flag(face_dial_astronaut_19_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_19_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_20_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_20_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_20_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_20_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_20_85197, 73);
    lv_obj_set_y(face_dial_astronaut_20_85197, 183);
    lv_obj_add_flag(face_dial_astronaut_20_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_20_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_21_89292 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_21_89292, &face_dial_astronaut_dial_img_21_89292_0);
    lv_obj_set_width(face_dial_astronaut_21_89292, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_21_89292, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_21_89292, 38);
    lv_obj_set_y(face_dial_astronaut_21_89292, 212);
    lv_obj_add_flag(face_dial_astronaut_21_89292, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_21_89292, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_22_89272 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_22_89272, &face_dial_astronaut_dial_img_22_89272_0);
    lv_obj_set_width(face_dial_astronaut_22_89272, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_22_89272, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_22_89272, 66);
    lv_obj_set_y(face_dial_astronaut_22_89272, 226);
    lv_obj_add_flag(face_dial_astronaut_22_89272, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_22_89272, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_23_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_23_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_23_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_23_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_23_85197, 83);
    lv_obj_set_y(face_dial_astronaut_23_85197, 212);
    lv_obj_add_flag(face_dial_astronaut_23_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_23_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_24_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_24_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_24_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_24_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_24_85197, 71);
    lv_obj_set_y(face_dial_astronaut_24_85197, 212);
    lv_obj_add_flag(face_dial_astronaut_24_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_24_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_25_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_25_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_25_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_25_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_25_85197, 53);
    lv_obj_set_y(face_dial_astronaut_25_85197, 212);
    lv_obj_add_flag(face_dial_astronaut_25_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_25_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_26_88651 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_26_88651, &face_dial_astronaut_dial_img_26_88651_0);
    lv_obj_set_width(face_dial_astronaut_26_88651, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_26_88651, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_26_88651, 37);
    lv_obj_set_y(face_dial_astronaut_26_88651, 238);
    lv_obj_add_flag(face_dial_astronaut_26_88651, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_26_88651, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_27_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_27_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_27_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_27_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_27_85197, 84);
    lv_obj_set_y(face_dial_astronaut_27_85197, 236);
    lv_obj_add_flag(face_dial_astronaut_27_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_27_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_28_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_28_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_28_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_28_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_28_85197, 72);
    lv_obj_set_y(face_dial_astronaut_28_85197, 236);
    lv_obj_add_flag(face_dial_astronaut_28_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_28_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_29_85197 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_29_85197, &face_dial_astronaut_dial_img_2_85197_0);
    lv_obj_set_width(face_dial_astronaut_29_85197, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_29_85197, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_29_85197, 60);
    lv_obj_set_y(face_dial_astronaut_29_85197, 236);
    lv_obj_add_flag(face_dial_astronaut_29_85197, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_29_85197, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_31_2056 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_31_2056, &face_dial_astronaut_dial_img_31_2056_0);
    lv_obj_set_width(face_dial_astronaut_31_2056, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_31_2056, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_31_2056, 49);
    lv_obj_set_y(face_dial_astronaut_31_2056, 146);
    lv_obj_add_flag(face_dial_astronaut_31_2056, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_31_2056, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_33_92190 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_33_92190, &face_dial_astronaut_dial_img_33_92190_0);
    lv_obj_set_width(face_dial_astronaut_33_92190, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_33_92190, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_33_92190, 82);
    lv_obj_set_y(face_dial_astronaut_33_92190, 146);
    lv_obj_add_flag(face_dial_astronaut_33_92190, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_33_92190, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_35_113802 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_35_113802, &face_dial_astronaut_dial_img_35_113802_0);
    lv_obj_set_width(face_dial_astronaut_35_113802, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_35_113802, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_35_113802, 153);
    lv_obj_set_y(face_dial_astronaut_35_113802, 144);
    lv_obj_add_flag(face_dial_astronaut_35_113802, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_35_113802, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_36_96224 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_36_96224, &face_dial_astronaut_dial_img_36_96224_0);
    lv_obj_set_width(face_dial_astronaut_36_96224, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_36_96224, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_36_96224, 117);
    lv_obj_set_y(face_dial_astronaut_36_96224, 29);
    lv_obj_add_flag(face_dial_astronaut_36_96224, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_36_96224, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_37_96394 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_37_96394, &face_dial_astronaut_dial_img_37_96394_0);
    lv_obj_set_width(face_dial_astronaut_37_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_37_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_37_96394, 79);
    lv_obj_set_y(face_dial_astronaut_37_96394, 19);
    lv_obj_add_flag(face_dial_astronaut_37_96394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_37_96394, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_38_96394 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_38_96394, &face_dial_astronaut_dial_img_37_96394_0);
    lv_obj_set_width(face_dial_astronaut_38_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_38_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_38_96394, 50);
    lv_obj_set_y(face_dial_astronaut_38_96394, 19);
    lv_obj_add_flag(face_dial_astronaut_38_96394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_38_96394, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_39_96394 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_39_96394, &face_dial_astronaut_dial_img_37_96394_0);
    lv_obj_set_width(face_dial_astronaut_39_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_39_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_39_96394, 166);
    lv_obj_set_y(face_dial_astronaut_39_96394, 19);
    lv_obj_add_flag(face_dial_astronaut_39_96394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_39_96394, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_40_96394 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_40_96394, &face_dial_astronaut_dial_img_37_96394_0);
    lv_obj_set_width(face_dial_astronaut_40_96394, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_40_96394, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_40_96394, 137);
    lv_obj_set_y(face_dial_astronaut_40_96394, 19);
    lv_obj_add_flag(face_dial_astronaut_40_96394, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_40_96394, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_42_86829 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_42_86829, &face_dial_astronaut_dial_img_42_86829_0);
    lv_obj_set_width(face_dial_astronaut_42_86829, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_42_86829, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_42_86829, 167);
    lv_obj_set_y(face_dial_astronaut_42_86829, 80);
    lv_obj_add_flag(face_dial_astronaut_42_86829, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_42_86829, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_47_86861 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_47_86861, &face_dial_astronaut_dial_img_47_86861_0);
    lv_obj_set_width(face_dial_astronaut_47_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_47_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_47_86861, 188);
    lv_obj_set_y(face_dial_astronaut_47_86861, 75);
    lv_obj_add_flag(face_dial_astronaut_47_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_47_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_48_86861 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_48_86861, &face_dial_astronaut_dial_img_47_86861_0);
    lv_obj_set_width(face_dial_astronaut_48_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_48_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_48_86861, 176);
    lv_obj_set_y(face_dial_astronaut_48_86861, 75);
    lv_obj_add_flag(face_dial_astronaut_48_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_48_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_49_86861 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_49_86861, &face_dial_astronaut_dial_img_47_86861_0);
    lv_obj_set_width(face_dial_astronaut_49_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_49_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_49_86861, 156);
    lv_obj_set_y(face_dial_astronaut_49_86861, 75);
    lv_obj_add_flag(face_dial_astronaut_49_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_49_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_50_86861 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_50_86861, &face_dial_astronaut_dial_img_47_86861_0);
    lv_obj_set_width(face_dial_astronaut_50_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_50_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_50_86861, 144);
    lv_obj_set_y(face_dial_astronaut_50_86861, 75);
    lv_obj_add_flag(face_dial_astronaut_50_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_50_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_53_86861 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_53_86861, &face_dial_astronaut_dial_img_47_86861_0);
    lv_obj_set_width(face_dial_astronaut_53_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_53_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_53_86861, 89);
    lv_obj_set_y(face_dial_astronaut_53_86861, 75);
    lv_obj_add_flag(face_dial_astronaut_53_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_53_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_54_86861 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_54_86861, &face_dial_astronaut_dial_img_47_86861_0);
    lv_obj_set_width(face_dial_astronaut_54_86861, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_54_86861, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_54_86861, 77);
    lv_obj_set_y(face_dial_astronaut_54_86861, 75);
    lv_obj_add_flag(face_dial_astronaut_54_86861, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_54_86861, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_55_106772 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_55_106772, &face_dial_astronaut_dial_img_55_106772_0);
    lv_obj_set_width(face_dial_astronaut_55_106772, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_55_106772, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_55_106772, 101);
    lv_obj_set_y(face_dial_astronaut_55_106772, 75);
    lv_obj_add_flag(face_dial_astronaut_55_106772, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_55_106772, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_56_25742 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_56_25742, &face_dial_astronaut_dial_img_51_25742_0);
    lv_obj_set_width(face_dial_astronaut_56_25742, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_56_25742, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_56_25742, 71);
    lv_obj_set_y(face_dial_astronaut_56_25742, 69);
    lv_obj_add_flag(face_dial_astronaut_56_25742, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_56_25742, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut_58_84569 = lv_img_create(face_dial_astronaut);
    lv_img_set_src(face_dial_astronaut_58_84569, &face_dial_astronaut_dial_img_58_84569_0);
    lv_obj_set_width(face_dial_astronaut_58_84569, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut_58_84569, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut_58_84569, 38);
    lv_obj_set_y(face_dial_astronaut_58_84569, 71);
    lv_obj_add_flag(face_dial_astronaut_58_84569, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut_58_84569, LV_OBJ_FLAG_SCROLLABLE );


    callback("dial astronaut", &face_dial_astronaut_dial_img_preview_0, &face_dial_astronaut);

#endif
}

void update_time_dial_astronaut(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    if (!face_dial_astronaut)
    {
        return;
    }
	if (mode)
	{
		lv_obj_add_flag(face_dial_astronaut_31_2056, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_astronaut_31_2056, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_astronaut_31_2056, face_dial_astronaut_dial_img_31_2056_group[(am ? 0 : 1) % 2]);
	if (mode)
	{
		lv_obj_add_flag(face_dial_astronaut_33_92190, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_astronaut_33_92190, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_astronaut_33_92190, face_dial_astronaut_dial_img_33_92190_group[(am ? 0 : 1) % 2]);
	lv_img_set_src(face_dial_astronaut_35_113802, face_dial_astronaut_dial_img_35_113802_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_dial_astronaut_37_96394, face_dial_astronaut_dial_img_37_96394_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_38_96394, face_dial_astronaut_dial_img_37_96394_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_astronaut_39_96394, face_dial_astronaut_dial_img_37_96394_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_40_96394, face_dial_astronaut_dial_img_37_96394_group[(minute / 10) % 10]);
	lv_img_set_src(face_dial_astronaut_47_86861, face_dial_astronaut_dial_img_47_86861_group[(month / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_48_86861, face_dial_astronaut_dial_img_47_86861_group[(month / 10) % 10]);
	lv_img_set_src(face_dial_astronaut_49_86861, face_dial_astronaut_dial_img_47_86861_group[(day / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_50_86861, face_dial_astronaut_dial_img_47_86861_group[(day / 10) % 10]);

#endif
}

void update_weather_dial_astronaut(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    if (!face_dial_astronaut)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut_53_86861, face_dial_astronaut_dial_img_47_86861_group[(temp / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_54_86861, face_dial_astronaut_dial_img_47_86861_group[(temp / 10) % 10]);
	if (temp >= 0)
	{
		lv_obj_add_flag(face_dial_astronaut_56_25742, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_astronaut_56_25742, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_astronaut_58_84569, face_dial_astronaut_dial_img_weather[icon % 8]);

#endif
}

void update_status_dial_astronaut(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    if (!face_dial_astronaut)
    {
        return;
    }

#endif
}

void update_activity_dial_astronaut(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    if (!face_dial_astronaut)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut_2_85197, face_dial_astronaut_dial_img_2_85197_group[(steps / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_3_85197, face_dial_astronaut_dial_img_2_85197_group[(steps / 10) % 10]);
	lv_img_set_src(face_dial_astronaut_4_85197, face_dial_astronaut_dial_img_2_85197_group[(steps / 100) % 10]);
	lv_img_set_src(face_dial_astronaut_5_85197, face_dial_astronaut_dial_img_2_85197_group[(steps / 1000) % 10]);
	lv_img_set_src(face_dial_astronaut_6_85197, face_dial_astronaut_dial_img_2_85197_group[(steps / 10000) % 10]);
	lv_img_set_src(face_dial_astronaut_7_85197, face_dial_astronaut_dial_img_2_85197_group[(kcal / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_8_85197, face_dial_astronaut_dial_img_2_85197_group[(kcal / 10) % 10]);
	lv_img_set_src(face_dial_astronaut_9_85197, face_dial_astronaut_dial_img_2_85197_group[(kcal / 100) % 10]);
	lv_img_set_src(face_dial_astronaut_10_85197, face_dial_astronaut_dial_img_2_85197_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_dial_astronaut_23_85197, face_dial_astronaut_dial_img_2_85197_group[(distance / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_24_85197, face_dial_astronaut_dial_img_2_85197_group[(distance / 10) % 10]);
	lv_img_set_src(face_dial_astronaut_25_85197, face_dial_astronaut_dial_img_2_85197_group[(distance / 100) % 10]);

#endif
}

void update_health_dial_astronaut(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    if (!face_dial_astronaut)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut_27_85197, face_dial_astronaut_dial_img_2_85197_group[(bpm / 1) % 10]);
	lv_img_set_src(face_dial_astronaut_28_85197, face_dial_astronaut_dial_img_2_85197_group[(bpm / 10) % 10]);
	lv_img_set_src(face_dial_astronaut_29_85197, face_dial_astronaut_dial_img_2_85197_group[(bpm / 100) % 10]);

#endif
}

void update_all_dial_astronaut(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    update_time_dial_astronaut(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_astronaut(temp, icon);
    update_status_dial_astronaut(battery, connection);
    update_activity_dial_astronaut(steps, distance, kcal);
    update_health_dial_astronaut(bpm, oxygen);
#endif
}

void update_check_dial_astronaut(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT
    if (root != face_dial_astronaut)
    {
        return;
    }
    update_time_dial_astronaut(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_astronaut(temp, icon);
    update_status_dial_astronaut(battery, connection);
    update_activity_dial_astronaut(steps, distance, kcal);
    update_health_dial_astronaut(bpm, oxygen);
#endif
}


