
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_ASTRONAUT2

#include "../dial_astronaut2.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_dial_astronaut2_dial_img_43_15549_data_0[] = {
	0x00,0x00,0x00,0x42,0x08,0xFF,0x00,0x00,0x00,0x8C,0x71,0xFF,0xFF,0xFF,0xFF,0x42,0x08,0xFF,0x42,0x08,0xFF,0x8C,0x71,0xFF,0x00,0x00,0x00,
    };
        


const lv_img_dsc_t face_dial_astronaut2_dial_img_43_15549_0 = {
    .header.always_zero = 0,
    .header.w = 3,
    .header.h = 3,
    .data_size = sizeof(face_dial_astronaut2_dial_img_43_15549_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_dial_astronaut2_dial_img_43_15549_data_0};

    