
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ANALOG_NIKE

#include "../analog_nike.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_analog_nike_dial_img_57_46486_data_0[] = {
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    };
        


const lv_img_dsc_t face_analog_nike_dial_img_57_46486_0 = {
    .header.always_zero = 0,
    .header.w = 6,
    .header.h = 2,
    .data_size = sizeof(face_analog_nike_dial_img_57_46486_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_analog_nike_dial_img_57_46486_data_0};

    