
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ANALOG_NIKE

#include "../analog_nike.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_analog_nike_dial_img_3_128886_data_0[] = {
	0xE7,0x3C,0xFF,0xE7,0x3C,0xFF,0xE7,0x3C,0xFF,0xE7,0x3C,0xFF,0xFF,0xFF,0xFF,
    };
        


const lv_img_dsc_t face_analog_nike_dial_img_3_128886_0 = {
    .header.always_zero = 0,
    .header.w = 5,
    .header.h = 1,
    .data_size = sizeof(face_analog_nike_dial_img_3_128886_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_analog_nike_dial_img_3_128886_data_0};

    