
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_ASTRONAUT2

#ifndef _FACE_DIAL_ASTRONAUT2_H
#define _FACE_DIAL_ASTRONAUT2_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#define ENABLE_FACE_DIAL_ASTRONAUT2 // (dial astronaut2) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    extern lv_obj_t *face_dial_astronaut2;
	extern lv_obj_t *face_dial_astronaut2_0_15784;
	extern lv_obj_t *face_dial_astronaut2_1_87334;
	extern lv_obj_t *face_dial_astronaut2_3_1284;
	extern lv_obj_t *face_dial_astronaut2_12_65535;
	extern lv_obj_t *face_dial_astronaut2_13_65535;
	extern lv_obj_t *face_dial_astronaut2_14_11675;
	extern lv_obj_t *face_dial_astronaut2_15_11675;
	extern lv_obj_t *face_dial_astronaut2_16_11675;
	extern lv_obj_t *face_dial_astronaut2_17_11557;
	extern lv_obj_t *face_dial_astronaut2_18_3918;
	extern lv_obj_t *face_dial_astronaut2_19_65535;
	extern lv_obj_t *face_dial_astronaut2_20_3788;
	extern lv_obj_t *face_dial_astronaut2_21_11675;
	extern lv_obj_t *face_dial_astronaut2_22_11675;
	extern lv_obj_t *face_dial_astronaut2_23_11675;
	extern lv_obj_t *face_dial_astronaut2_24_11675;
	extern lv_obj_t *face_dial_astronaut2_25_11675;
	extern lv_obj_t *face_dial_astronaut2_26_11675;
	extern lv_obj_t *face_dial_astronaut2_27_11675;
	extern lv_obj_t *face_dial_astronaut2_28_11675;
	extern lv_obj_t *face_dial_astronaut2_29_11675;
	extern lv_obj_t *face_dial_astronaut2_30_11675;
	extern lv_obj_t *face_dial_astronaut2_31_11675;
	extern lv_obj_t *face_dial_astronaut2_32_11675;
	extern lv_obj_t *face_dial_astronaut2_33_11675;
	extern lv_obj_t *face_dial_astronaut2_34_11675;
	extern lv_obj_t *face_dial_astronaut2_35_11675;
	extern lv_obj_t *face_dial_astronaut2_37_4462;
	extern lv_obj_t *face_dial_astronaut2_39_4034;
	extern lv_obj_t *face_dial_astronaut2_40_11675;
	extern lv_obj_t *face_dial_astronaut2_41_11675;
	extern lv_obj_t *face_dial_astronaut2_42_11675;
	extern lv_obj_t *face_dial_astronaut2_43_15549;
	extern lv_obj_t *face_dial_astronaut2_45_13977;
	extern lv_obj_t *face_dial_astronaut2_46_11675;
	extern lv_obj_t *face_dial_astronaut2_47_11675;
	extern lv_obj_t *face_dial_astronaut2_48_11675;
	extern lv_obj_t *face_dial_astronaut2_49_11675;
	extern lv_obj_t *face_dial_astronaut2_50_4682;
	extern lv_obj_t *face_dial_astronaut2_51_4682;
	extern lv_obj_t *face_dial_astronaut2_52_4682;
	extern lv_obj_t *face_dial_astronaut2_53_4682;
	extern lv_obj_t *face_dial_astronaut2_54_4682;
	extern lv_obj_t *face_dial_astronaut2_55_4682;
	extern lv_obj_t *face_dial_astronaut2_56_11675;
	extern lv_obj_t *face_dial_astronaut2_57_11675;
	extern lv_obj_t *face_dial_astronaut2_58_11675;
	extern lv_obj_t *face_dial_astronaut2_59_11675;
	extern lv_obj_t *face_dial_astronaut2_60_11364;
	extern lv_obj_t *face_dial_astronaut2_61_11446;


	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_0_15784_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_1);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_2);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_3);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_4);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_5);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_6);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_7);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_8);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_9);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_10);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_11);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_12);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_13);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_1_87334_14);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_3_1284_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_4_1566_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_5_1860_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_6_2170_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_7_2450_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_8_2692_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_9_2944_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_10_3224_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_11_3536_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_12_65535_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_1);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_2);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_3);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_4);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_5);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_6);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_7);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_8);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_14_11675_9);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_17_11557_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_18_3918_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_20_3788_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_36_15566_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_37_4462_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_38_4248_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_39_4034_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_43_15549_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_44_12407_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_44_12407_1);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_44_12407_2);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_44_12407_3);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_44_12407_4);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_44_12407_5);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_44_12407_6);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_45_13977_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_45_13977_1);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_45_13977_2);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_45_13977_3);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_45_13977_4);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_45_13977_5);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_45_13977_6);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_1);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_2);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_3);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_4);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_5);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_6);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_7);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_8);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_50_4682_9);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_60_11364_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_61_11446_0);
	LV_IMG_DECLARE(face_dial_astronaut2_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_dial_astronaut2(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **));
    void update_time_dial_astronaut2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_dial_astronaut2(int temp, int icon);
    void update_status_dial_astronaut2(int battery, bool connection);
    void update_activity_dial_astronaut2(int steps, int distance, int kcal);
    void update_health_dial_astronaut2(int bpm, int oxygen);
    void update_all_dial_astronaut2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_dial_astronaut2(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
