
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_ASTRONAUT2

#include "dial_astronaut2.h"

#ifdef ENABLE_FACE_DIAL_ASTRONAUT2

lv_obj_t *face_dial_astronaut2;
lv_obj_t *face_dial_astronaut2_0_15784;
lv_obj_t *face_dial_astronaut2_1_87334;
lv_obj_t *face_dial_astronaut2_3_1284;
lv_obj_t *face_dial_astronaut2_12_65535;
lv_obj_t *face_dial_astronaut2_13_65535;
lv_obj_t *face_dial_astronaut2_14_11675;
lv_obj_t *face_dial_astronaut2_15_11675;
lv_obj_t *face_dial_astronaut2_16_11675;
lv_obj_t *face_dial_astronaut2_17_11557;
lv_obj_t *face_dial_astronaut2_18_3918;
lv_obj_t *face_dial_astronaut2_19_65535;
lv_obj_t *face_dial_astronaut2_20_3788;
lv_obj_t *face_dial_astronaut2_21_11675;
lv_obj_t *face_dial_astronaut2_22_11675;
lv_obj_t *face_dial_astronaut2_23_11675;
lv_obj_t *face_dial_astronaut2_24_11675;
lv_obj_t *face_dial_astronaut2_25_11675;
lv_obj_t *face_dial_astronaut2_26_11675;
lv_obj_t *face_dial_astronaut2_27_11675;
lv_obj_t *face_dial_astronaut2_28_11675;
lv_obj_t *face_dial_astronaut2_29_11675;
lv_obj_t *face_dial_astronaut2_30_11675;
lv_obj_t *face_dial_astronaut2_31_11675;
lv_obj_t *face_dial_astronaut2_32_11675;
lv_obj_t *face_dial_astronaut2_33_11675;
lv_obj_t *face_dial_astronaut2_34_11675;
lv_obj_t *face_dial_astronaut2_35_11675;
lv_obj_t *face_dial_astronaut2_37_4462;
lv_obj_t *face_dial_astronaut2_39_4034;
lv_obj_t *face_dial_astronaut2_40_11675;
lv_obj_t *face_dial_astronaut2_41_11675;
lv_obj_t *face_dial_astronaut2_42_11675;
lv_obj_t *face_dial_astronaut2_43_15549;
lv_obj_t *face_dial_astronaut2_45_13977;
lv_obj_t *face_dial_astronaut2_46_11675;
lv_obj_t *face_dial_astronaut2_47_11675;
lv_obj_t *face_dial_astronaut2_48_11675;
lv_obj_t *face_dial_astronaut2_49_11675;
lv_obj_t *face_dial_astronaut2_50_4682;
lv_obj_t *face_dial_astronaut2_51_4682;
lv_obj_t *face_dial_astronaut2_52_4682;
lv_obj_t *face_dial_astronaut2_53_4682;
lv_obj_t *face_dial_astronaut2_54_4682;
lv_obj_t *face_dial_astronaut2_55_4682;
lv_obj_t *face_dial_astronaut2_56_11675;
lv_obj_t *face_dial_astronaut2_57_11675;
lv_obj_t *face_dial_astronaut2_58_11675;
lv_obj_t *face_dial_astronaut2_59_11675;
lv_obj_t *face_dial_astronaut2_60_11364;
lv_obj_t *face_dial_astronaut2_61_11446;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_astronaut2_dial_img_1_87334_group[] = {
	&face_dial_astronaut2_dial_img_1_87334_0,
	&face_dial_astronaut2_dial_img_1_87334_1,
	&face_dial_astronaut2_dial_img_1_87334_2,
	&face_dial_astronaut2_dial_img_1_87334_3,
	&face_dial_astronaut2_dial_img_1_87334_4,
	&face_dial_astronaut2_dial_img_1_87334_5,
	&face_dial_astronaut2_dial_img_1_87334_6,
	&face_dial_astronaut2_dial_img_1_87334_7,
	&face_dial_astronaut2_dial_img_1_87334_8,
	&face_dial_astronaut2_dial_img_1_87334_9,
	&face_dial_astronaut2_dial_img_1_87334_10,
	&face_dial_astronaut2_dial_img_1_87334_11,
	&face_dial_astronaut2_dial_img_1_87334_12,
	&face_dial_astronaut2_dial_img_1_87334_13,
	&face_dial_astronaut2_dial_img_1_87334_14,
};
const lv_img_dsc_t *face_dial_astronaut2_dial_img_weather[] = {
	&face_dial_astronaut2_dial_img_3_1284_0,
	&face_dial_astronaut2_dial_img_4_1566_0,
	&face_dial_astronaut2_dial_img_5_1860_0,
	&face_dial_astronaut2_dial_img_6_2170_0,
	&face_dial_astronaut2_dial_img_7_2450_0,
	&face_dial_astronaut2_dial_img_8_2692_0,
	&face_dial_astronaut2_dial_img_9_2944_0,
	&face_dial_astronaut2_dial_img_10_3224_0,
	&face_dial_astronaut2_dial_img_11_3536_0,
};
const lv_img_dsc_t *face_dial_astronaut2_dial_img_14_11675_group[] = {
	&face_dial_astronaut2_dial_img_14_11675_0,
	&face_dial_astronaut2_dial_img_14_11675_1,
	&face_dial_astronaut2_dial_img_14_11675_2,
	&face_dial_astronaut2_dial_img_14_11675_3,
	&face_dial_astronaut2_dial_img_14_11675_4,
	&face_dial_astronaut2_dial_img_14_11675_5,
	&face_dial_astronaut2_dial_img_14_11675_6,
	&face_dial_astronaut2_dial_img_14_11675_7,
	&face_dial_astronaut2_dial_img_14_11675_8,
	&face_dial_astronaut2_dial_img_14_11675_9,
};
const lv_img_dsc_t *face_dial_astronaut2_dial_img_44_12407_group[] = {
	&face_dial_astronaut2_dial_img_44_12407_0,
	&face_dial_astronaut2_dial_img_44_12407_1,
	&face_dial_astronaut2_dial_img_44_12407_2,
	&face_dial_astronaut2_dial_img_44_12407_3,
	&face_dial_astronaut2_dial_img_44_12407_4,
	&face_dial_astronaut2_dial_img_44_12407_5,
	&face_dial_astronaut2_dial_img_44_12407_6,
};
const lv_img_dsc_t *face_dial_astronaut2_dial_img_45_13977_group[] = {
	&face_dial_astronaut2_dial_img_45_13977_0,
	&face_dial_astronaut2_dial_img_45_13977_1,
	&face_dial_astronaut2_dial_img_45_13977_2,
	&face_dial_astronaut2_dial_img_45_13977_3,
	&face_dial_astronaut2_dial_img_45_13977_4,
	&face_dial_astronaut2_dial_img_45_13977_5,
	&face_dial_astronaut2_dial_img_45_13977_6,
};
const lv_img_dsc_t *face_dial_astronaut2_dial_img_50_4682_group[] = {
	&face_dial_astronaut2_dial_img_50_4682_0,
	&face_dial_astronaut2_dial_img_50_4682_1,
	&face_dial_astronaut2_dial_img_50_4682_2,
	&face_dial_astronaut2_dial_img_50_4682_3,
	&face_dial_astronaut2_dial_img_50_4682_4,
	&face_dial_astronaut2_dial_img_50_4682_5,
	&face_dial_astronaut2_dial_img_50_4682_6,
	&face_dial_astronaut2_dial_img_50_4682_7,
	&face_dial_astronaut2_dial_img_50_4682_8,
	&face_dial_astronaut2_dial_img_50_4682_9,
};


#endif

void init_face_dial_astronaut2(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    face_dial_astronaut2 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_astronaut2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_astronaut2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_astronaut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_astronaut2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_astronaut2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_astronaut2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_astronaut2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_astronaut2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_astronaut2, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_astronaut2_0_15784 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_0_15784, &face_dial_astronaut2_dial_img_0_15784_0);
    lv_obj_set_width(face_dial_astronaut2_0_15784, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_0_15784, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_0_15784, 0);
    lv_obj_set_y(face_dial_astronaut2_0_15784, 0);
    lv_obj_add_flag(face_dial_astronaut2_0_15784, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_0_15784, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_1_87334 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_1_87334, &face_dial_astronaut2_dial_img_1_87334_0);
    lv_obj_set_width(face_dial_astronaut2_1_87334, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_1_87334, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_1_87334, 94);
    lv_obj_set_y(face_dial_astronaut2_1_87334, 101);
    lv_obj_add_flag(face_dial_astronaut2_1_87334, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_1_87334, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_3_1284 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_3_1284, &face_dial_astronaut2_dial_img_3_1284_0);
    lv_obj_set_width(face_dial_astronaut2_3_1284, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_3_1284, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_3_1284, 128);
    lv_obj_set_y(face_dial_astronaut2_3_1284, 37);
    lv_obj_add_flag(face_dial_astronaut2_3_1284, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_3_1284, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_12_65535 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_12_65535, &face_dial_astronaut2_dial_img_12_65535_0);
    lv_obj_set_width(face_dial_astronaut2_12_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_12_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_12_65535, 108);
    lv_obj_set_y(face_dial_astronaut2_12_65535, 41);
    lv_obj_add_flag(face_dial_astronaut2_12_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_12_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_13_65535 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_13_65535, &face_dial_astronaut2_dial_img_12_65535_0);
    lv_obj_set_width(face_dial_astronaut2_13_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_13_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_13_65535, 98);
    lv_obj_set_y(face_dial_astronaut2_13_65535, 41);
    lv_obj_add_flag(face_dial_astronaut2_13_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_13_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_14_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_14_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_14_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_14_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_14_11675, 105);
    lv_obj_set_y(face_dial_astronaut2_14_11675, 37);
    lv_obj_add_flag(face_dial_astronaut2_14_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_14_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_15_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_15_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_15_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_15_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_15_11675, 98);
    lv_obj_set_y(face_dial_astronaut2_15_11675, 37);
    lv_obj_add_flag(face_dial_astronaut2_15_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_15_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_16_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_16_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_16_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_16_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_16_11675, 91);
    lv_obj_set_y(face_dial_astronaut2_16_11675, 37);
    lv_obj_add_flag(face_dial_astronaut2_16_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_16_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_17_11557 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_17_11557, &face_dial_astronaut2_dial_img_17_11557_0);
    lv_obj_set_width(face_dial_astronaut2_17_11557, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_17_11557, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_17_11557, 112);
    lv_obj_set_y(face_dial_astronaut2_17_11557, 37);
    lv_obj_add_flag(face_dial_astronaut2_17_11557, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_17_11557, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_18_3918 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_18_3918, &face_dial_astronaut2_dial_img_18_3918_0);
    lv_obj_set_width(face_dial_astronaut2_18_3918, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_18_3918, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_18_3918, 112);
    lv_obj_set_y(face_dial_astronaut2_18_3918, 37);
    lv_obj_add_flag(face_dial_astronaut2_18_3918, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_18_3918, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_19_65535 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_19_65535, &face_dial_astronaut2_dial_img_12_65535_0);
    lv_obj_set_width(face_dial_astronaut2_19_65535, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_19_65535, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_19_65535, 90);
    lv_obj_set_y(face_dial_astronaut2_19_65535, 41);
    lv_obj_add_flag(face_dial_astronaut2_19_65535, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_19_65535, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_20_3788 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_20_3788, &face_dial_astronaut2_dial_img_20_3788_0);
    lv_obj_set_width(face_dial_astronaut2_20_3788, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_20_3788, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_20_3788, 145);
    lv_obj_set_y(face_dial_astronaut2_20_3788, 16);
    lv_obj_add_flag(face_dial_astronaut2_20_3788, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_20_3788, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_21_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_21_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_21_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_21_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_21_11675, 133);
    lv_obj_set_y(face_dial_astronaut2_21_11675, 16);
    lv_obj_add_flag(face_dial_astronaut2_21_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_21_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_22_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_22_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_22_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_22_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_22_11675, 126);
    lv_obj_set_y(face_dial_astronaut2_22_11675, 16);
    lv_obj_add_flag(face_dial_astronaut2_22_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_22_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_23_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_23_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_23_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_23_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_23_11675, 119);
    lv_obj_set_y(face_dial_astronaut2_23_11675, 16);
    lv_obj_add_flag(face_dial_astronaut2_23_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_23_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_24_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_24_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_24_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_24_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_24_11675, 225);
    lv_obj_set_y(face_dial_astronaut2_24_11675, 113);
    lv_obj_add_flag(face_dial_astronaut2_24_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_24_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_25_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_25_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_25_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_25_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_25_11675, 218);
    lv_obj_set_y(face_dial_astronaut2_25_11675, 113);
    lv_obj_add_flag(face_dial_astronaut2_25_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_25_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_26_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_26_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_26_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_26_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_26_11675, 211);
    lv_obj_set_y(face_dial_astronaut2_26_11675, 113);
    lv_obj_add_flag(face_dial_astronaut2_26_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_26_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_27_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_27_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_27_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_27_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_27_11675, 133);
    lv_obj_set_y(face_dial_astronaut2_27_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_27_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_27_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_28_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_28_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_28_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_28_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_28_11675, 126);
    lv_obj_set_y(face_dial_astronaut2_28_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_28_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_28_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_29_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_29_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_29_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_29_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_29_11675, 119);
    lv_obj_set_y(face_dial_astronaut2_29_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_29_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_29_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_30_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_30_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_30_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_30_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_30_11675, 112);
    lv_obj_set_y(face_dial_astronaut2_30_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_30_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_30_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_31_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_31_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_31_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_31_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_31_11675, 71);
    lv_obj_set_y(face_dial_astronaut2_31_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_31_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_31_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_32_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_32_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_32_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_32_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_32_11675, 64);
    lv_obj_set_y(face_dial_astronaut2_32_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_32_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_32_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_33_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_33_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_33_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_33_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_33_11675, 57);
    lv_obj_set_y(face_dial_astronaut2_33_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_33_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_33_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_34_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_34_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_34_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_34_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_34_11675, 50);
    lv_obj_set_y(face_dial_astronaut2_34_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_34_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_34_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_35_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_35_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_35_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_35_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_35_11675, 43);
    lv_obj_set_y(face_dial_astronaut2_35_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_35_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_35_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_37_4462 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_37_4462, &face_dial_astronaut2_dial_img_37_4462_0);
    lv_obj_set_width(face_dial_astronaut2_37_4462, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_37_4462, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_37_4462, 203);
    lv_obj_set_y(face_dial_astronaut2_37_4462, 207);
    lv_obj_add_flag(face_dial_astronaut2_37_4462, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_37_4462, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_39_4034 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_39_4034, &face_dial_astronaut2_dial_img_39_4034_0);
    lv_obj_set_width(face_dial_astronaut2_39_4034, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_39_4034, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_39_4034, 203);
    lv_obj_set_y(face_dial_astronaut2_39_4034, 207);
    lv_obj_add_flag(face_dial_astronaut2_39_4034, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_39_4034, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_40_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_40_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_40_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_40_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_40_11675, 193);
    lv_obj_set_y(face_dial_astronaut2_40_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_40_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_40_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_41_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_41_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_41_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_41_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_41_11675, 186);
    lv_obj_set_y(face_dial_astronaut2_41_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_41_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_41_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_42_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_42_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_42_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_42_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_42_11675, 177);
    lv_obj_set_y(face_dial_astronaut2_42_11675, 205);
    lv_obj_add_flag(face_dial_astronaut2_42_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_42_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_43_15549 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_43_15549, &face_dial_astronaut2_dial_img_43_15549_0);
    lv_obj_set_width(face_dial_astronaut2_43_15549, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_43_15549, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_43_15549, 183);
    lv_obj_set_y(face_dial_astronaut2_43_15549, 208);
    lv_obj_add_flag(face_dial_astronaut2_43_15549, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_43_15549, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_45_13977 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_45_13977, &face_dial_astronaut2_dial_img_45_13977_0);
    lv_obj_set_width(face_dial_astronaut2_45_13977, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_45_13977, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_45_13977, 128);
    lv_obj_set_y(face_dial_astronaut2_45_13977, 262);
    lv_obj_add_flag(face_dial_astronaut2_45_13977, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_45_13977, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_46_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_46_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_46_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_46_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_46_11675, 163);
    lv_obj_set_y(face_dial_astronaut2_46_11675, 262);
    lv_obj_add_flag(face_dial_astronaut2_46_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_46_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_47_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_47_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_47_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_47_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_47_11675, 156);
    lv_obj_set_y(face_dial_astronaut2_47_11675, 262);
    lv_obj_add_flag(face_dial_astronaut2_47_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_47_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_48_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_48_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_48_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_48_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_48_11675, 181);
    lv_obj_set_y(face_dial_astronaut2_48_11675, 262);
    lv_obj_add_flag(face_dial_astronaut2_48_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_48_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_49_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_49_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_49_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_49_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_49_11675, 174);
    lv_obj_set_y(face_dial_astronaut2_49_11675, 262);
    lv_obj_add_flag(face_dial_astronaut2_49_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_49_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_50_4682 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_50_4682, &face_dial_astronaut2_dial_img_50_4682_0);
    lv_obj_set_width(face_dial_astronaut2_50_4682, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_50_4682, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_50_4682, 71);
    lv_obj_set_y(face_dial_astronaut2_50_4682, 222);
    lv_obj_add_flag(face_dial_astronaut2_50_4682, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_50_4682, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_51_4682 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_51_4682, &face_dial_astronaut2_dial_img_50_4682_0);
    lv_obj_set_width(face_dial_astronaut2_51_4682, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_51_4682, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_51_4682, 50);
    lv_obj_set_y(face_dial_astronaut2_51_4682, 222);
    lv_obj_add_flag(face_dial_astronaut2_51_4682, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_51_4682, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_52_4682 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_52_4682, &face_dial_astronaut2_dial_img_50_4682_0);
    lv_obj_set_width(face_dial_astronaut2_52_4682, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_52_4682, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_52_4682, 120);
    lv_obj_set_y(face_dial_astronaut2_52_4682, 222);
    lv_obj_add_flag(face_dial_astronaut2_52_4682, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_52_4682, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_53_4682 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_53_4682, &face_dial_astronaut2_dial_img_50_4682_0);
    lv_obj_set_width(face_dial_astronaut2_53_4682, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_53_4682, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_53_4682, 99);
    lv_obj_set_y(face_dial_astronaut2_53_4682, 222);
    lv_obj_add_flag(face_dial_astronaut2_53_4682, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_53_4682, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_54_4682 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_54_4682, &face_dial_astronaut2_dial_img_50_4682_0);
    lv_obj_set_width(face_dial_astronaut2_54_4682, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_54_4682, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_54_4682, 169);
    lv_obj_set_y(face_dial_astronaut2_54_4682, 222);
    lv_obj_add_flag(face_dial_astronaut2_54_4682, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_54_4682, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_55_4682 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_55_4682, &face_dial_astronaut2_dial_img_50_4682_0);
    lv_obj_set_width(face_dial_astronaut2_55_4682, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_55_4682, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_55_4682, 148);
    lv_obj_set_y(face_dial_astronaut2_55_4682, 222);
    lv_obj_add_flag(face_dial_astronaut2_55_4682, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_55_4682, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_56_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_56_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_56_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_56_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_56_11675, 95);
    lv_obj_set_y(face_dial_astronaut2_56_11675, 263);
    lv_obj_add_flag(face_dial_astronaut2_56_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_56_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_57_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_57_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_57_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_57_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_57_11675, 88);
    lv_obj_set_y(face_dial_astronaut2_57_11675, 263);
    lv_obj_add_flag(face_dial_astronaut2_57_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_57_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_58_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_58_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_58_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_58_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_58_11675, 75);
    lv_obj_set_y(face_dial_astronaut2_58_11675, 263);
    lv_obj_add_flag(face_dial_astronaut2_58_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_58_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_59_11675 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_59_11675, &face_dial_astronaut2_dial_img_14_11675_0);
    lv_obj_set_width(face_dial_astronaut2_59_11675, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_59_11675, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_59_11675, 68);
    lv_obj_set_y(face_dial_astronaut2_59_11675, 263);
    lv_obj_add_flag(face_dial_astronaut2_59_11675, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_59_11675, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_60_11364 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_60_11364, &face_dial_astronaut2_dial_img_60_11364_0);
    lv_obj_set_width(face_dial_astronaut2_60_11364, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_60_11364, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_60_11364, 82);
    lv_obj_set_y(face_dial_astronaut2_60_11364, 263);
    lv_obj_add_flag(face_dial_astronaut2_60_11364, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_60_11364, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_astronaut2_61_11446 = lv_img_create(face_dial_astronaut2);
    lv_img_set_src(face_dial_astronaut2_61_11446, &face_dial_astronaut2_dial_img_61_11446_0);
    lv_obj_set_width(face_dial_astronaut2_61_11446, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_astronaut2_61_11446, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_astronaut2_61_11446, 102);
    lv_obj_set_y(face_dial_astronaut2_61_11446, 264);
    lv_obj_add_flag(face_dial_astronaut2_61_11446, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_astronaut2_61_11446, LV_OBJ_FLAG_SCROLLABLE );


    callback("dial astronaut2", &face_dial_astronaut2_dial_img_preview_0, &face_dial_astronaut2);

#endif
}

void update_time_dial_astronaut2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    if (!face_dial_astronaut2)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut2_45_13977, face_dial_astronaut2_dial_img_45_13977_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_dial_astronaut2_46_11675, face_dial_astronaut2_dial_img_14_11675_group[(month / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_47_11675, face_dial_astronaut2_dial_img_14_11675_group[(month / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_48_11675, face_dial_astronaut2_dial_img_14_11675_group[(day / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_49_11675, face_dial_astronaut2_dial_img_14_11675_group[(day / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_50_4682, face_dial_astronaut2_dial_img_50_4682_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_51_4682, face_dial_astronaut2_dial_img_50_4682_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_52_4682, face_dial_astronaut2_dial_img_50_4682_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_53_4682, face_dial_astronaut2_dial_img_50_4682_group[(minute / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_54_4682, face_dial_astronaut2_dial_img_50_4682_group[(second / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_55_4682, face_dial_astronaut2_dial_img_50_4682_group[(second / 10) % 10]);

#endif
}

void update_weather_dial_astronaut2(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    if (!face_dial_astronaut2)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut2_3_1284, face_dial_astronaut2_dial_img_weather[icon % 8]);

#endif
}

void update_status_dial_astronaut2(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    if (!face_dial_astronaut2)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut2_21_11675, face_dial_astronaut2_dial_img_14_11675_group[(battery / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_22_11675, face_dial_astronaut2_dial_img_14_11675_group[(battery / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_23_11675, face_dial_astronaut2_dial_img_14_11675_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_dial_astronaut2_23_11675, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_astronaut2_23_11675, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_dial_astronaut2(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    if (!face_dial_astronaut2)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut2_27_11675, face_dial_astronaut2_dial_img_14_11675_group[(kcal / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_28_11675, face_dial_astronaut2_dial_img_14_11675_group[(kcal / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_29_11675, face_dial_astronaut2_dial_img_14_11675_group[(kcal / 100) % 10]);
	lv_img_set_src(face_dial_astronaut2_30_11675, face_dial_astronaut2_dial_img_14_11675_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_dial_astronaut2_31_11675, face_dial_astronaut2_dial_img_14_11675_group[(steps / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_32_11675, face_dial_astronaut2_dial_img_14_11675_group[(steps / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_33_11675, face_dial_astronaut2_dial_img_14_11675_group[(steps / 100) % 10]);
	lv_img_set_src(face_dial_astronaut2_34_11675, face_dial_astronaut2_dial_img_14_11675_group[(steps / 1000) % 10]);
	lv_img_set_src(face_dial_astronaut2_35_11675, face_dial_astronaut2_dial_img_14_11675_group[(steps / 10000) % 10]);
	lv_img_set_src(face_dial_astronaut2_40_11675, face_dial_astronaut2_dial_img_14_11675_group[(distance / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_41_11675, face_dial_astronaut2_dial_img_14_11675_group[(distance / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_42_11675, face_dial_astronaut2_dial_img_14_11675_group[(distance / 100) % 10]);

#endif
}

void update_health_dial_astronaut2(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    if (!face_dial_astronaut2)
    {
        return;
    }
	lv_img_set_src(face_dial_astronaut2_24_11675, face_dial_astronaut2_dial_img_14_11675_group[(bpm / 1) % 10]);
	lv_img_set_src(face_dial_astronaut2_25_11675, face_dial_astronaut2_dial_img_14_11675_group[(bpm / 10) % 10]);
	lv_img_set_src(face_dial_astronaut2_26_11675, face_dial_astronaut2_dial_img_14_11675_group[(bpm / 100) % 10]);

#endif
}

void update_all_dial_astronaut2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    update_time_dial_astronaut2(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_astronaut2(temp, icon);
    update_status_dial_astronaut2(battery, connection);
    update_activity_dial_astronaut2(steps, distance, kcal);
    update_health_dial_astronaut2(bpm, oxygen);
#endif
}

void update_check_dial_astronaut2(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_ASTRONAUT2
    if (root != face_dial_astronaut2)
    {
        return;
    }
    update_time_dial_astronaut2(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_astronaut2(temp, icon);
    update_status_dial_astronaut2(battery, connection);
    update_activity_dial_astronaut2(steps, distance, kcal);
    update_health_dial_astronaut2(bpm, oxygen);
#endif
}


