
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_OLDPERSON

#include "dial_oldperson.h"

#ifdef ENABLE_FACE_DIAL_OLDPERSON

lv_obj_t *face_dial_oldperson;
lv_obj_t *face_dial_oldperson_0_536;
lv_obj_t *face_dial_oldperson_1_264;
lv_obj_t *face_dial_oldperson_2_72088;
lv_obj_t *face_dial_oldperson_3_72088;
lv_obj_t *face_dial_oldperson_4_72088;
lv_obj_t *face_dial_oldperson_5_75902;
lv_obj_t *face_dial_oldperson_6_75902;
lv_obj_t *face_dial_oldperson_7_82236;
lv_obj_t *face_dial_oldperson_8_82236;
lv_obj_t *face_dial_oldperson_9_138722;
lv_obj_t *face_dial_oldperson_10_88570;
lv_obj_t *face_dial_oldperson_11_188858;
lv_obj_t *face_dial_oldperson_12_188858;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_oldperson_dial_img_2_72088_group[] = {
	&face_dial_oldperson_dial_img_2_72088_0,
	&face_dial_oldperson_dial_img_2_72088_1,
	&face_dial_oldperson_dial_img_2_72088_2,
	&face_dial_oldperson_dial_img_2_72088_3,
	&face_dial_oldperson_dial_img_2_72088_4,
	&face_dial_oldperson_dial_img_2_72088_5,
	&face_dial_oldperson_dial_img_2_72088_6,
	&face_dial_oldperson_dial_img_2_72088_7,
	&face_dial_oldperson_dial_img_2_72088_8,
	&face_dial_oldperson_dial_img_2_72088_9,
};
const lv_img_dsc_t *face_dial_oldperson_dial_img_5_75902_group[] = {
	&face_dial_oldperson_dial_img_5_75902_0,
	&face_dial_oldperson_dial_img_5_75902_1,
	&face_dial_oldperson_dial_img_5_75902_2,
	&face_dial_oldperson_dial_img_5_75902_3,
	&face_dial_oldperson_dial_img_5_75902_4,
	&face_dial_oldperson_dial_img_5_75902_5,
	&face_dial_oldperson_dial_img_5_75902_6,
	&face_dial_oldperson_dial_img_5_75902_7,
	&face_dial_oldperson_dial_img_5_75902_8,
	&face_dial_oldperson_dial_img_5_75902_9,
};
const lv_img_dsc_t *face_dial_oldperson_dial_img_7_82236_group[] = {
	&face_dial_oldperson_dial_img_7_82236_0,
	&face_dial_oldperson_dial_img_7_82236_1,
	&face_dial_oldperson_dial_img_7_82236_2,
	&face_dial_oldperson_dial_img_7_82236_3,
	&face_dial_oldperson_dial_img_7_82236_4,
	&face_dial_oldperson_dial_img_7_82236_5,
	&face_dial_oldperson_dial_img_7_82236_6,
	&face_dial_oldperson_dial_img_7_82236_7,
	&face_dial_oldperson_dial_img_7_82236_8,
	&face_dial_oldperson_dial_img_7_82236_9,
};
const lv_img_dsc_t *face_dial_oldperson_dial_img_9_138722_group[] = {
	&face_dial_oldperson_dial_img_9_138722_0,
	&face_dial_oldperson_dial_img_9_138722_1,
	&face_dial_oldperson_dial_img_9_138722_2,
	&face_dial_oldperson_dial_img_9_138722_3,
	&face_dial_oldperson_dial_img_9_138722_4,
	&face_dial_oldperson_dial_img_9_138722_5,
	&face_dial_oldperson_dial_img_9_138722_6,
	&face_dial_oldperson_dial_img_9_138722_7,
	&face_dial_oldperson_dial_img_9_138722_8,
	&face_dial_oldperson_dial_img_9_138722_9,
};
const lv_img_dsc_t *face_dial_oldperson_dial_img_10_88570_group[] = {
	&face_dial_oldperson_dial_img_10_88570_0,
	&face_dial_oldperson_dial_img_10_88570_1,
	&face_dial_oldperson_dial_img_10_88570_2,
	&face_dial_oldperson_dial_img_10_88570_3,
	&face_dial_oldperson_dial_img_10_88570_4,
	&face_dial_oldperson_dial_img_10_88570_5,
	&face_dial_oldperson_dial_img_10_88570_6,
	&face_dial_oldperson_dial_img_10_88570_7,
	&face_dial_oldperson_dial_img_10_88570_8,
	&face_dial_oldperson_dial_img_10_88570_9,
};
const lv_img_dsc_t *face_dial_oldperson_dial_img_11_188858_group[] = {
	&face_dial_oldperson_dial_img_11_188858_0,
	&face_dial_oldperson_dial_img_11_188858_1,
	&face_dial_oldperson_dial_img_11_188858_2,
	&face_dial_oldperson_dial_img_11_188858_3,
	&face_dial_oldperson_dial_img_11_188858_4,
	&face_dial_oldperson_dial_img_11_188858_5,
	&face_dial_oldperson_dial_img_11_188858_6,
	&face_dial_oldperson_dial_img_11_188858_7,
	&face_dial_oldperson_dial_img_11_188858_8,
	&face_dial_oldperson_dial_img_11_188858_9,
};


#endif

void init_face_dial_oldperson(void (*callback)(const char *name, const lv_img_dsc_t *preview, lv_obj_t **watchface, int anim_img_num, lv_obj_t *anim_img, const lv_img_dsc_t **anim_img_group)){
#ifdef ENABLE_FACE_DIAL_OLDPERSON
    face_dial_oldperson = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_oldperson, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_oldperson, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_oldperson, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_oldperson, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_oldperson, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_oldperson, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_oldperson, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_oldperson, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_oldperson, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_oldperson_0_536 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_0_536, &face_dial_oldperson_dial_img_0_536_0);
    lv_obj_set_width(face_dial_oldperson_0_536, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_0_536, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_0_536, 0);
    lv_obj_set_y(face_dial_oldperson_0_536, 0);
    lv_obj_add_flag(face_dial_oldperson_0_536, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_0_536, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_1_264 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_1_264, &face_dial_oldperson_dial_img_1_264_0);
    lv_obj_set_width(face_dial_oldperson_1_264, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_1_264, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_1_264, 215);
    lv_obj_set_y(face_dial_oldperson_1_264, 35);
    lv_obj_add_flag(face_dial_oldperson_1_264, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_1_264, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_2_72088 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_2_72088, &face_dial_oldperson_dial_img_2_72088_0);
    lv_obj_set_width(face_dial_oldperson_2_72088, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_2_72088, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_2_72088, 200);
    lv_obj_set_y(face_dial_oldperson_2_72088, 27);
    lv_obj_add_flag(face_dial_oldperson_2_72088, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_2_72088, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_3_72088 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_3_72088, &face_dial_oldperson_dial_img_2_72088_0);
    lv_obj_set_width(face_dial_oldperson_3_72088, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_3_72088, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_3_72088, 185);
    lv_obj_set_y(face_dial_oldperson_3_72088, 27);
    lv_obj_add_flag(face_dial_oldperson_3_72088, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_3_72088, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_4_72088 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_4_72088, &face_dial_oldperson_dial_img_2_72088_0);
    lv_obj_set_width(face_dial_oldperson_4_72088, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_4_72088, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_4_72088, 171);
    lv_obj_set_y(face_dial_oldperson_4_72088, 27);
    lv_obj_add_flag(face_dial_oldperson_4_72088, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_4_72088, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_5_75902 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_5_75902, &face_dial_oldperson_dial_img_5_75902_0);
    lv_obj_set_width(face_dial_oldperson_5_75902, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_5_75902, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_5_75902, 165);
    lv_obj_set_y(face_dial_oldperson_5_75902, 246);
    lv_obj_add_flag(face_dial_oldperson_5_75902, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_5_75902, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_6_75902 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_6_75902, &face_dial_oldperson_dial_img_5_75902_0);
    lv_obj_set_width(face_dial_oldperson_6_75902, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_6_75902, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_6_75902, 144);
    lv_obj_set_y(face_dial_oldperson_6_75902, 246);
    lv_obj_add_flag(face_dial_oldperson_6_75902, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_6_75902, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_7_82236 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_7_82236, &face_dial_oldperson_dial_img_7_82236_0);
    lv_obj_set_width(face_dial_oldperson_7_82236, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_7_82236, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_7_82236, 214);
    lv_obj_set_y(face_dial_oldperson_7_82236, 245);
    lv_obj_add_flag(face_dial_oldperson_7_82236, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_7_82236, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_8_82236 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_8_82236, &face_dial_oldperson_dial_img_7_82236_0);
    lv_obj_set_width(face_dial_oldperson_8_82236, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_8_82236, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_8_82236, 193);
    lv_obj_set_y(face_dial_oldperson_8_82236, 245);
    lv_obj_add_flag(face_dial_oldperson_8_82236, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_8_82236, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_9_138722 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_9_138722, &face_dial_oldperson_dial_img_9_138722_0);
    lv_obj_set_width(face_dial_oldperson_9_138722, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_9_138722, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_9_138722, 67);
    lv_obj_set_y(face_dial_oldperson_9_138722, 73);
    lv_obj_add_flag(face_dial_oldperson_9_138722, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_9_138722, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_10_88570 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_10_88570, &face_dial_oldperson_dial_img_10_88570_0);
    lv_obj_set_width(face_dial_oldperson_10_88570, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_10_88570, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_10_88570, 8);
    lv_obj_set_y(face_dial_oldperson_10_88570, 73);
    lv_obj_add_flag(face_dial_oldperson_10_88570, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_10_88570, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_11_188858 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_11_188858, &face_dial_oldperson_dial_img_11_188858_0);
    lv_obj_set_width(face_dial_oldperson_11_188858, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_11_188858, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_11_188858, 67);
    lv_obj_set_y(face_dial_oldperson_11_188858, 184);
    lv_obj_add_flag(face_dial_oldperson_11_188858, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_11_188858, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_oldperson_12_188858 = lv_img_create(face_dial_oldperson);
    lv_img_set_src(face_dial_oldperson_12_188858, &face_dial_oldperson_dial_img_11_188858_0);
    lv_obj_set_width(face_dial_oldperson_12_188858, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_oldperson_12_188858, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_oldperson_12_188858, 8);
    lv_obj_set_y(face_dial_oldperson_12_188858, 184);
    lv_obj_add_flag(face_dial_oldperson_12_188858, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_oldperson_12_188858, LV_OBJ_FLAG_SCROLLABLE );


    callback("dial oldperson", &face_dial_oldperson_dial_img_preview_0, &face_dial_oldperson, 0, NULL, NULL);

#endif
}

void update_time_dial_oldperson(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_OLDPERSON
    if (!face_dial_oldperson)
    {
        return;
    }
	lv_img_set_src(face_dial_oldperson_5_75902, face_dial_oldperson_dial_img_5_75902_group[(day / 1) % 10]);
	lv_img_set_src(face_dial_oldperson_6_75902, face_dial_oldperson_dial_img_5_75902_group[(day / 10) % 10]);
	lv_img_set_src(face_dial_oldperson_7_82236, face_dial_oldperson_dial_img_7_82236_group[(month / 1) % 10]);
	lv_img_set_src(face_dial_oldperson_8_82236, face_dial_oldperson_dial_img_7_82236_group[(month / 10) % 10]);
	lv_img_set_src(face_dial_oldperson_9_138722, face_dial_oldperson_dial_img_9_138722_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_oldperson_10_88570, face_dial_oldperson_dial_img_10_88570_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_oldperson_11_188858, face_dial_oldperson_dial_img_11_188858_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_oldperson_12_188858, face_dial_oldperson_dial_img_11_188858_group[(minute / 10) % 10]);

#endif
}

void update_weather_dial_oldperson(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_OLDPERSON
    if (!face_dial_oldperson)
    {
        return;
    }

#endif
}

void update_status_dial_oldperson(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_OLDPERSON
    if (!face_dial_oldperson)
    {
        return;
    }
	lv_img_set_src(face_dial_oldperson_2_72088, face_dial_oldperson_dial_img_2_72088_group[(battery / 1) % 10]);
	lv_img_set_src(face_dial_oldperson_3_72088, face_dial_oldperson_dial_img_2_72088_group[(battery / 10) % 10]);
	lv_img_set_src(face_dial_oldperson_4_72088, face_dial_oldperson_dial_img_2_72088_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_dial_oldperson_4_72088, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_oldperson_4_72088, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_dial_oldperson(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_OLDPERSON
    if (!face_dial_oldperson)
    {
        return;
    }

#endif
}

void update_health_dial_oldperson(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_OLDPERSON
    if (!face_dial_oldperson)
    {
        return;
    }

#endif
}

void update_all_dial_oldperson(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_OLDPERSON
    update_time_dial_oldperson(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_oldperson(temp, icon);
    update_status_dial_oldperson(battery, connection);
    update_activity_dial_oldperson(steps, distance, kcal);
    update_health_dial_oldperson(bpm, oxygen);
#endif
}

void update_check_dial_oldperson(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_OLDPERSON
    if (root != face_dial_oldperson)
    {
        return;
    }
    update_time_dial_oldperson(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_oldperson(temp, icon);
    update_status_dial_oldperson(battery, connection);
    update_activity_dial_oldperson(steps, distance, kcal);
    update_health_dial_oldperson(bpm, oxygen);
#endif
}


