
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_OLDPERSON

#ifndef _FACE_DIAL_OLDPERSON_H
#define _FACE_DIAL_OLDPERSON_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

// #define ENABLE_FACE_DIAL_OLDPERSON // (dial oldperson) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_DIAL_OLDPERSON
    extern lv_obj_t *face_dial_oldperson;
	extern lv_obj_t *face_dial_oldperson_0_536;
	extern lv_obj_t *face_dial_oldperson_1_264;
	extern lv_obj_t *face_dial_oldperson_2_72088;
	extern lv_obj_t *face_dial_oldperson_3_72088;
	extern lv_obj_t *face_dial_oldperson_4_72088;
	extern lv_obj_t *face_dial_oldperson_5_75902;
	extern lv_obj_t *face_dial_oldperson_6_75902;
	extern lv_obj_t *face_dial_oldperson_7_82236;
	extern lv_obj_t *face_dial_oldperson_8_82236;
	extern lv_obj_t *face_dial_oldperson_9_138722;
	extern lv_obj_t *face_dial_oldperson_10_88570;
	extern lv_obj_t *face_dial_oldperson_11_188858;
	extern lv_obj_t *face_dial_oldperson_12_188858;


	LV_IMG_DECLARE(face_dial_oldperson_dial_img_0_536_0);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_1_264_0);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_0);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_1);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_2);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_3);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_4);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_5);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_6);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_7);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_8);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_2_72088_9);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_0);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_1);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_2);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_3);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_4);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_5);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_6);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_7);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_8);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_5_75902_9);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_0);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_1);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_2);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_3);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_4);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_5);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_6);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_7);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_8);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_7_82236_9);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_0);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_1);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_2);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_3);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_4);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_5);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_6);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_7);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_8);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_9_138722_9);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_0);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_1);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_2);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_3);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_4);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_5);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_6);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_7);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_8);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_10_88570_9);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_0);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_1);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_2);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_3);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_4);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_5);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_6);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_7);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_8);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_11_188858_9);
	LV_IMG_DECLARE(face_dial_oldperson_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_dial_oldperson(void (*callback)(const char *name, const lv_img_dsc_t *preview, lv_obj_t **watchface, int anim_img_num, lv_obj_t *anim_img, const lv_img_dsc_t **anim_img_group));
    void update_time_dial_oldperson(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_dial_oldperson(int temp, int icon);
    void update_status_dial_oldperson(int battery, bool connection);
    void update_activity_dial_oldperson(int steps, int distance, int kcal);
    void update_health_dial_oldperson(int bpm, int oxygen);
    void update_all_dial_oldperson(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_dial_oldperson(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
