
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ANALOG_STARCRAFT2

#ifndef _FACE_ANALOG_STARCRAFT2_H
#define _FACE_ANALOG_STARCRAFT2_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#define ENABLE_FACE_ANALOG_STARCRAFT2 // (analog starcraft2) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    extern lv_obj_t *face_analog_starcraft2;
	extern lv_obj_t *face_analog_starcraft2_0_1164;
	extern lv_obj_t *face_analog_starcraft2_6_226580;
	extern lv_obj_t *face_analog_starcraft2_7_226580;
	extern lv_obj_t *face_analog_starcraft2_9_347008;
	extern lv_obj_t *face_analog_starcraft2_10_70776;
	extern lv_obj_t *face_analog_starcraft2_26_135458;
	extern lv_obj_t *face_analog_starcraft2_42_229134;


	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_0_1164_0);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_0);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_1);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_2);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_3);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_4);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_5);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_6);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_7);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_8);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_6_226580_9);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_8_340653_0);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_8_340653_1);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_8_340653_2);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_8_340653_3);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_8_340653_4);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_8_340653_5);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_8_340653_6);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_9_347008_0);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_9_347008_1);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_9_347008_2);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_9_347008_3);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_9_347008_4);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_9_347008_5);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_9_347008_6);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_10_70776_0);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_26_135458_0);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_42_229134_0);
	LV_IMG_DECLARE(face_analog_starcraft2_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_analog_starcraft2(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **));
    void update_time_analog_starcraft2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_analog_starcraft2(int temp, int icon);
    void update_status_analog_starcraft2(int battery, bool connection);
    void update_activity_analog_starcraft2(int steps, int distance, int kcal);
    void update_health_analog_starcraft2(int bpm, int oxygen);
    void update_all_analog_starcraft2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_analog_starcraft2(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
