
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ANALOG_STARCRAFT2

#include "analog_starcraft2.h"

#ifdef ENABLE_FACE_ANALOG_STARCRAFT2

lv_obj_t *face_analog_starcraft2;
lv_obj_t *face_analog_starcraft2_0_1164;
lv_obj_t *face_analog_starcraft2_6_226580;
lv_obj_t *face_analog_starcraft2_7_226580;
lv_obj_t *face_analog_starcraft2_9_347008;
lv_obj_t *face_analog_starcraft2_10_70776;
lv_obj_t *face_analog_starcraft2_26_135458;
lv_obj_t *face_analog_starcraft2_42_229134;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_analog_starcraft2_dial_img_6_226580_group[] = {
	&face_analog_starcraft2_dial_img_6_226580_0,
	&face_analog_starcraft2_dial_img_6_226580_1,
	&face_analog_starcraft2_dial_img_6_226580_2,
	&face_analog_starcraft2_dial_img_6_226580_3,
	&face_analog_starcraft2_dial_img_6_226580_4,
	&face_analog_starcraft2_dial_img_6_226580_5,
	&face_analog_starcraft2_dial_img_6_226580_6,
	&face_analog_starcraft2_dial_img_6_226580_7,
	&face_analog_starcraft2_dial_img_6_226580_8,
	&face_analog_starcraft2_dial_img_6_226580_9,
};
const lv_img_dsc_t *face_analog_starcraft2_dial_img_8_340653_group[] = {
	&face_analog_starcraft2_dial_img_8_340653_0,
	&face_analog_starcraft2_dial_img_8_340653_1,
	&face_analog_starcraft2_dial_img_8_340653_2,
	&face_analog_starcraft2_dial_img_8_340653_3,
	&face_analog_starcraft2_dial_img_8_340653_4,
	&face_analog_starcraft2_dial_img_8_340653_5,
	&face_analog_starcraft2_dial_img_8_340653_6,
};
const lv_img_dsc_t *face_analog_starcraft2_dial_img_9_347008_group[] = {
	&face_analog_starcraft2_dial_img_9_347008_0,
	&face_analog_starcraft2_dial_img_9_347008_1,
	&face_analog_starcraft2_dial_img_9_347008_2,
	&face_analog_starcraft2_dial_img_9_347008_3,
	&face_analog_starcraft2_dial_img_9_347008_4,
	&face_analog_starcraft2_dial_img_9_347008_5,
	&face_analog_starcraft2_dial_img_9_347008_6,
};


#endif

void init_face_analog_starcraft2(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    face_analog_starcraft2 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_analog_starcraft2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_analog_starcraft2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_analog_starcraft2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_analog_starcraft2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_analog_starcraft2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_analog_starcraft2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_analog_starcraft2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_analog_starcraft2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_analog_starcraft2, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_analog_starcraft2_0_1164 = lv_img_create(face_analog_starcraft2);
    lv_img_set_src(face_analog_starcraft2_0_1164, &face_analog_starcraft2_dial_img_0_1164_0);
    lv_obj_set_width(face_analog_starcraft2_0_1164, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_starcraft2_0_1164, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_starcraft2_0_1164, 0);
    lv_obj_set_y(face_analog_starcraft2_0_1164, 0);
    lv_obj_add_flag(face_analog_starcraft2_0_1164, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_starcraft2_0_1164, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_starcraft2_6_226580 = lv_img_create(face_analog_starcraft2);
    lv_img_set_src(face_analog_starcraft2_6_226580, &face_analog_starcraft2_dial_img_6_226580_0);
    lv_obj_set_width(face_analog_starcraft2_6_226580, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_starcraft2_6_226580, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_starcraft2_6_226580, 146);
    lv_obj_set_y(face_analog_starcraft2_6_226580, 173);
    lv_obj_add_flag(face_analog_starcraft2_6_226580, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_starcraft2_6_226580, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_starcraft2_7_226580 = lv_img_create(face_analog_starcraft2);
    lv_img_set_src(face_analog_starcraft2_7_226580, &face_analog_starcraft2_dial_img_6_226580_0);
    lv_obj_set_width(face_analog_starcraft2_7_226580, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_starcraft2_7_226580, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_starcraft2_7_226580, 132);
    lv_obj_set_y(face_analog_starcraft2_7_226580, 173);
    lv_obj_add_flag(face_analog_starcraft2_7_226580, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_starcraft2_7_226580, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_starcraft2_9_347008 = lv_img_create(face_analog_starcraft2);
    lv_img_set_src(face_analog_starcraft2_9_347008, &face_analog_starcraft2_dial_img_9_347008_0);
    lv_obj_set_width(face_analog_starcraft2_9_347008, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_starcraft2_9_347008, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_starcraft2_9_347008, 81);
    lv_obj_set_y(face_analog_starcraft2_9_347008, 175);
    lv_obj_add_flag(face_analog_starcraft2_9_347008, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_starcraft2_9_347008, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_starcraft2_10_70776 = lv_img_create(face_analog_starcraft2);
    lv_img_set_src(face_analog_starcraft2_10_70776, &face_analog_starcraft2_dial_img_10_70776_0);
    lv_obj_set_width(face_analog_starcraft2_10_70776, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_starcraft2_10_70776, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_starcraft2_10_70776, 113);
    lv_obj_set_y(face_analog_starcraft2_10_70776, 55);
    lv_obj_add_flag(face_analog_starcraft2_10_70776, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_starcraft2_10_70776, LV_OBJ_FLAG_SCROLLABLE );
	lv_img_set_pivot(face_analog_starcraft2_10_70776, 7, 89);

    face_analog_starcraft2_26_135458 = lv_img_create(face_analog_starcraft2);
    lv_img_set_src(face_analog_starcraft2_26_135458, &face_analog_starcraft2_dial_img_26_135458_0);
    lv_obj_set_width(face_analog_starcraft2_26_135458, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_starcraft2_26_135458, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_starcraft2_26_135458, 113);
    lv_obj_set_y(face_analog_starcraft2_26_135458, 31);
    lv_obj_add_flag(face_analog_starcraft2_26_135458, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_starcraft2_26_135458, LV_OBJ_FLAG_SCROLLABLE );
	lv_img_set_pivot(face_analog_starcraft2_26_135458, 7, 113);

    face_analog_starcraft2_42_229134 = lv_img_create(face_analog_starcraft2);
    lv_img_set_src(face_analog_starcraft2_42_229134, &face_analog_starcraft2_dial_img_42_229134_0);
    lv_obj_set_width(face_analog_starcraft2_42_229134, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_starcraft2_42_229134, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_starcraft2_42_229134, 107);
    lv_obj_set_y(face_analog_starcraft2_42_229134, 23);
    lv_obj_add_flag(face_analog_starcraft2_42_229134, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_starcraft2_42_229134, LV_OBJ_FLAG_SCROLLABLE );
	lv_img_set_pivot(face_analog_starcraft2_42_229134, 13, 121);


    callback("analog starcraft2", &face_analog_starcraft2_dial_img_preview_0, &face_analog_starcraft2);

#endif
}

void update_time_analog_starcraft2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    if (!face_analog_starcraft2)
    {
        return;
    }
	lv_img_set_src(face_analog_starcraft2_6_226580, face_analog_starcraft2_dial_img_6_226580_group[(day / 1) % 10]);
	lv_img_set_src(face_analog_starcraft2_7_226580, face_analog_starcraft2_dial_img_6_226580_group[(day / 10) % 10]);
	lv_img_set_src(face_analog_starcraft2_9_347008, face_analog_starcraft2_dial_img_9_347008_group[((weekday + 6) / 1) % 7]);
	lv_img_set_angle(face_analog_starcraft2_10_70776, hour * 300 + (minute * 5));
	lv_img_set_angle(face_analog_starcraft2_26_135458, minute * 60);
	lv_img_set_angle(face_analog_starcraft2_42_229134, second * 60);

#endif
}

void update_weather_analog_starcraft2(int temp, int icon)
{
#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    if (!face_analog_starcraft2)
    {
        return;
    }

#endif
}

void update_status_analog_starcraft2(int battery, bool connection){
#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    if (!face_analog_starcraft2)
    {
        return;
    }

#endif
}

void update_activity_analog_starcraft2(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    if (!face_analog_starcraft2)
    {
        return;
    }

#endif
}

void update_health_analog_starcraft2(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    if (!face_analog_starcraft2)
    {
        return;
    }

#endif
}

void update_all_analog_starcraft2(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    update_time_analog_starcraft2(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_analog_starcraft2(temp, icon);
    update_status_analog_starcraft2(battery, connection);
    update_activity_analog_starcraft2(steps, distance, kcal);
    update_health_analog_starcraft2(bpm, oxygen);
#endif
}

void update_check_analog_starcraft2(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_STARCRAFT2
    if (root != face_analog_starcraft2)
    {
        return;
    }
    update_time_analog_starcraft2(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_analog_starcraft2(temp, icon);
    update_status_analog_starcraft2(battery, connection);
    update_activity_analog_starcraft2(steps, distance, kcal);
    update_health_analog_starcraft2(bpm, oxygen);
#endif
}


