
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_BLACKBOARD

#include "../dial_blackboard.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_dial_blackboard_dial_img_45_133743_data_0[] = {
	0x41,0x62,0xFF,0x41,0x62,0xFF,0x41,0x62,0xFF,
    };
        


const lv_img_dsc_t face_dial_blackboard_dial_img_45_133743_0 = {
    .header.always_zero = 0,
    .header.w = 3,
    .header.h = 1,
    .data_size = sizeof(face_dial_blackboard_dial_img_45_133743_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_dial_blackboard_dial_img_45_133743_data_0};

    