
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_BLACKBOARD

#include "../dial_blackboard.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_dial_blackboard_dial_img_38_19117_data_0[] = {
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x1F,0x14,0xFF,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x03,0x00,0xFF,0x00,0x00,0x00,
    };
        


const lv_img_dsc_t face_dial_blackboard_dial_img_38_19117_0 = {
    .header.always_zero = 0,
    .header.w = 7,
    .header.h = 2,
    .data_size = sizeof(face_dial_blackboard_dial_img_38_19117_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_dial_blackboard_dial_img_38_19117_data_0};

    