
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ANALOG_NIKE

#ifndef _FACE_ANALOG_NIKE_H
#define _FACE_ANALOG_NIKE_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

// #define ENABLE_FACE_ANALOG_NIKE // (analog nike) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_ANALOG_NIKE
    extern lv_obj_t *face_analog_nike;
	extern lv_obj_t *face_analog_nike_0_154255;
	extern lv_obj_t *face_analog_nike_3_128886;
	extern lv_obj_t *face_analog_nike_4_130643;
	extern lv_obj_t *face_analog_nike_5_130643;
	extern lv_obj_t *face_analog_nike_6_130643;
	extern lv_obj_t *face_analog_nike_7_130643;
	extern lv_obj_t *face_analog_nike_8_136825;
	extern lv_obj_t *face_analog_nike_9_136825;
	extern lv_obj_t *face_analog_nike_10_136825;
	extern lv_obj_t *face_analog_nike_11_136825;
	extern lv_obj_t *face_analog_nike_16_130643;
	extern lv_obj_t *face_analog_nike_17_130643;
	extern lv_obj_t *face_analog_nike_18_130643;
	extern lv_obj_t *face_analog_nike_19_154109;
	extern lv_obj_t *face_analog_nike_35_130643;
	extern lv_obj_t *face_analog_nike_36_130643;
	extern lv_obj_t *face_analog_nike_37_130643;
	extern lv_obj_t *face_analog_nike_38_130643;
	extern lv_obj_t *face_analog_nike_39_130643;
	extern lv_obj_t *face_analog_nike_40_130643;
	extern lv_obj_t *face_analog_nike_41_130643;
	extern lv_obj_t *face_analog_nike_42_130643;
	extern lv_obj_t *face_analog_nike_43_130643;
	extern lv_obj_t *face_analog_nike_44_130643;
	extern lv_obj_t *face_analog_nike_45_130643;
	extern lv_obj_t *face_analog_nike_46_130643;
	extern lv_obj_t *face_analog_nike_48_73266;
	extern lv_obj_t *face_analog_nike_57_46486;
	extern lv_obj_t *face_analog_nike_58_46486;
	extern lv_obj_t *face_analog_nike_59_130643;
	extern lv_obj_t *face_analog_nike_60_130643;
	extern lv_obj_t *face_analog_nike_61_130643;
	extern lv_obj_t *face_analog_nike_62_135751;
	extern lv_obj_t *face_analog_nike_63_128895;
	extern lv_obj_t *face_analog_nike_64_46486;


	LV_IMG_DECLARE(face_analog_nike_dial_img_0_154255_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_1_75220_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_1_75220_1);
	LV_IMG_DECLARE(face_analog_nike_dial_img_1_75220_2);
	LV_IMG_DECLARE(face_analog_nike_dial_img_1_75220_3);
	LV_IMG_DECLARE(face_analog_nike_dial_img_1_75220_4);
	LV_IMG_DECLARE(face_analog_nike_dial_img_1_75220_5);
	LV_IMG_DECLARE(face_analog_nike_dial_img_1_75220_6);
	LV_IMG_DECLARE(face_analog_nike_dial_img_3_128886_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_1);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_2);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_3);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_4);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_5);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_6);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_7);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_8);
	LV_IMG_DECLARE(face_analog_nike_dial_img_4_130643_9);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_1);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_2);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_3);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_4);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_5);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_6);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_7);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_8);
	LV_IMG_DECLARE(face_analog_nike_dial_img_8_136825_9);
	LV_IMG_DECLARE(face_analog_nike_dial_img_19_154109_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_48_73266_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_49_135891_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_50_134745_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_51_132583_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_52_131377_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_53_133693_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_54_153059_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_55_127790_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_56_129607_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_57_46486_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_62_135751_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_63_128895_0);
	LV_IMG_DECLARE(face_analog_nike_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_analog_nike(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **));
    void update_time_analog_nike(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_analog_nike(int temp, int icon);
    void update_status_analog_nike(int battery, bool connection);
    void update_activity_analog_nike(int steps, int distance, int kcal);
    void update_health_analog_nike(int bpm, int oxygen);
    void update_all_analog_nike(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_analog_nike(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
