
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ANALOG_NIKE

#include "analog_nike.h"

#ifdef ENABLE_FACE_ANALOG_NIKE

lv_obj_t *face_analog_nike;
lv_obj_t *face_analog_nike_0_154255;
lv_obj_t *face_analog_nike_3_128886;
lv_obj_t *face_analog_nike_4_130643;
lv_obj_t *face_analog_nike_5_130643;
lv_obj_t *face_analog_nike_6_130643;
lv_obj_t *face_analog_nike_7_130643;
lv_obj_t *face_analog_nike_8_136825;
lv_obj_t *face_analog_nike_9_136825;
lv_obj_t *face_analog_nike_10_136825;
lv_obj_t *face_analog_nike_11_136825;
lv_obj_t *face_analog_nike_16_130643;
lv_obj_t *face_analog_nike_17_130643;
lv_obj_t *face_analog_nike_18_130643;
lv_obj_t *face_analog_nike_19_154109;
lv_obj_t *face_analog_nike_35_130643;
lv_obj_t *face_analog_nike_36_130643;
lv_obj_t *face_analog_nike_37_130643;
lv_obj_t *face_analog_nike_38_130643;
lv_obj_t *face_analog_nike_39_130643;
lv_obj_t *face_analog_nike_40_130643;
lv_obj_t *face_analog_nike_41_130643;
lv_obj_t *face_analog_nike_42_130643;
lv_obj_t *face_analog_nike_43_130643;
lv_obj_t *face_analog_nike_44_130643;
lv_obj_t *face_analog_nike_45_130643;
lv_obj_t *face_analog_nike_46_130643;
lv_obj_t *face_analog_nike_48_73266;
lv_obj_t *face_analog_nike_57_46486;
lv_obj_t *face_analog_nike_58_46486;
lv_obj_t *face_analog_nike_59_130643;
lv_obj_t *face_analog_nike_60_130643;
lv_obj_t *face_analog_nike_61_130643;
lv_obj_t *face_analog_nike_62_135751;
lv_obj_t *face_analog_nike_63_128895;
lv_obj_t *face_analog_nike_64_46486;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_analog_nike_dial_img_1_75220_group[] = {
	&face_analog_nike_dial_img_1_75220_0,
	&face_analog_nike_dial_img_1_75220_1,
	&face_analog_nike_dial_img_1_75220_2,
	&face_analog_nike_dial_img_1_75220_3,
	&face_analog_nike_dial_img_1_75220_4,
	&face_analog_nike_dial_img_1_75220_5,
	&face_analog_nike_dial_img_1_75220_6,
};
const lv_img_dsc_t *face_analog_nike_dial_img_4_130643_group[] = {
	&face_analog_nike_dial_img_4_130643_0,
	&face_analog_nike_dial_img_4_130643_1,
	&face_analog_nike_dial_img_4_130643_2,
	&face_analog_nike_dial_img_4_130643_3,
	&face_analog_nike_dial_img_4_130643_4,
	&face_analog_nike_dial_img_4_130643_5,
	&face_analog_nike_dial_img_4_130643_6,
	&face_analog_nike_dial_img_4_130643_7,
	&face_analog_nike_dial_img_4_130643_8,
	&face_analog_nike_dial_img_4_130643_9,
};
const lv_img_dsc_t *face_analog_nike_dial_img_8_136825_group[] = {
	&face_analog_nike_dial_img_8_136825_0,
	&face_analog_nike_dial_img_8_136825_1,
	&face_analog_nike_dial_img_8_136825_2,
	&face_analog_nike_dial_img_8_136825_3,
	&face_analog_nike_dial_img_8_136825_4,
	&face_analog_nike_dial_img_8_136825_5,
	&face_analog_nike_dial_img_8_136825_6,
	&face_analog_nike_dial_img_8_136825_7,
	&face_analog_nike_dial_img_8_136825_8,
	&face_analog_nike_dial_img_8_136825_9,
};
const lv_img_dsc_t *face_analog_nike_dial_img_weather[] = {
	&face_analog_nike_dial_img_48_73266_0,
	&face_analog_nike_dial_img_49_135891_0,
	&face_analog_nike_dial_img_50_134745_0,
	&face_analog_nike_dial_img_51_132583_0,
	&face_analog_nike_dial_img_52_131377_0,
	&face_analog_nike_dial_img_53_133693_0,
	&face_analog_nike_dial_img_54_153059_0,
	&face_analog_nike_dial_img_55_127790_0,
	&face_analog_nike_dial_img_56_129607_0,
};


#endif

void init_face_analog_nike(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_ANALOG_NIKE
    face_analog_nike = lv_obj_create(NULL);
    lv_obj_clear_flag(face_analog_nike, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_analog_nike, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_analog_nike, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_analog_nike, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_analog_nike, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_analog_nike, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_analog_nike, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_analog_nike, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_analog_nike, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_analog_nike_0_154255 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_0_154255, &face_analog_nike_dial_img_0_154255_0);
    lv_obj_set_width(face_analog_nike_0_154255, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_0_154255, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_0_154255, 0);
    lv_obj_set_y(face_analog_nike_0_154255, 0);
    lv_obj_add_flag(face_analog_nike_0_154255, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_0_154255, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_3_128886 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_3_128886, &face_analog_nike_dial_img_3_128886_0);
    lv_obj_set_width(face_analog_nike_3_128886, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_3_128886, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_3_128886, 185);
    lv_obj_set_y(face_analog_nike_3_128886, 29);
    lv_obj_add_flag(face_analog_nike_3_128886, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_3_128886, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_4_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_4_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_4_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_4_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_4_130643, 202);
    lv_obj_set_y(face_analog_nike_4_130643, 24);
    lv_obj_add_flag(face_analog_nike_4_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_4_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_5_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_5_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_5_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_5_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_5_130643, 194);
    lv_obj_set_y(face_analog_nike_5_130643, 24);
    lv_obj_add_flag(face_analog_nike_5_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_5_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_6_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_6_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_6_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_6_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_6_130643, 174);
    lv_obj_set_y(face_analog_nike_6_130643, 24);
    lv_obj_add_flag(face_analog_nike_6_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_6_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_7_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_7_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_7_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_7_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_7_130643, 166);
    lv_obj_set_y(face_analog_nike_7_130643, 24);
    lv_obj_add_flag(face_analog_nike_7_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_7_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_8_136825 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_8_136825, &face_analog_nike_dial_img_8_136825_0);
    lv_obj_set_width(face_analog_nike_8_136825, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_8_136825, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_8_136825, 75);
    lv_obj_set_y(face_analog_nike_8_136825, 116);
    lv_obj_add_flag(face_analog_nike_8_136825, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_8_136825, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_9_136825 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_9_136825, &face_analog_nike_dial_img_8_136825_0);
    lv_obj_set_width(face_analog_nike_9_136825, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_9_136825, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_9_136825, 35);
    lv_obj_set_y(face_analog_nike_9_136825, 116);
    lv_obj_add_flag(face_analog_nike_9_136825, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_9_136825, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_10_136825 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_10_136825, &face_analog_nike_dial_img_8_136825_0);
    lv_obj_set_width(face_analog_nike_10_136825, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_10_136825, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_10_136825, 169);
    lv_obj_set_y(face_analog_nike_10_136825, 116);
    lv_obj_add_flag(face_analog_nike_10_136825, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_10_136825, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_11_136825 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_11_136825, &face_analog_nike_dial_img_8_136825_0);
    lv_obj_set_width(face_analog_nike_11_136825, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_11_136825, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_11_136825, 131);
    lv_obj_set_y(face_analog_nike_11_136825, 116);
    lv_obj_add_flag(face_analog_nike_11_136825, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_11_136825, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_16_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_16_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_16_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_16_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_16_130643, 195);
    lv_obj_set_y(face_analog_nike_16_130643, 252);
    lv_obj_add_flag(face_analog_nike_16_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_16_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_17_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_17_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_17_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_17_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_17_130643, 187);
    lv_obj_set_y(face_analog_nike_17_130643, 252);
    lv_obj_add_flag(face_analog_nike_17_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_17_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_18_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_18_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_18_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_18_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_18_130643, 179);
    lv_obj_set_y(face_analog_nike_18_130643, 252);
    lv_obj_add_flag(face_analog_nike_18_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_18_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_19_154109 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_19_154109, &face_analog_nike_dial_img_19_154109_0);
    lv_obj_set_width(face_analog_nike_19_154109, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_19_154109, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_19_154109, 203);
    lv_obj_set_y(face_analog_nike_19_154109, 253);
    lv_obj_add_flag(face_analog_nike_19_154109, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_19_154109, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_35_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_35_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_35_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_35_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_35_130643, 89);
    lv_obj_set_y(face_analog_nike_35_130643, 178);
    lv_obj_add_flag(face_analog_nike_35_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_35_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_36_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_36_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_36_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_36_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_36_130643, 81);
    lv_obj_set_y(face_analog_nike_36_130643, 178);
    lv_obj_add_flag(face_analog_nike_36_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_36_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_37_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_37_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_37_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_37_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_37_130643, 73);
    lv_obj_set_y(face_analog_nike_37_130643, 178);
    lv_obj_add_flag(face_analog_nike_37_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_37_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_38_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_38_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_38_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_38_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_38_130643, 164);
    lv_obj_set_y(face_analog_nike_38_130643, 178);
    lv_obj_add_flag(face_analog_nike_38_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_38_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_39_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_39_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_39_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_39_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_39_130643, 156);
    lv_obj_set_y(face_analog_nike_39_130643, 178);
    lv_obj_add_flag(face_analog_nike_39_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_39_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_40_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_40_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_40_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_40_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_40_130643, 148);
    lv_obj_set_y(face_analog_nike_40_130643, 178);
    lv_obj_add_flag(face_analog_nike_40_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_40_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_41_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_41_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_41_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_41_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_41_130643, 140);
    lv_obj_set_y(face_analog_nike_41_130643, 178);
    lv_obj_add_flag(face_analog_nike_41_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_41_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_42_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_42_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_42_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_42_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_42_130643, 55);
    lv_obj_set_y(face_analog_nike_42_130643, 253);
    lv_obj_add_flag(face_analog_nike_42_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_42_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_43_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_43_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_43_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_43_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_43_130643, 47);
    lv_obj_set_y(face_analog_nike_43_130643, 253);
    lv_obj_add_flag(face_analog_nike_43_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_43_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_44_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_44_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_44_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_44_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_44_130643, 39);
    lv_obj_set_y(face_analog_nike_44_130643, 253);
    lv_obj_add_flag(face_analog_nike_44_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_44_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_45_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_45_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_45_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_45_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_45_130643, 31);
    lv_obj_set_y(face_analog_nike_45_130643, 253);
    lv_obj_add_flag(face_analog_nike_45_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_45_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_46_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_46_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_46_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_46_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_46_130643, 23);
    lv_obj_set_y(face_analog_nike_46_130643, 253);
    lv_obj_add_flag(face_analog_nike_46_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_46_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_48_73266 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_48_73266, &face_analog_nike_dial_img_48_73266_0);
    lv_obj_set_width(face_analog_nike_48_73266, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_48_73266, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_48_73266, 16);
    lv_obj_set_y(face_analog_nike_48_73266, 13);
    lv_obj_add_flag(face_analog_nike_48_73266, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_48_73266, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_57_46486 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_57_46486, &face_analog_nike_dial_img_57_46486_0);
    lv_obj_set_width(face_analog_nike_57_46486, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_57_46486, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_57_46486, 66);
    lv_obj_set_y(face_analog_nike_57_46486, 28);
    lv_obj_add_flag(face_analog_nike_57_46486, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_57_46486, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_58_46486 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_58_46486, &face_analog_nike_dial_img_57_46486_0);
    lv_obj_set_width(face_analog_nike_58_46486, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_58_46486, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_58_46486, 58);
    lv_obj_set_y(face_analog_nike_58_46486, 28);
    lv_obj_add_flag(face_analog_nike_58_46486, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_58_46486, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_59_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_59_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_59_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_59_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_59_130643, 66);
    lv_obj_set_y(face_analog_nike_59_130643, 24);
    lv_obj_add_flag(face_analog_nike_59_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_59_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_60_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_60_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_60_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_60_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_60_130643, 58);
    lv_obj_set_y(face_analog_nike_60_130643, 24);
    lv_obj_add_flag(face_analog_nike_60_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_60_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_61_130643 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_61_130643, &face_analog_nike_dial_img_4_130643_0);
    lv_obj_set_width(face_analog_nike_61_130643, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_61_130643, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_61_130643, 50);
    lv_obj_set_y(face_analog_nike_61_130643, 24);
    lv_obj_add_flag(face_analog_nike_61_130643, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_61_130643, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_62_135751 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_62_135751, &face_analog_nike_dial_img_62_135751_0);
    lv_obj_set_width(face_analog_nike_62_135751, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_62_135751, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_62_135751, 74);
    lv_obj_set_y(face_analog_nike_62_135751, 24);
    lv_obj_add_flag(face_analog_nike_62_135751, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_62_135751, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_63_128895 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_63_128895, &face_analog_nike_dial_img_63_128895_0);
    lv_obj_set_width(face_analog_nike_63_128895, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_63_128895, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_63_128895, 74);
    lv_obj_set_y(face_analog_nike_63_128895, 24);
    lv_obj_add_flag(face_analog_nike_63_128895, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_63_128895, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_nike_64_46486 = lv_img_create(face_analog_nike);
    lv_img_set_src(face_analog_nike_64_46486, &face_analog_nike_dial_img_57_46486_0);
    lv_obj_set_width(face_analog_nike_64_46486, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_nike_64_46486, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_nike_64_46486, 50);
    lv_obj_set_y(face_analog_nike_64_46486, 28);
    lv_obj_add_flag(face_analog_nike_64_46486, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_nike_64_46486, LV_OBJ_FLAG_SCROLLABLE );


    callback("analog nike", &face_analog_nike_dial_img_preview_0, &face_analog_nike);

#endif
}

void update_time_analog_nike(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_ANALOG_NIKE
    if (!face_analog_nike)
    {
        return;
    }
	lv_img_set_src(face_analog_nike_4_130643, face_analog_nike_dial_img_4_130643_group[(month / 1) % 10]);
	lv_img_set_src(face_analog_nike_5_130643, face_analog_nike_dial_img_4_130643_group[(month / 10) % 10]);
	lv_img_set_src(face_analog_nike_6_130643, face_analog_nike_dial_img_4_130643_group[(day / 1) % 10]);
	lv_img_set_src(face_analog_nike_7_130643, face_analog_nike_dial_img_4_130643_group[(day / 10) % 10]);
	lv_img_set_src(face_analog_nike_8_136825, face_analog_nike_dial_img_8_136825_group[(hour / 1) % 10]);
	lv_img_set_src(face_analog_nike_9_136825, face_analog_nike_dial_img_8_136825_group[(hour / 10) % 10]);
	lv_img_set_src(face_analog_nike_10_136825, face_analog_nike_dial_img_8_136825_group[(minute / 1) % 10]);
	lv_img_set_src(face_analog_nike_11_136825, face_analog_nike_dial_img_8_136825_group[(minute / 10) % 10]);

#endif
}

void update_weather_analog_nike(int temp, int icon)
{
#ifdef ENABLE_FACE_ANALOG_NIKE
    if (!face_analog_nike)
    {
        return;
    }
	lv_img_set_src(face_analog_nike_48_73266, face_analog_nike_dial_img_weather[icon % 8]);

#endif
}

void update_status_analog_nike(int battery, bool connection){
#ifdef ENABLE_FACE_ANALOG_NIKE
    if (!face_analog_nike)
    {
        return;
    }
	lv_img_set_src(face_analog_nike_16_130643, face_analog_nike_dial_img_4_130643_group[(battery / 1) % 10]);
	lv_img_set_src(face_analog_nike_17_130643, face_analog_nike_dial_img_4_130643_group[(battery / 10) % 10]);
	lv_img_set_src(face_analog_nike_18_130643, face_analog_nike_dial_img_4_130643_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_analog_nike_18_130643, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_analog_nike_18_130643, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_analog_nike(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_ANALOG_NIKE
    if (!face_analog_nike)
    {
        return;
    }
	lv_img_set_src(face_analog_nike_38_130643, face_analog_nike_dial_img_4_130643_group[(kcal / 1) % 10]);
	lv_img_set_src(face_analog_nike_39_130643, face_analog_nike_dial_img_4_130643_group[(kcal / 10) % 10]);
	lv_img_set_src(face_analog_nike_40_130643, face_analog_nike_dial_img_4_130643_group[(kcal / 100) % 10]);
	lv_img_set_src(face_analog_nike_41_130643, face_analog_nike_dial_img_4_130643_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_analog_nike_42_130643, face_analog_nike_dial_img_4_130643_group[(steps / 1) % 10]);
	lv_img_set_src(face_analog_nike_43_130643, face_analog_nike_dial_img_4_130643_group[(steps / 10) % 10]);
	lv_img_set_src(face_analog_nike_44_130643, face_analog_nike_dial_img_4_130643_group[(steps / 100) % 10]);
	lv_img_set_src(face_analog_nike_45_130643, face_analog_nike_dial_img_4_130643_group[(steps / 1000) % 10]);
	lv_img_set_src(face_analog_nike_46_130643, face_analog_nike_dial_img_4_130643_group[(steps / 10000) % 10]);

#endif
}

void update_health_analog_nike(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_NIKE
    if (!face_analog_nike)
    {
        return;
    }
	lv_img_set_src(face_analog_nike_35_130643, face_analog_nike_dial_img_4_130643_group[(bpm / 1) % 10]);
	lv_img_set_src(face_analog_nike_36_130643, face_analog_nike_dial_img_4_130643_group[(bpm / 10) % 10]);
	lv_img_set_src(face_analog_nike_37_130643, face_analog_nike_dial_img_4_130643_group[(bpm / 100) % 10]);

#endif
}

void update_all_analog_nike(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_NIKE
    update_time_analog_nike(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_analog_nike(temp, icon);
    update_status_analog_nike(battery, connection);
    update_activity_analog_nike(steps, distance, kcal);
    update_health_analog_nike(bpm, oxygen);
#endif
}

void update_check_analog_nike(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_NIKE
    if (root != face_analog_nike)
    {
        return;
    }
    update_time_analog_nike(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_analog_nike(temp, icon);
    update_status_analog_nike(battery, connection);
    update_activity_analog_nike(steps, distance, kcal);
    update_health_analog_nike(bpm, oxygen);
#endif
}


