
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_RABBIT

#ifndef _FACE_DIAL_RABBIT_H
#define _FACE_DIAL_RABBIT_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

// #define ENABLE_FACE_DIAL_RABBIT // (dial rabbit) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_DIAL_RABBIT
    extern lv_obj_t *face_dial_rabbit;
	extern lv_obj_t *face_dial_rabbit_0_3646;
	extern lv_obj_t *face_dial_rabbit_1_75194;
	extern lv_obj_t *face_dial_rabbit_3_144644;
	extern lv_obj_t *face_dial_rabbit_13_117606;
	extern lv_obj_t *face_dial_rabbit_15_102272;
	extern lv_obj_t *face_dial_rabbit_17_115528;
	extern lv_obj_t *face_dial_rabbit_19_112780;
	extern lv_obj_t *face_dial_rabbit_21_126710;
	extern lv_obj_t *face_dial_rabbit_22_133180;
	extern lv_obj_t *face_dial_rabbit_23_133180;
	extern lv_obj_t *face_dial_rabbit_24_133180;
	extern lv_obj_t *face_dial_rabbit_25_133180;
	extern lv_obj_t *face_dial_rabbit_26_113598;
	extern lv_obj_t *face_dial_rabbit_27_113754;
	extern lv_obj_t *face_dial_rabbit_28_113754;
	extern lv_obj_t *face_dial_rabbit_29_113754;
	extern lv_obj_t *face_dial_rabbit_30_113754;
	extern lv_obj_t *face_dial_rabbit_31_113754;
	extern lv_obj_t *face_dial_rabbit_32_113754;
	extern lv_obj_t *face_dial_rabbit_33_113754;
	extern lv_obj_t *face_dial_rabbit_34_113754;
	extern lv_obj_t *face_dial_rabbit_35_115046;
	extern lv_obj_t *face_dial_rabbit_36_115046;
	extern lv_obj_t *face_dial_rabbit_38_115929;
	extern lv_obj_t *face_dial_rabbit_39_113754;
	extern lv_obj_t *face_dial_rabbit_40_113754;
	extern lv_obj_t *face_dial_rabbit_41_113754;
	extern lv_obj_t *face_dial_rabbit_42_1264;
	extern lv_obj_t *face_dial_rabbit_44_116371;
	extern lv_obj_t *face_dial_rabbit_45_127508;
	extern lv_obj_t *face_dial_rabbit_46_127508;
	extern lv_obj_t *face_dial_rabbit_47_127508;
	extern lv_obj_t *face_dial_rabbit_48_113754;
	extern lv_obj_t *face_dial_rabbit_49_113754;
	extern lv_obj_t *face_dial_rabbit_50_129698;
	extern lv_obj_t *face_dial_rabbit_51_129698;
	extern lv_obj_t *face_dial_rabbit_52_129698;
	extern lv_obj_t *face_dial_rabbit_53_115068;
	extern lv_obj_t *face_dial_rabbit_55_103279;
	extern lv_obj_t *face_dial_rabbit_57_116732;
	extern lv_obj_t *face_dial_rabbit_58_129698;
	extern lv_obj_t *face_dial_rabbit_59_129698;
	extern lv_obj_t *face_dial_rabbit_60_129698;
	extern lv_obj_t *face_dial_rabbit_61_129698;
	extern lv_obj_t *face_dial_rabbit_62_129698;


	LV_IMG_DECLARE(face_dial_rabbit_dial_img_0_3646_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_1_75194_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_1_75194_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_1_75194_2);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_1_75194_3);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_1_75194_4);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_1_75194_5);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_1_75194_6);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_3_144644_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_4_148017_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_5_147497_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_6_146478_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_7_146036_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_8_146940_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_9_148577_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_10_145122_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_11_145658_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_2);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_3);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_4);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_5);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_6);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_7);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_8);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_9);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_10);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_12_104324_11);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_2);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_3);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_4);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_5);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_6);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_7);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_8);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_9);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_10);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_13_117606_11);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_14_101880_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_14_101880_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_15_102272_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_15_102272_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_16_115127_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_16_115127_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_17_115528_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_17_115528_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_18_113189_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_18_113189_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_19_112780_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_19_112780_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_20_127109_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_20_127109_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_21_126710_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_21_126710_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_2);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_3);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_4);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_5);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_6);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_7);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_8);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_22_133180_9);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_26_113598_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_2);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_3);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_4);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_5);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_6);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_7);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_8);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_27_113754_9);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_35_115046_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_37_102664_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_38_115929_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_42_1264_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_42_1264_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_42_1264_2);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_42_1264_3);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_42_1264_4);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_42_1264_5);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_43_103076_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_44_116371_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_2);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_3);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_4);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_5);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_6);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_7);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_8);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_45_127508_9);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_1);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_2);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_3);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_4);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_5);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_6);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_7);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_8);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_50_129698_9);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_53_115068_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_54_103825_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_55_103279_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_56_117212_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_57_116732_0);
	LV_IMG_DECLARE(face_dial_rabbit_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_dial_rabbit(void (*callback)(const char *name, const lv_img_dsc_t *preview, lv_obj_t **watchface, int anim_img_num, lv_obj_t *anim_img, const lv_img_dsc_t **anim_img_group));
    void update_time_dial_rabbit(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_dial_rabbit(int temp, int icon);
    void update_status_dial_rabbit(int battery, bool connection);
    void update_activity_dial_rabbit(int steps, int distance, int kcal);
    void update_health_dial_rabbit(int bpm, int oxygen);
    void update_all_dial_rabbit(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_dial_rabbit(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
