
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_RABBIT

#include "dial_rabbit.h"

#ifdef ENABLE_FACE_DIAL_RABBIT

lv_obj_t *face_dial_rabbit;
lv_obj_t *face_dial_rabbit_0_3646;
lv_obj_t *face_dial_rabbit_1_75194;
lv_obj_t *face_dial_rabbit_3_144644;
lv_obj_t *face_dial_rabbit_13_117606;
lv_obj_t *face_dial_rabbit_15_102272;
lv_obj_t *face_dial_rabbit_17_115528;
lv_obj_t *face_dial_rabbit_19_112780;
lv_obj_t *face_dial_rabbit_21_126710;
lv_obj_t *face_dial_rabbit_22_133180;
lv_obj_t *face_dial_rabbit_23_133180;
lv_obj_t *face_dial_rabbit_24_133180;
lv_obj_t *face_dial_rabbit_25_133180;
lv_obj_t *face_dial_rabbit_26_113598;
lv_obj_t *face_dial_rabbit_27_113754;
lv_obj_t *face_dial_rabbit_28_113754;
lv_obj_t *face_dial_rabbit_29_113754;
lv_obj_t *face_dial_rabbit_30_113754;
lv_obj_t *face_dial_rabbit_31_113754;
lv_obj_t *face_dial_rabbit_32_113754;
lv_obj_t *face_dial_rabbit_33_113754;
lv_obj_t *face_dial_rabbit_34_113754;
lv_obj_t *face_dial_rabbit_35_115046;
lv_obj_t *face_dial_rabbit_36_115046;
lv_obj_t *face_dial_rabbit_38_115929;
lv_obj_t *face_dial_rabbit_39_113754;
lv_obj_t *face_dial_rabbit_40_113754;
lv_obj_t *face_dial_rabbit_41_113754;
lv_obj_t *face_dial_rabbit_42_1264;
lv_obj_t *face_dial_rabbit_44_116371;
lv_obj_t *face_dial_rabbit_45_127508;
lv_obj_t *face_dial_rabbit_46_127508;
lv_obj_t *face_dial_rabbit_47_127508;
lv_obj_t *face_dial_rabbit_48_113754;
lv_obj_t *face_dial_rabbit_49_113754;
lv_obj_t *face_dial_rabbit_50_129698;
lv_obj_t *face_dial_rabbit_51_129698;
lv_obj_t *face_dial_rabbit_52_129698;
lv_obj_t *face_dial_rabbit_53_115068;
lv_obj_t *face_dial_rabbit_55_103279;
lv_obj_t *face_dial_rabbit_57_116732;
lv_obj_t *face_dial_rabbit_58_129698;
lv_obj_t *face_dial_rabbit_59_129698;
lv_obj_t *face_dial_rabbit_60_129698;
lv_obj_t *face_dial_rabbit_61_129698;
lv_obj_t *face_dial_rabbit_62_129698;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_rabbit_dial_img_1_75194_group[] = {
	&face_dial_rabbit_dial_img_1_75194_0,
	&face_dial_rabbit_dial_img_1_75194_1,
	&face_dial_rabbit_dial_img_1_75194_2,
	&face_dial_rabbit_dial_img_1_75194_3,
	&face_dial_rabbit_dial_img_1_75194_4,
	&face_dial_rabbit_dial_img_1_75194_5,
	&face_dial_rabbit_dial_img_1_75194_6,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_weather[] = {
	&face_dial_rabbit_dial_img_3_144644_0,
	&face_dial_rabbit_dial_img_4_148017_0,
	&face_dial_rabbit_dial_img_5_147497_0,
	&face_dial_rabbit_dial_img_6_146478_0,
	&face_dial_rabbit_dial_img_7_146036_0,
	&face_dial_rabbit_dial_img_8_146940_0,
	&face_dial_rabbit_dial_img_9_148577_0,
	&face_dial_rabbit_dial_img_10_145122_0,
	&face_dial_rabbit_dial_img_11_145658_0,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_12_104324_group[] = {
	&face_dial_rabbit_dial_img_12_104324_0,
	&face_dial_rabbit_dial_img_12_104324_1,
	&face_dial_rabbit_dial_img_12_104324_2,
	&face_dial_rabbit_dial_img_12_104324_3,
	&face_dial_rabbit_dial_img_12_104324_4,
	&face_dial_rabbit_dial_img_12_104324_5,
	&face_dial_rabbit_dial_img_12_104324_6,
	&face_dial_rabbit_dial_img_12_104324_7,
	&face_dial_rabbit_dial_img_12_104324_8,
	&face_dial_rabbit_dial_img_12_104324_9,
	&face_dial_rabbit_dial_img_12_104324_10,
	&face_dial_rabbit_dial_img_12_104324_11,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_13_117606_group[] = {
	&face_dial_rabbit_dial_img_13_117606_0,
	&face_dial_rabbit_dial_img_13_117606_1,
	&face_dial_rabbit_dial_img_13_117606_2,
	&face_dial_rabbit_dial_img_13_117606_3,
	&face_dial_rabbit_dial_img_13_117606_4,
	&face_dial_rabbit_dial_img_13_117606_5,
	&face_dial_rabbit_dial_img_13_117606_6,
	&face_dial_rabbit_dial_img_13_117606_7,
	&face_dial_rabbit_dial_img_13_117606_8,
	&face_dial_rabbit_dial_img_13_117606_9,
	&face_dial_rabbit_dial_img_13_117606_10,
	&face_dial_rabbit_dial_img_13_117606_11,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_14_101880_group[] = {
	&face_dial_rabbit_dial_img_14_101880_0,
	&face_dial_rabbit_dial_img_14_101880_1,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_15_102272_group[] = {
	&face_dial_rabbit_dial_img_15_102272_0,
	&face_dial_rabbit_dial_img_15_102272_1,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_16_115127_group[] = {
	&face_dial_rabbit_dial_img_16_115127_0,
	&face_dial_rabbit_dial_img_16_115127_1,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_17_115528_group[] = {
	&face_dial_rabbit_dial_img_17_115528_0,
	&face_dial_rabbit_dial_img_17_115528_1,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_18_113189_group[] = {
	&face_dial_rabbit_dial_img_18_113189_0,
	&face_dial_rabbit_dial_img_18_113189_1,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_19_112780_group[] = {
	&face_dial_rabbit_dial_img_19_112780_0,
	&face_dial_rabbit_dial_img_19_112780_1,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_20_127109_group[] = {
	&face_dial_rabbit_dial_img_20_127109_0,
	&face_dial_rabbit_dial_img_20_127109_1,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_21_126710_group[] = {
	&face_dial_rabbit_dial_img_21_126710_0,
	&face_dial_rabbit_dial_img_21_126710_1,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_22_133180_group[] = {
	&face_dial_rabbit_dial_img_22_133180_0,
	&face_dial_rabbit_dial_img_22_133180_1,
	&face_dial_rabbit_dial_img_22_133180_2,
	&face_dial_rabbit_dial_img_22_133180_3,
	&face_dial_rabbit_dial_img_22_133180_4,
	&face_dial_rabbit_dial_img_22_133180_5,
	&face_dial_rabbit_dial_img_22_133180_6,
	&face_dial_rabbit_dial_img_22_133180_7,
	&face_dial_rabbit_dial_img_22_133180_8,
	&face_dial_rabbit_dial_img_22_133180_9,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_27_113754_group[] = {
	&face_dial_rabbit_dial_img_27_113754_0,
	&face_dial_rabbit_dial_img_27_113754_1,
	&face_dial_rabbit_dial_img_27_113754_2,
	&face_dial_rabbit_dial_img_27_113754_3,
	&face_dial_rabbit_dial_img_27_113754_4,
	&face_dial_rabbit_dial_img_27_113754_5,
	&face_dial_rabbit_dial_img_27_113754_6,
	&face_dial_rabbit_dial_img_27_113754_7,
	&face_dial_rabbit_dial_img_27_113754_8,
	&face_dial_rabbit_dial_img_27_113754_9,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_42_1264_group[] = {
	&face_dial_rabbit_dial_img_42_1264_0,
	&face_dial_rabbit_dial_img_42_1264_1,
	&face_dial_rabbit_dial_img_42_1264_2,
	&face_dial_rabbit_dial_img_42_1264_3,
	&face_dial_rabbit_dial_img_42_1264_4,
	&face_dial_rabbit_dial_img_42_1264_5,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_45_127508_group[] = {
	&face_dial_rabbit_dial_img_45_127508_0,
	&face_dial_rabbit_dial_img_45_127508_1,
	&face_dial_rabbit_dial_img_45_127508_2,
	&face_dial_rabbit_dial_img_45_127508_3,
	&face_dial_rabbit_dial_img_45_127508_4,
	&face_dial_rabbit_dial_img_45_127508_5,
	&face_dial_rabbit_dial_img_45_127508_6,
	&face_dial_rabbit_dial_img_45_127508_7,
	&face_dial_rabbit_dial_img_45_127508_8,
	&face_dial_rabbit_dial_img_45_127508_9,
};
const lv_img_dsc_t *face_dial_rabbit_dial_img_50_129698_group[] = {
	&face_dial_rabbit_dial_img_50_129698_0,
	&face_dial_rabbit_dial_img_50_129698_1,
	&face_dial_rabbit_dial_img_50_129698_2,
	&face_dial_rabbit_dial_img_50_129698_3,
	&face_dial_rabbit_dial_img_50_129698_4,
	&face_dial_rabbit_dial_img_50_129698_5,
	&face_dial_rabbit_dial_img_50_129698_6,
	&face_dial_rabbit_dial_img_50_129698_7,
	&face_dial_rabbit_dial_img_50_129698_8,
	&face_dial_rabbit_dial_img_50_129698_9,
};


#endif

void init_face_dial_rabbit(void (*callback)(const char *name, const lv_img_dsc_t *preview, lv_obj_t **watchface, int anim_img_num, lv_obj_t *anim_img, const lv_img_dsc_t **anim_img_group)){
#ifdef ENABLE_FACE_DIAL_RABBIT
    face_dial_rabbit = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_rabbit, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_rabbit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_rabbit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_rabbit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_rabbit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_rabbit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_rabbit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_rabbit, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_rabbit, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_rabbit_0_3646 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_0_3646, &face_dial_rabbit_dial_img_0_3646_0);
    lv_obj_set_width(face_dial_rabbit_0_3646, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_0_3646, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_0_3646, 0);
    lv_obj_set_y(face_dial_rabbit_0_3646, 0);
    lv_obj_add_flag(face_dial_rabbit_0_3646, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_0_3646, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_1_75194 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_1_75194, &face_dial_rabbit_dial_img_1_75194_0);
    lv_obj_set_width(face_dial_rabbit_1_75194, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_1_75194, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_1_75194, 137);
    lv_obj_set_y(face_dial_rabbit_1_75194, 21);
    lv_obj_add_flag(face_dial_rabbit_1_75194, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_1_75194, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_3_144644 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_3_144644, &face_dial_rabbit_dial_img_3_144644_0);
    lv_obj_set_width(face_dial_rabbit_3_144644, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_3_144644, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_3_144644, 32);
    lv_obj_set_y(face_dial_rabbit_3_144644, 88);
    lv_obj_add_flag(face_dial_rabbit_3_144644, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_3_144644, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_13_117606 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_13_117606, &face_dial_rabbit_dial_img_13_117606_0);
    lv_obj_set_width(face_dial_rabbit_13_117606, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_13_117606, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_13_117606, 78);
    lv_obj_set_y(face_dial_rabbit_13_117606, 76);
    lv_obj_add_flag(face_dial_rabbit_13_117606, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_13_117606, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_15_102272 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_15_102272, &face_dial_rabbit_dial_img_15_102272_0);
    lv_obj_set_width(face_dial_rabbit_15_102272, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_15_102272, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_15_102272, 16);
    lv_obj_set_y(face_dial_rabbit_15_102272, 125);
    lv_obj_add_flag(face_dial_rabbit_15_102272, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_15_102272, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_17_115528 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_17_115528, &face_dial_rabbit_dial_img_17_115528_0);
    lv_obj_set_width(face_dial_rabbit_17_115528, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_17_115528, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_17_115528, 16);
    lv_obj_set_y(face_dial_rabbit_17_115528, 125);
    lv_obj_add_flag(face_dial_rabbit_17_115528, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_17_115528, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_19_112780 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_19_112780, &face_dial_rabbit_dial_img_19_112780_0);
    lv_obj_set_width(face_dial_rabbit_19_112780, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_19_112780, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_19_112780, 16);
    lv_obj_set_y(face_dial_rabbit_19_112780, 156);
    lv_obj_add_flag(face_dial_rabbit_19_112780, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_19_112780, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_21_126710 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_21_126710, &face_dial_rabbit_dial_img_21_126710_0);
    lv_obj_set_width(face_dial_rabbit_21_126710, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_21_126710, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_21_126710, 16);
    lv_obj_set_y(face_dial_rabbit_21_126710, 156);
    lv_obj_add_flag(face_dial_rabbit_21_126710, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_21_126710, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_22_133180 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_22_133180, &face_dial_rabbit_dial_img_22_133180_0);
    lv_obj_set_width(face_dial_rabbit_22_133180, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_22_133180, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_22_133180, 102);
    lv_obj_set_y(face_dial_rabbit_22_133180, 115);
    lv_obj_add_flag(face_dial_rabbit_22_133180, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_22_133180, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_23_133180 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_23_133180, &face_dial_rabbit_dial_img_22_133180_0);
    lv_obj_set_width(face_dial_rabbit_23_133180, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_23_133180, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_23_133180, 67);
    lv_obj_set_y(face_dial_rabbit_23_133180, 115);
    lv_obj_add_flag(face_dial_rabbit_23_133180, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_23_133180, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_24_133180 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_24_133180, &face_dial_rabbit_dial_img_22_133180_0);
    lv_obj_set_width(face_dial_rabbit_24_133180, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_24_133180, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_24_133180, 181);
    lv_obj_set_y(face_dial_rabbit_24_133180, 115);
    lv_obj_add_flag(face_dial_rabbit_24_133180, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_24_133180, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_25_133180 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_25_133180, &face_dial_rabbit_dial_img_22_133180_0);
    lv_obj_set_width(face_dial_rabbit_25_133180, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_25_133180, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_25_133180, 146);
    lv_obj_set_y(face_dial_rabbit_25_133180, 115);
    lv_obj_add_flag(face_dial_rabbit_25_133180, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_25_133180, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_26_113598 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_26_113598, &face_dial_rabbit_dial_img_26_113598_0);
    lv_obj_set_width(face_dial_rabbit_26_113598, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_26_113598, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_26_113598, 134);
    lv_obj_set_y(face_dial_rabbit_26_113598, 126);
    lv_obj_add_flag(face_dial_rabbit_26_113598, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_26_113598, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_27_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_27_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_27_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_27_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_27_113754, 164);
    lv_obj_set_y(face_dial_rabbit_27_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_27_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_27_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_28_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_28_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_28_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_28_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_28_113754, 153);
    lv_obj_set_y(face_dial_rabbit_28_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_28_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_28_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_29_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_29_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_29_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_29_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_29_113754, 142);
    lv_obj_set_y(face_dial_rabbit_29_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_29_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_29_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_30_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_30_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_30_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_30_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_30_113754, 131);
    lv_obj_set_y(face_dial_rabbit_30_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_30_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_30_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_31_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_31_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_31_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_31_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_31_113754, 111);
    lv_obj_set_y(face_dial_rabbit_31_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_31_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_31_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_32_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_32_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_32_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_32_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_32_113754, 100);
    lv_obj_set_y(face_dial_rabbit_32_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_32_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_32_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_33_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_33_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_33_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_33_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_33_113754, 76);
    lv_obj_set_y(face_dial_rabbit_33_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_33_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_33_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_34_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_34_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_34_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_34_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_34_113754, 65);
    lv_obj_set_y(face_dial_rabbit_34_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_34_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_34_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_35_115046 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_35_115046, &face_dial_rabbit_dial_img_35_115046_0);
    lv_obj_set_width(face_dial_rabbit_35_115046, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_35_115046, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_35_115046, 87);
    lv_obj_set_y(face_dial_rabbit_35_115046, 174);
    lv_obj_add_flag(face_dial_rabbit_35_115046, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_35_115046, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_36_115046 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_36_115046, &face_dial_rabbit_dial_img_35_115046_0);
    lv_obj_set_width(face_dial_rabbit_36_115046, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_36_115046, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_36_115046, 122);
    lv_obj_set_y(face_dial_rabbit_36_115046, 174);
    lv_obj_add_flag(face_dial_rabbit_36_115046, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_36_115046, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_38_115929 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_38_115929, &face_dial_rabbit_dial_img_38_115929_0);
    lv_obj_set_width(face_dial_rabbit_38_115929, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_38_115929, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_38_115929, 190);
    lv_obj_set_y(face_dial_rabbit_38_115929, 189);
    lv_obj_add_flag(face_dial_rabbit_38_115929, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_38_115929, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_39_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_39_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_39_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_39_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_39_113754, 206);
    lv_obj_set_y(face_dial_rabbit_39_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_39_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_39_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_40_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_40_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_40_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_40_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_40_113754, 195);
    lv_obj_set_y(face_dial_rabbit_40_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_40_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_40_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_41_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_41_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_41_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_41_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_41_113754, 184);
    lv_obj_set_y(face_dial_rabbit_41_113754, 168);
    lv_obj_add_flag(face_dial_rabbit_41_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_41_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_42_1264 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_42_1264, &face_dial_rabbit_dial_img_42_1264_0);
    lv_obj_set_width(face_dial_rabbit_42_1264, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_42_1264, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_42_1264, 212);
    lv_obj_set_y(face_dial_rabbit_42_1264, 120);
    lv_obj_add_flag(face_dial_rabbit_42_1264, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_42_1264, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_44_116371 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_44_116371, &face_dial_rabbit_dial_img_44_116371_0);
    lv_obj_set_width(face_dial_rabbit_44_116371, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_44_116371, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_44_116371, 81);
    lv_obj_set_y(face_dial_rabbit_44_116371, 21);
    lv_obj_add_flag(face_dial_rabbit_44_116371, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_44_116371, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_45_127508 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_45_127508, &face_dial_rabbit_dial_img_45_127508_0);
    lv_obj_set_width(face_dial_rabbit_45_127508, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_45_127508, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_45_127508, 102);
    lv_obj_set_y(face_dial_rabbit_45_127508, 44);
    lv_obj_add_flag(face_dial_rabbit_45_127508, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_45_127508, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_46_127508 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_46_127508, &face_dial_rabbit_dial_img_45_127508_0);
    lv_obj_set_width(face_dial_rabbit_46_127508, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_46_127508, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_46_127508, 89);
    lv_obj_set_y(face_dial_rabbit_46_127508, 44);
    lv_obj_add_flag(face_dial_rabbit_46_127508, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_46_127508, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_47_127508 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_47_127508, &face_dial_rabbit_dial_img_45_127508_0);
    lv_obj_set_width(face_dial_rabbit_47_127508, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_47_127508, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_47_127508, 76);
    lv_obj_set_y(face_dial_rabbit_47_127508, 44);
    lv_obj_add_flag(face_dial_rabbit_47_127508, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_47_127508, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_48_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_48_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_48_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_48_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_48_113754, 160);
    lv_obj_set_y(face_dial_rabbit_48_113754, 216);
    lv_obj_add_flag(face_dial_rabbit_48_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_48_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_49_113754 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_49_113754, &face_dial_rabbit_dial_img_27_113754_0);
    lv_obj_set_width(face_dial_rabbit_49_113754, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_49_113754, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_49_113754, 150);
    lv_obj_set_y(face_dial_rabbit_49_113754, 216);
    lv_obj_add_flag(face_dial_rabbit_49_113754, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_49_113754, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_50_129698 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_50_129698, &face_dial_rabbit_dial_img_50_129698_0);
    lv_obj_set_width(face_dial_rabbit_50_129698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_50_129698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_50_129698, 99);
    lv_obj_set_y(face_dial_rabbit_50_129698, 247);
    lv_obj_add_flag(face_dial_rabbit_50_129698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_50_129698, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_51_129698 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_51_129698, &face_dial_rabbit_dial_img_50_129698_0);
    lv_obj_set_width(face_dial_rabbit_51_129698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_51_129698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_51_129698, 74);
    lv_obj_set_y(face_dial_rabbit_51_129698, 247);
    lv_obj_add_flag(face_dial_rabbit_51_129698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_51_129698, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_52_129698 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_52_129698, &face_dial_rabbit_dial_img_50_129698_0);
    lv_obj_set_width(face_dial_rabbit_52_129698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_52_129698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_52_129698, 56);
    lv_obj_set_y(face_dial_rabbit_52_129698, 247);
    lv_obj_add_flag(face_dial_rabbit_52_129698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_52_129698, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_53_115068 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_53_115068, &face_dial_rabbit_dial_img_53_115068_0);
    lv_obj_set_width(face_dial_rabbit_53_115068, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_53_115068, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_53_115068, 91);
    lv_obj_set_y(face_dial_rabbit_53_115068, 262);
    lv_obj_add_flag(face_dial_rabbit_53_115068, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_53_115068, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_55_103279 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_55_103279, &face_dial_rabbit_dial_img_55_103279_0);
    lv_obj_set_width(face_dial_rabbit_55_103279, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_55_103279, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_55_103279, 120);
    lv_obj_set_y(face_dial_rabbit_55_103279, 255);
    lv_obj_add_flag(face_dial_rabbit_55_103279, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_55_103279, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_57_116732 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_57_116732, &face_dial_rabbit_dial_img_57_116732_0);
    lv_obj_set_width(face_dial_rabbit_57_116732, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_57_116732, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_57_116732, 121);
    lv_obj_set_y(face_dial_rabbit_57_116732, 255);
    lv_obj_add_flag(face_dial_rabbit_57_116732, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_57_116732, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_58_129698 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_58_129698, &face_dial_rabbit_dial_img_50_129698_0);
    lv_obj_set_width(face_dial_rabbit_58_129698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_58_129698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_58_129698, 110);
    lv_obj_set_y(face_dial_rabbit_58_129698, 210);
    lv_obj_add_flag(face_dial_rabbit_58_129698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_58_129698, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_59_129698 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_59_129698, &face_dial_rabbit_dial_img_50_129698_0);
    lv_obj_set_width(face_dial_rabbit_59_129698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_59_129698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_59_129698, 92);
    lv_obj_set_y(face_dial_rabbit_59_129698, 210);
    lv_obj_add_flag(face_dial_rabbit_59_129698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_59_129698, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_60_129698 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_60_129698, &face_dial_rabbit_dial_img_50_129698_0);
    lv_obj_set_width(face_dial_rabbit_60_129698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_60_129698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_60_129698, 74);
    lv_obj_set_y(face_dial_rabbit_60_129698, 210);
    lv_obj_add_flag(face_dial_rabbit_60_129698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_60_129698, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_61_129698 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_61_129698, &face_dial_rabbit_dial_img_50_129698_0);
    lv_obj_set_width(face_dial_rabbit_61_129698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_61_129698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_61_129698, 56);
    lv_obj_set_y(face_dial_rabbit_61_129698, 210);
    lv_obj_add_flag(face_dial_rabbit_61_129698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_61_129698, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_rabbit_62_129698 = lv_img_create(face_dial_rabbit);
    lv_img_set_src(face_dial_rabbit_62_129698, &face_dial_rabbit_dial_img_50_129698_0);
    lv_obj_set_width(face_dial_rabbit_62_129698, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_rabbit_62_129698, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_rabbit_62_129698, 38);
    lv_obj_set_y(face_dial_rabbit_62_129698, 210);
    lv_obj_add_flag(face_dial_rabbit_62_129698, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_rabbit_62_129698, LV_OBJ_FLAG_SCROLLABLE );

    int anim_img_num = sizeof(face_dial_rabbit_dial_img_1_75194_group) / sizeof(face_dial_rabbit_dial_img_1_75194_group[0]);
    callback("dial rabbit", &face_dial_rabbit_dial_img_preview_0, &face_dial_rabbit, anim_img_num, face_dial_rabbit_1_75194, face_dial_rabbit_dial_img_1_75194_group);

#endif
}

void update_time_dial_rabbit(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_RABBIT
    if (!face_dial_rabbit)
    {
        return;
    }
	lv_img_set_src(face_dial_rabbit_13_117606, face_dial_rabbit_dial_img_13_117606_group[((month - 1) / 1) % 12]);
	if (mode)
	{
		lv_obj_add_flag(face_dial_rabbit_15_102272, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_rabbit_15_102272, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_rabbit_15_102272, face_dial_rabbit_dial_img_15_102272_group[(am ? 0 : 1) % 2]);
	if (mode)
	{
		lv_obj_add_flag(face_dial_rabbit_17_115528, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_rabbit_17_115528, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_rabbit_17_115528, face_dial_rabbit_dial_img_17_115528_group[(am ? 0 : 1) % 2]);
	if (mode)
	{
		lv_obj_add_flag(face_dial_rabbit_19_112780, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_rabbit_19_112780, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_rabbit_19_112780, face_dial_rabbit_dial_img_19_112780_group[(am ? 0 : 1) % 2]);
	if (mode)
	{
		lv_obj_add_flag(face_dial_rabbit_21_126710, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_rabbit_21_126710, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_rabbit_21_126710, face_dial_rabbit_dial_img_21_126710_group[(am ? 0 : 1) % 2]);
	lv_img_set_src(face_dial_rabbit_22_133180, face_dial_rabbit_dial_img_22_133180_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_rabbit_23_133180, face_dial_rabbit_dial_img_22_133180_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_rabbit_24_133180, face_dial_rabbit_dial_img_22_133180_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_rabbit_25_133180, face_dial_rabbit_dial_img_22_133180_group[(minute / 10) % 10]);
	lv_img_set_src(face_dial_rabbit_27_113754, face_dial_rabbit_dial_img_27_113754_group[(year / 1) % 10]);
	lv_img_set_src(face_dial_rabbit_28_113754, face_dial_rabbit_dial_img_27_113754_group[(year / 10) % 10]);
	lv_img_set_src(face_dial_rabbit_29_113754, face_dial_rabbit_dial_img_27_113754_group[(year / 100) % 10]);
	lv_img_set_src(face_dial_rabbit_30_113754, face_dial_rabbit_dial_img_27_113754_group[(year / 1000) % 10]);
	lv_img_set_src(face_dial_rabbit_31_113754, face_dial_rabbit_dial_img_27_113754_group[(month / 10) % 10]);
	lv_img_set_src(face_dial_rabbit_32_113754, face_dial_rabbit_dial_img_27_113754_group[(month / 100) % 10]);
	lv_img_set_src(face_dial_rabbit_33_113754, face_dial_rabbit_dial_img_27_113754_group[(day / 1) % 10]);
	lv_img_set_src(face_dial_rabbit_34_113754, face_dial_rabbit_dial_img_27_113754_group[(day / 10) % 10]);

#endif
}

void update_weather_dial_rabbit(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_RABBIT
    if (!face_dial_rabbit)
    {
        return;
    }
	lv_img_set_src(face_dial_rabbit_3_144644, face_dial_rabbit_dial_img_weather[icon % 8]);

#endif
}

void update_status_dial_rabbit(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_RABBIT
    if (!face_dial_rabbit)
    {
        return;
    }
	lv_img_set_src(face_dial_rabbit_39_113754, face_dial_rabbit_dial_img_27_113754_group[(battery / 1) % 10]);
	lv_img_set_src(face_dial_rabbit_40_113754, face_dial_rabbit_dial_img_27_113754_group[(battery / 10) % 10]);
	lv_img_set_src(face_dial_rabbit_41_113754, face_dial_rabbit_dial_img_27_113754_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_dial_rabbit_41_113754, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_rabbit_41_113754, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_rabbit_42_1264, face_dial_rabbit_dial_img_42_1264_group[(battery / (100 / 6)) % 6]);

#endif
}

void update_activity_dial_rabbit(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_RABBIT
    if (!face_dial_rabbit)
    {
        return;
    }
	lv_img_set_src(face_dial_rabbit_50_129698, face_dial_rabbit_dial_img_50_129698_group[(distance / 1) % 10]);
	lv_img_set_src(face_dial_rabbit_51_129698, face_dial_rabbit_dial_img_50_129698_group[(distance / 10) % 10]);
	lv_img_set_src(face_dial_rabbit_52_129698, face_dial_rabbit_dial_img_50_129698_group[(distance / 100) % 10]);
	lv_img_set_src(face_dial_rabbit_58_129698, face_dial_rabbit_dial_img_50_129698_group[(steps / 1) % 10]);
	lv_img_set_src(face_dial_rabbit_59_129698, face_dial_rabbit_dial_img_50_129698_group[(steps / 10) % 10]);
	lv_img_set_src(face_dial_rabbit_60_129698, face_dial_rabbit_dial_img_50_129698_group[(steps / 100) % 10]);
	lv_img_set_src(face_dial_rabbit_61_129698, face_dial_rabbit_dial_img_50_129698_group[(steps / 1000) % 10]);
	lv_img_set_src(face_dial_rabbit_62_129698, face_dial_rabbit_dial_img_50_129698_group[(steps / 10000) % 10]);

#endif
}

void update_health_dial_rabbit(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_RABBIT
    if (!face_dial_rabbit)
    {
        return;
    }
	lv_img_set_src(face_dial_rabbit_45_127508, face_dial_rabbit_dial_img_45_127508_group[(bpm / 1) % 10]);
	lv_img_set_src(face_dial_rabbit_46_127508, face_dial_rabbit_dial_img_45_127508_group[(bpm / 10) % 10]);
	lv_img_set_src(face_dial_rabbit_47_127508, face_dial_rabbit_dial_img_45_127508_group[(bpm / 100) % 10]);

#endif
}

void update_all_dial_rabbit(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_RABBIT
    update_time_dial_rabbit(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_rabbit(temp, icon);
    update_status_dial_rabbit(battery, connection);
    update_activity_dial_rabbit(steps, distance, kcal);
    update_health_dial_rabbit(bpm, oxygen);
#endif
}

void update_check_dial_rabbit(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_RABBIT
    if (root != face_dial_rabbit)
    {
        return;
    }
    update_time_dial_rabbit(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_rabbit(temp, icon);
    update_status_dial_rabbit(battery, connection);
    update_activity_dial_rabbit(steps, distance, kcal);
    update_health_dial_rabbit(bpm, oxygen);
#endif
}


