
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_ASTRONAUT3

#include "../dial_astronaut3.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_dial_astronaut3_dial_img_40_41863_data_0[] = {
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    };
        


const lv_img_dsc_t face_dial_astronaut3_dial_img_40_41863_0 = {
    .header.always_zero = 0,
    .header.w = 6,
    .header.h = 2,
    .data_size = sizeof(face_dial_astronaut3_dial_img_40_41863_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_dial_astronaut3_dial_img_40_41863_data_0};

    