
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ANALOG_81

#ifndef _FACE_ANALOG_81_H
#define _FACE_ANALOG_81_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

// #define ENABLE_FACE_ANALOG_81 // (analog 81) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_ANALOG_81
    extern lv_obj_t *face_analog_81;
	extern lv_obj_t *face_analog_81_0_2808;
	extern lv_obj_t *face_analog_81_1_1124;
	extern lv_obj_t *face_analog_81_2_1124;
	extern lv_obj_t *face_analog_81_3_1124;
	extern lv_obj_t *face_analog_81_4_1124;
	extern lv_obj_t *face_analog_81_5_1124;
	extern lv_obj_t *face_analog_81_6_1124;
	extern lv_obj_t *face_analog_81_7_1124;
	extern lv_obj_t *face_analog_81_8_72438;
	extern lv_obj_t *face_analog_81_24_137120;
	extern lv_obj_t *face_analog_81_40_226768;


	LV_IMG_DECLARE(face_analog_81_dial_img_0_2808_0);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_0);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_1);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_2);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_3);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_4);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_5);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_6);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_7);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_8);
	LV_IMG_DECLARE(face_analog_81_dial_img_1_1124_9);
	LV_IMG_DECLARE(face_analog_81_dial_img_8_72438_0);
	LV_IMG_DECLARE(face_analog_81_dial_img_24_137120_0);
	LV_IMG_DECLARE(face_analog_81_dial_img_40_226768_0);
	LV_IMG_DECLARE(face_analog_81_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_analog_81(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **));
    void update_time_analog_81(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_analog_81(int temp, int icon);
    void update_status_analog_81(int battery, bool connection);
    void update_activity_analog_81(int steps, int distance, int kcal);
    void update_health_analog_81(int bpm, int oxygen);
    void update_all_analog_81(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_analog_81(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
