
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: ANALOG_81

#include "analog_81.h"

#ifdef ENABLE_FACE_ANALOG_81

lv_obj_t *face_analog_81;
lv_obj_t *face_analog_81_0_2808;
lv_obj_t *face_analog_81_1_1124;
lv_obj_t *face_analog_81_2_1124;
lv_obj_t *face_analog_81_3_1124;
lv_obj_t *face_analog_81_4_1124;
lv_obj_t *face_analog_81_5_1124;
lv_obj_t *face_analog_81_6_1124;
lv_obj_t *face_analog_81_7_1124;
lv_obj_t *face_analog_81_8_72438;
lv_obj_t *face_analog_81_24_137120;
lv_obj_t *face_analog_81_40_226768;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_analog_81_dial_img_1_1124_group[] = {
	&face_analog_81_dial_img_1_1124_0,
	&face_analog_81_dial_img_1_1124_1,
	&face_analog_81_dial_img_1_1124_2,
	&face_analog_81_dial_img_1_1124_3,
	&face_analog_81_dial_img_1_1124_4,
	&face_analog_81_dial_img_1_1124_5,
	&face_analog_81_dial_img_1_1124_6,
	&face_analog_81_dial_img_1_1124_7,
	&face_analog_81_dial_img_1_1124_8,
	&face_analog_81_dial_img_1_1124_9,
};


#endif

void init_face_analog_81(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_ANALOG_81
    face_analog_81 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_analog_81, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_analog_81, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_analog_81, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_analog_81, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_analog_81, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_analog_81, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_analog_81, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_analog_81, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_analog_81, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_analog_81_0_2808 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_0_2808, &face_analog_81_dial_img_0_2808_0);
    lv_obj_set_width(face_analog_81_0_2808, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_0_2808, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_0_2808, 0);
    lv_obj_set_y(face_analog_81_0_2808, 0);
    lv_obj_add_flag(face_analog_81_0_2808, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_0_2808, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_81_1_1124 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_1_1124, &face_analog_81_dial_img_1_1124_0);
    lv_obj_set_width(face_analog_81_1_1124, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_1_1124, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_1_1124, 126);
    lv_obj_set_y(face_analog_81_1_1124, 199);
    lv_obj_add_flag(face_analog_81_1_1124, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_1_1124, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_81_2_1124 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_2_1124, &face_analog_81_dial_img_1_1124_0);
    lv_obj_set_width(face_analog_81_2_1124, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_2_1124, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_2_1124, 115);
    lv_obj_set_y(face_analog_81_2_1124, 199);
    lv_obj_add_flag(face_analog_81_2_1124, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_2_1124, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_81_3_1124 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_3_1124, &face_analog_81_dial_img_1_1124_0);
    lv_obj_set_width(face_analog_81_3_1124, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_3_1124, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_3_1124, 104);
    lv_obj_set_y(face_analog_81_3_1124, 199);
    lv_obj_add_flag(face_analog_81_3_1124, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_3_1124, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_81_4_1124 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_4_1124, &face_analog_81_dial_img_1_1124_0);
    lv_obj_set_width(face_analog_81_4_1124, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_4_1124, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_4_1124, 133);
    lv_obj_set_y(face_analog_81_4_1124, 88);
    lv_obj_add_flag(face_analog_81_4_1124, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_4_1124, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_81_5_1124 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_5_1124, &face_analog_81_dial_img_1_1124_0);
    lv_obj_set_width(face_analog_81_5_1124, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_5_1124, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_5_1124, 122);
    lv_obj_set_y(face_analog_81_5_1124, 88);
    lv_obj_add_flag(face_analog_81_5_1124, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_5_1124, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_81_6_1124 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_6_1124, &face_analog_81_dial_img_1_1124_0);
    lv_obj_set_width(face_analog_81_6_1124, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_6_1124, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_6_1124, 111);
    lv_obj_set_y(face_analog_81_6_1124, 88);
    lv_obj_add_flag(face_analog_81_6_1124, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_6_1124, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_81_7_1124 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_7_1124, &face_analog_81_dial_img_1_1124_0);
    lv_obj_set_width(face_analog_81_7_1124, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_7_1124, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_7_1124, 100);
    lv_obj_set_y(face_analog_81_7_1124, 88);
    lv_obj_add_flag(face_analog_81_7_1124, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_7_1124, LV_OBJ_FLAG_SCROLLABLE );

    face_analog_81_8_72438 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_8_72438, &face_analog_81_dial_img_8_72438_0);
    lv_obj_set_width(face_analog_81_8_72438, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_8_72438, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_8_72438, 113);
    lv_obj_set_y(face_analog_81_8_72438, 55);
    lv_obj_add_flag(face_analog_81_8_72438, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_8_72438, LV_OBJ_FLAG_SCROLLABLE );
	lv_img_set_pivot(face_analog_81_8_72438, 7, 89);

    face_analog_81_24_137120 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_24_137120, &face_analog_81_dial_img_24_137120_0);
    lv_obj_set_width(face_analog_81_24_137120, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_24_137120, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_24_137120, 113);
    lv_obj_set_y(face_analog_81_24_137120, 31);
    lv_obj_add_flag(face_analog_81_24_137120, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_24_137120, LV_OBJ_FLAG_SCROLLABLE );
	lv_img_set_pivot(face_analog_81_24_137120, 7, 113);

    face_analog_81_40_226768 = lv_img_create(face_analog_81);
    lv_img_set_src(face_analog_81_40_226768, &face_analog_81_dial_img_40_226768_0);
    lv_obj_set_width(face_analog_81_40_226768, LV_SIZE_CONTENT);
    lv_obj_set_height(face_analog_81_40_226768, LV_SIZE_CONTENT);
    lv_obj_set_x(face_analog_81_40_226768, 107);
    lv_obj_set_y(face_analog_81_40_226768, 24);
    lv_obj_add_flag(face_analog_81_40_226768, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_analog_81_40_226768, LV_OBJ_FLAG_SCROLLABLE );
	lv_img_set_pivot(face_analog_81_40_226768, 13, 120);


    callback("analog 81", &face_analog_81_dial_img_preview_0, &face_analog_81);

#endif
}

void update_time_analog_81(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_ANALOG_81
    if (!face_analog_81)
    {
        return;
    }
	lv_img_set_angle(face_analog_81_8_72438, hour * 300 + (minute * 5));
	lv_img_set_angle(face_analog_81_24_137120, minute * 60);
	lv_img_set_angle(face_analog_81_40_226768, second * 60);

#endif
}

void update_weather_analog_81(int temp, int icon)
{
#ifdef ENABLE_FACE_ANALOG_81
    if (!face_analog_81)
    {
        return;
    }

#endif
}

void update_status_analog_81(int battery, bool connection){
#ifdef ENABLE_FACE_ANALOG_81
    if (!face_analog_81)
    {
        return;
    }

#endif
}

void update_activity_analog_81(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_ANALOG_81
    if (!face_analog_81)
    {
        return;
    }
	lv_img_set_src(face_analog_81_4_1124, face_analog_81_dial_img_1_1124_group[(kcal / 1) % 10]);
	lv_img_set_src(face_analog_81_5_1124, face_analog_81_dial_img_1_1124_group[(kcal / 10) % 10]);
	lv_img_set_src(face_analog_81_6_1124, face_analog_81_dial_img_1_1124_group[(kcal / 100) % 10]);
	lv_img_set_src(face_analog_81_7_1124, face_analog_81_dial_img_1_1124_group[(kcal / 1000) % 10]);

#endif
}

void update_health_analog_81(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_81
    if (!face_analog_81)
    {
        return;
    }
	lv_img_set_src(face_analog_81_1_1124, face_analog_81_dial_img_1_1124_group[(bpm / 1) % 10]);
	lv_img_set_src(face_analog_81_2_1124, face_analog_81_dial_img_1_1124_group[(bpm / 10) % 10]);
	lv_img_set_src(face_analog_81_3_1124, face_analog_81_dial_img_1_1124_group[(bpm / 100) % 10]);

#endif
}

void update_all_analog_81(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_81
    update_time_analog_81(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_analog_81(temp, icon);
    update_status_analog_81(battery, connection);
    update_activity_analog_81(steps, distance, kcal);
    update_health_analog_81(bpm, oxygen);
#endif
}

void update_check_analog_81(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_ANALOG_81
    if (root != face_analog_81)
    {
        return;
    }
    update_time_analog_81(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_analog_81(temp, icon);
    update_status_analog_81(battery, connection);
    update_activity_analog_81(steps, distance, kcal);
    update_health_analog_81(bpm, oxygen);
#endif
}


