
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_DOG

#include "dial_dog.h"

#ifdef ENABLE_FACE_DIAL_DOG

lv_obj_t *face_dial_dog;
lv_obj_t *face_dial_dog_0_1625;
lv_obj_t *face_dial_dog_1_72547;
lv_obj_t *face_dial_dog_3_174841;
lv_obj_t *face_dial_dog_5_174485;
lv_obj_t *face_dial_dog_6_71253;
lv_obj_t *face_dial_dog_7_71253;
lv_obj_t *face_dial_dog_8_71253;
lv_obj_t *face_dial_dog_9_174282;
lv_obj_t *face_dial_dog_10_71253;
lv_obj_t *face_dial_dog_11_71253;
lv_obj_t *face_dial_dog_12_71253;
lv_obj_t *face_dial_dog_13_163051;
lv_obj_t *face_dial_dog_14_71253;
lv_obj_t *face_dial_dog_15_71253;
lv_obj_t *face_dial_dog_16_71253;
lv_obj_t *face_dial_dog_17_71253;
lv_obj_t *face_dial_dog_18_71253;
lv_obj_t *face_dial_dog_19_71253;
lv_obj_t *face_dial_dog_20_71253;
lv_obj_t *face_dial_dog_21_71253;
lv_obj_t *face_dial_dog_22_71253;
lv_obj_t *face_dial_dog_23_71253;
lv_obj_t *face_dial_dog_24_71253;
lv_obj_t *face_dial_dog_25_71253;
lv_obj_t *face_dial_dog_26_71253;
lv_obj_t *face_dial_dog_28_170072;
lv_obj_t *face_dial_dog_29_163074;
lv_obj_t *face_dial_dog_30_163074;
lv_obj_t *face_dial_dog_31_175338;
lv_obj_t *face_dial_dog_32_175484;
lv_obj_t *face_dial_dog_33_175484;
lv_obj_t *face_dial_dog_34_175484;
lv_obj_t *face_dial_dog_35_175484;
lv_obj_t *face_dial_dog_36_187118;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_dog_dial_img_1_72547_group[] = {
	&face_dial_dog_dial_img_1_72547_0,
	&face_dial_dog_dial_img_1_72547_1,
	&face_dial_dog_dial_img_1_72547_2,
	&face_dial_dog_dial_img_1_72547_3,
	&face_dial_dog_dial_img_1_72547_4,
	&face_dial_dog_dial_img_1_72547_5,
	&face_dial_dog_dial_img_1_72547_6,
	&face_dial_dog_dial_img_1_72547_7,
	&face_dial_dog_dial_img_1_72547_8,
};
const lv_img_dsc_t *face_dial_dog_dial_img_2_1128_group[] = {
	&face_dial_dog_dial_img_2_1128_0,
	&face_dial_dog_dial_img_2_1128_1,
};
const lv_img_dsc_t *face_dial_dog_dial_img_3_174841_group[] = {
	&face_dial_dog_dial_img_3_174841_0,
	&face_dial_dog_dial_img_3_174841_1,
};
const lv_img_dsc_t *face_dial_dog_dial_img_4_744_group[] = {
	&face_dial_dog_dial_img_4_744_0,
	&face_dial_dog_dial_img_4_744_1,
};
const lv_img_dsc_t *face_dial_dog_dial_img_5_174485_group[] = {
	&face_dial_dog_dial_img_5_174485_0,
	&face_dial_dog_dial_img_5_174485_1,
};
const lv_img_dsc_t *face_dial_dog_dial_img_6_71253_group[] = {
	&face_dial_dog_dial_img_6_71253_0,
	&face_dial_dog_dial_img_6_71253_1,
	&face_dial_dog_dial_img_6_71253_2,
	&face_dial_dog_dial_img_6_71253_3,
	&face_dial_dog_dial_img_6_71253_4,
	&face_dial_dog_dial_img_6_71253_5,
	&face_dial_dog_dial_img_6_71253_6,
	&face_dial_dog_dial_img_6_71253_7,
	&face_dial_dog_dial_img_6_71253_8,
	&face_dial_dog_dial_img_6_71253_9,
};
const lv_img_dsc_t *face_dial_dog_dial_img_27_164278_group[] = {
	&face_dial_dog_dial_img_27_164278_0,
	&face_dial_dog_dial_img_27_164278_1,
	&face_dial_dog_dial_img_27_164278_2,
	&face_dial_dog_dial_img_27_164278_3,
	&face_dial_dog_dial_img_27_164278_4,
	&face_dial_dog_dial_img_27_164278_5,
	&face_dial_dog_dial_img_27_164278_6,
	&face_dial_dog_dial_img_27_164278_7,
	&face_dial_dog_dial_img_27_164278_8,
	&face_dial_dog_dial_img_27_164278_9,
	&face_dial_dog_dial_img_27_164278_10,
	&face_dial_dog_dial_img_27_164278_11,
};
const lv_img_dsc_t *face_dial_dog_dial_img_28_170072_group[] = {
	&face_dial_dog_dial_img_28_170072_0,
	&face_dial_dog_dial_img_28_170072_1,
	&face_dial_dog_dial_img_28_170072_2,
	&face_dial_dog_dial_img_28_170072_3,
	&face_dial_dog_dial_img_28_170072_4,
	&face_dial_dog_dial_img_28_170072_5,
	&face_dial_dog_dial_img_28_170072_6,
	&face_dial_dog_dial_img_28_170072_7,
	&face_dial_dog_dial_img_28_170072_8,
	&face_dial_dog_dial_img_28_170072_9,
	&face_dial_dog_dial_img_28_170072_10,
	&face_dial_dog_dial_img_28_170072_11,
};
const lv_img_dsc_t *face_dial_dog_dial_img_29_163074_group[] = {
	&face_dial_dog_dial_img_29_163074_0,
	&face_dial_dog_dial_img_29_163074_1,
	&face_dial_dog_dial_img_29_163074_2,
	&face_dial_dog_dial_img_29_163074_3,
	&face_dial_dog_dial_img_29_163074_4,
	&face_dial_dog_dial_img_29_163074_5,
	&face_dial_dog_dial_img_29_163074_6,
	&face_dial_dog_dial_img_29_163074_7,
	&face_dial_dog_dial_img_29_163074_8,
	&face_dial_dog_dial_img_29_163074_9,
};
const lv_img_dsc_t *face_dial_dog_dial_img_32_175484_group[] = {
	&face_dial_dog_dial_img_32_175484_0,
	&face_dial_dog_dial_img_32_175484_1,
	&face_dial_dog_dial_img_32_175484_2,
	&face_dial_dog_dial_img_32_175484_3,
	&face_dial_dog_dial_img_32_175484_4,
	&face_dial_dog_dial_img_32_175484_5,
	&face_dial_dog_dial_img_32_175484_6,
	&face_dial_dog_dial_img_32_175484_7,
	&face_dial_dog_dial_img_32_175484_8,
	&face_dial_dog_dial_img_32_175484_9,
};
const lv_img_dsc_t *face_dial_dog_dial_img_36_187118_group[] = {
	&face_dial_dog_dial_img_36_187118_0,
	&face_dial_dog_dial_img_36_187118_1,
	&face_dial_dog_dial_img_36_187118_2,
	&face_dial_dog_dial_img_36_187118_3,
	&face_dial_dog_dial_img_36_187118_4,
	&face_dial_dog_dial_img_36_187118_5,
	&face_dial_dog_dial_img_36_187118_6,
};


#endif

void init_face_dial_dog(void (*callback)(const char *name, const lv_img_dsc_t *preview, lv_obj_t **watchface, int anim_img_num, lv_obj_t *anim_img, const lv_img_dsc_t **anim_img_group)){
#ifdef ENABLE_FACE_DIAL_DOG
    face_dial_dog = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_dog, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_dog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_dog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_dog, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_dog, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_dog, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_dog, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_dog, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_dog, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_dog_0_1625 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_0_1625, &face_dial_dog_dial_img_0_1625_0);
    lv_obj_set_width(face_dial_dog_0_1625, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_0_1625, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_0_1625, 0);
    lv_obj_set_y(face_dial_dog_0_1625, 0);
    lv_obj_add_flag(face_dial_dog_0_1625, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_0_1625, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_1_72547 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_1_72547, &face_dial_dog_dial_img_1_72547_0);
    lv_obj_set_width(face_dial_dog_1_72547, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_1_72547, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_1_72547, 10);
    lv_obj_set_y(face_dial_dog_1_72547, 9);
    lv_obj_add_flag(face_dial_dog_1_72547, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_1_72547, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_3_174841 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_3_174841, &face_dial_dog_dial_img_3_174841_0);
    lv_obj_set_width(face_dial_dog_3_174841, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_3_174841, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_3_174841, 201);
    lv_obj_set_y(face_dial_dog_3_174841, 137);
    lv_obj_add_flag(face_dial_dog_3_174841, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_3_174841, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_5_174485 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_5_174485, &face_dial_dog_dial_img_5_174485_0);
    lv_obj_set_width(face_dial_dog_5_174485, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_5_174485, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_5_174485, 201);
    lv_obj_set_y(face_dial_dog_5_174485, 137);
    lv_obj_add_flag(face_dial_dog_5_174485, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_5_174485, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_6_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_6_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_6_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_6_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_6_71253, 161);
    lv_obj_set_y(face_dial_dog_6_71253, 81);
    lv_obj_add_flag(face_dial_dog_6_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_6_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_7_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_7_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_7_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_7_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_7_71253, 151);
    lv_obj_set_y(face_dial_dog_7_71253, 81);
    lv_obj_add_flag(face_dial_dog_7_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_7_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_8_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_8_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_8_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_8_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_8_71253, 141);
    lv_obj_set_y(face_dial_dog_8_71253, 81);
    lv_obj_add_flag(face_dial_dog_8_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_8_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_9_174282 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_9_174282, &face_dial_dog_dial_img_9_174282_0);
    lv_obj_set_width(face_dial_dog_9_174282, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_9_174282, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_9_174282, 172);
    lv_obj_set_y(face_dial_dog_9_174282, 82);
    lv_obj_add_flag(face_dial_dog_9_174282, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_9_174282, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_10_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_10_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_10_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_10_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_10_71253, 182);
    lv_obj_set_y(face_dial_dog_10_71253, 13);
    lv_obj_add_flag(face_dial_dog_10_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_10_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_11_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_11_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_11_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_11_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_11_71253, 172);
    lv_obj_set_y(face_dial_dog_11_71253, 13);
    lv_obj_add_flag(face_dial_dog_11_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_11_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_12_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_12_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_12_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_12_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_12_71253, 162);
    lv_obj_set_y(face_dial_dog_12_71253, 13);
    lv_obj_add_flag(face_dial_dog_12_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_12_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_13_163051 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_13_163051, &face_dial_dog_dial_img_13_163051_0);
    lv_obj_set_width(face_dial_dog_13_163051, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_13_163051, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_13_163051, 147);
    lv_obj_set_y(face_dial_dog_13_163051, 59);
    lv_obj_add_flag(face_dial_dog_13_163051, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_13_163051, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_14_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_14_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_14_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_14_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_14_71253, 161);
    lv_obj_set_y(face_dial_dog_14_71253, 49);
    lv_obj_add_flag(face_dial_dog_14_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_14_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_15_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_15_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_15_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_15_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_15_71253, 151);
    lv_obj_set_y(face_dial_dog_15_71253, 49);
    lv_obj_add_flag(face_dial_dog_15_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_15_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_16_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_16_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_16_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_16_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_16_71253, 135);
    lv_obj_set_y(face_dial_dog_16_71253, 49);
    lv_obj_add_flag(face_dial_dog_16_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_16_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_17_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_17_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_17_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_17_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_17_71253, 124);
    lv_obj_set_y(face_dial_dog_17_71253, 49);
    lv_obj_add_flag(face_dial_dog_17_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_17_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_18_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_18_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_18_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_18_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_18_71253, 205);
    lv_obj_set_y(face_dial_dog_18_71253, 238);
    lv_obj_add_flag(face_dial_dog_18_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_18_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_19_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_19_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_19_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_19_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_19_71253, 195);
    lv_obj_set_y(face_dial_dog_19_71253, 238);
    lv_obj_add_flag(face_dial_dog_19_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_19_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_20_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_20_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_20_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_20_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_20_71253, 185);
    lv_obj_set_y(face_dial_dog_20_71253, 238);
    lv_obj_add_flag(face_dial_dog_20_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_20_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_21_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_21_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_21_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_21_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_21_71253, 175);
    lv_obj_set_y(face_dial_dog_21_71253, 238);
    lv_obj_add_flag(face_dial_dog_21_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_21_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_22_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_22_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_22_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_22_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_22_71253, 69);
    lv_obj_set_y(face_dial_dog_22_71253, 238);
    lv_obj_add_flag(face_dial_dog_22_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_22_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_23_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_23_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_23_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_23_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_23_71253, 59);
    lv_obj_set_y(face_dial_dog_23_71253, 238);
    lv_obj_add_flag(face_dial_dog_23_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_23_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_24_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_24_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_24_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_24_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_24_71253, 49);
    lv_obj_set_y(face_dial_dog_24_71253, 238);
    lv_obj_add_flag(face_dial_dog_24_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_24_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_25_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_25_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_25_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_25_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_25_71253, 39);
    lv_obj_set_y(face_dial_dog_25_71253, 238);
    lv_obj_add_flag(face_dial_dog_25_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_25_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_26_71253 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_26_71253, &face_dial_dog_dial_img_6_71253_0);
    lv_obj_set_width(face_dial_dog_26_71253, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_26_71253, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_26_71253, 29);
    lv_obj_set_y(face_dial_dog_26_71253, 238);
    lv_obj_add_flag(face_dial_dog_26_71253, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_26_71253, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_28_170072 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_28_170072, &face_dial_dog_dial_img_28_170072_0);
    lv_obj_set_width(face_dial_dog_28_170072, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_28_170072, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_28_170072, 14);
    lv_obj_set_y(face_dial_dog_28_170072, 135);
    lv_obj_add_flag(face_dial_dog_28_170072, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_28_170072, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_29_163074 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_29_163074, &face_dial_dog_dial_img_29_163074_0);
    lv_obj_set_width(face_dial_dog_29_163074, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_29_163074, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_29_163074, 29);
    lv_obj_set_y(face_dial_dog_29_163074, 157);
    lv_obj_add_flag(face_dial_dog_29_163074, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_29_163074, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_30_163074 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_30_163074, &face_dial_dog_dial_img_29_163074_0);
    lv_obj_set_width(face_dial_dog_30_163074, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_30_163074, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_30_163074, 18);
    lv_obj_set_y(face_dial_dog_30_163074, 157);
    lv_obj_add_flag(face_dial_dog_30_163074, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_30_163074, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_31_175338 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_31_175338, &face_dial_dog_dial_img_31_175338_0);
    lv_obj_set_width(face_dial_dog_31_175338, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_31_175338, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_31_175338, 119);
    lv_obj_set_y(face_dial_dog_31_175338, 145);
    lv_obj_add_flag(face_dial_dog_31_175338, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_31_175338, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_32_175484 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_32_175484, &face_dial_dog_dial_img_32_175484_0);
    lv_obj_set_width(face_dial_dog_32_175484, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_32_175484, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_32_175484, 83);
    lv_obj_set_y(face_dial_dog_32_175484, 135);
    lv_obj_add_flag(face_dial_dog_32_175484, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_32_175484, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_33_175484 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_33_175484, &face_dial_dog_dial_img_32_175484_0);
    lv_obj_set_width(face_dial_dog_33_175484, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_33_175484, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_33_175484, 49);
    lv_obj_set_y(face_dial_dog_33_175484, 135);
    lv_obj_add_flag(face_dial_dog_33_175484, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_33_175484, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_34_175484 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_34_175484, &face_dial_dog_dial_img_32_175484_0);
    lv_obj_set_width(face_dial_dog_34_175484, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_34_175484, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_34_175484, 169);
    lv_obj_set_y(face_dial_dog_34_175484, 135);
    lv_obj_add_flag(face_dial_dog_34_175484, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_34_175484, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_35_175484 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_35_175484, &face_dial_dog_dial_img_32_175484_0);
    lv_obj_set_width(face_dial_dog_35_175484, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_35_175484, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_35_175484, 135);
    lv_obj_set_y(face_dial_dog_35_175484, 135);
    lv_obj_add_flag(face_dial_dog_35_175484, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_35_175484, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_dog_36_187118 = lv_img_create(face_dial_dog);
    lv_img_set_src(face_dial_dog_36_187118, &face_dial_dog_dial_img_36_187118_0);
    lv_obj_set_width(face_dial_dog_36_187118, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_dog_36_187118, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_dog_36_187118, 0);
    lv_obj_set_y(face_dial_dog_36_187118, 200);
    lv_obj_add_flag(face_dial_dog_36_187118, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_dog_36_187118, LV_OBJ_FLAG_SCROLLABLE );

    int anim_img_num = sizeof(face_dial_dog_dial_img_1_72547_group) / sizeof(face_dial_dog_dial_img_1_72547_group[0]);
    callback("dial dog", &face_dial_dog_dial_img_preview_0, &face_dial_dog, anim_img_num, face_dial_dog_1_72547, face_dial_dog_dial_img_1_72547_group);

#endif
}

void update_time_dial_dog(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_DOG
    if (!face_dial_dog)
    {
        return;
    }
	if (mode)
	{
		lv_obj_add_flag(face_dial_dog_3_174841, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_dog_3_174841, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_dog_3_174841, face_dial_dog_dial_img_3_174841_group[(am ? 0 : 1) % 2]);
	if (mode)
	{
		lv_obj_add_flag(face_dial_dog_5_174485, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_dog_5_174485, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_dog_5_174485, face_dial_dog_dial_img_5_174485_group[(am ? 0 : 1) % 2]);
	lv_img_set_src(face_dial_dog_28_170072, face_dial_dog_dial_img_28_170072_group[((month - 1) / 1) % 12]);
	lv_img_set_src(face_dial_dog_29_163074, face_dial_dog_dial_img_29_163074_group[(day / 1) % 10]);
	lv_img_set_src(face_dial_dog_30_163074, face_dial_dog_dial_img_29_163074_group[(day / 10) % 10]);
	lv_img_set_src(face_dial_dog_32_175484, face_dial_dog_dial_img_32_175484_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_dog_33_175484, face_dial_dog_dial_img_32_175484_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_dog_34_175484, face_dial_dog_dial_img_32_175484_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_dog_35_175484, face_dial_dog_dial_img_32_175484_group[(minute / 10) % 10]);
	lv_img_set_src(face_dial_dog_36_187118, face_dial_dog_dial_img_36_187118_group[((weekday + 6) / 1) % 7]);

#endif
}

void update_weather_dial_dog(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_DOG
    if (!face_dial_dog)
    {
        return;
    }

#endif
}

void update_status_dial_dog(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_DOG
    if (!face_dial_dog)
    {
        return;
    }
	lv_img_set_src(face_dial_dog_6_71253, face_dial_dog_dial_img_6_71253_group[(battery / 1) % 10]);
	lv_img_set_src(face_dial_dog_7_71253, face_dial_dog_dial_img_6_71253_group[(battery / 10) % 10]);
	lv_img_set_src(face_dial_dog_8_71253, face_dial_dog_dial_img_6_71253_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_dial_dog_8_71253, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_dog_8_71253, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_dial_dog(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_DOG
    if (!face_dial_dog)
    {
        return;
    }
	lv_img_set_src(face_dial_dog_14_71253, face_dial_dog_dial_img_6_71253_group[(distance / 1) % 10]);
	lv_img_set_src(face_dial_dog_15_71253, face_dial_dog_dial_img_6_71253_group[(distance / 10) % 10]);
	lv_img_set_src(face_dial_dog_16_71253, face_dial_dog_dial_img_6_71253_group[(distance / 100) % 10]);
	lv_img_set_src(face_dial_dog_17_71253, face_dial_dog_dial_img_6_71253_group[(distance / 1000) % 10]);
	lv_img_set_src(face_dial_dog_18_71253, face_dial_dog_dial_img_6_71253_group[(kcal / 1) % 10]);
	lv_img_set_src(face_dial_dog_19_71253, face_dial_dog_dial_img_6_71253_group[(kcal / 10) % 10]);
	lv_img_set_src(face_dial_dog_20_71253, face_dial_dog_dial_img_6_71253_group[(kcal / 100) % 10]);
	lv_img_set_src(face_dial_dog_21_71253, face_dial_dog_dial_img_6_71253_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_dial_dog_22_71253, face_dial_dog_dial_img_6_71253_group[(steps / 1) % 10]);
	lv_img_set_src(face_dial_dog_23_71253, face_dial_dog_dial_img_6_71253_group[(steps / 10) % 10]);
	lv_img_set_src(face_dial_dog_24_71253, face_dial_dog_dial_img_6_71253_group[(steps / 100) % 10]);
	lv_img_set_src(face_dial_dog_25_71253, face_dial_dog_dial_img_6_71253_group[(steps / 1000) % 10]);
	lv_img_set_src(face_dial_dog_26_71253, face_dial_dog_dial_img_6_71253_group[(steps / 10000) % 10]);

#endif
}

void update_health_dial_dog(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_DOG
    if (!face_dial_dog)
    {
        return;
    }
	lv_img_set_src(face_dial_dog_10_71253, face_dial_dog_dial_img_6_71253_group[(bpm / 1) % 10]);
	lv_img_set_src(face_dial_dog_11_71253, face_dial_dog_dial_img_6_71253_group[(bpm / 10) % 10]);
	lv_img_set_src(face_dial_dog_12_71253, face_dial_dog_dial_img_6_71253_group[(bpm / 100) % 10]);

#endif
}

void update_all_dial_dog(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_DOG
    update_time_dial_dog(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_dog(temp, icon);
    update_status_dial_dog(battery, connection);
    update_activity_dial_dog(steps, distance, kcal);
    update_health_dial_dog(bpm, oxygen);
#endif
}

void update_check_dial_dog(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_DOG
    if (root != face_dial_dog)
    {
        return;
    }
    update_time_dial_dog(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_dog(temp, icon);
    update_status_dial_dog(battery, connection);
    update_activity_dial_dog(steps, distance, kcal);
    update_health_dial_dog(bpm, oxygen);
#endif
}


