
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_DOG

#ifndef _FACE_DIAL_DOG_H
#define _FACE_DIAL_DOG_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

// #define ENABLE_FACE_DIAL_DOG // (dial dog) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_DIAL_DOG
    extern lv_obj_t *face_dial_dog;
	extern lv_obj_t *face_dial_dog_0_1625;
	extern lv_obj_t *face_dial_dog_1_72547;
	extern lv_obj_t *face_dial_dog_3_174841;
	extern lv_obj_t *face_dial_dog_5_174485;
	extern lv_obj_t *face_dial_dog_6_71253;
	extern lv_obj_t *face_dial_dog_7_71253;
	extern lv_obj_t *face_dial_dog_8_71253;
	extern lv_obj_t *face_dial_dog_9_174282;
	extern lv_obj_t *face_dial_dog_10_71253;
	extern lv_obj_t *face_dial_dog_11_71253;
	extern lv_obj_t *face_dial_dog_12_71253;
	extern lv_obj_t *face_dial_dog_13_163051;
	extern lv_obj_t *face_dial_dog_14_71253;
	extern lv_obj_t *face_dial_dog_15_71253;
	extern lv_obj_t *face_dial_dog_16_71253;
	extern lv_obj_t *face_dial_dog_17_71253;
	extern lv_obj_t *face_dial_dog_18_71253;
	extern lv_obj_t *face_dial_dog_19_71253;
	extern lv_obj_t *face_dial_dog_20_71253;
	extern lv_obj_t *face_dial_dog_21_71253;
	extern lv_obj_t *face_dial_dog_22_71253;
	extern lv_obj_t *face_dial_dog_23_71253;
	extern lv_obj_t *face_dial_dog_24_71253;
	extern lv_obj_t *face_dial_dog_25_71253;
	extern lv_obj_t *face_dial_dog_26_71253;
	extern lv_obj_t *face_dial_dog_28_170072;
	extern lv_obj_t *face_dial_dog_29_163074;
	extern lv_obj_t *face_dial_dog_30_163074;
	extern lv_obj_t *face_dial_dog_31_175338;
	extern lv_obj_t *face_dial_dog_32_175484;
	extern lv_obj_t *face_dial_dog_33_175484;
	extern lv_obj_t *face_dial_dog_34_175484;
	extern lv_obj_t *face_dial_dog_35_175484;
	extern lv_obj_t *face_dial_dog_36_187118;


	LV_IMG_DECLARE(face_dial_dog_dial_img_0_1625_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_2);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_3);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_4);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_5);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_6);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_7);
	LV_IMG_DECLARE(face_dial_dog_dial_img_1_72547_8);
	LV_IMG_DECLARE(face_dial_dog_dial_img_2_1128_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_2_1128_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_3_174841_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_3_174841_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_4_744_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_4_744_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_5_174485_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_5_174485_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_2);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_3);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_4);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_5);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_6);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_7);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_8);
	LV_IMG_DECLARE(face_dial_dog_dial_img_6_71253_9);
	LV_IMG_DECLARE(face_dial_dog_dial_img_9_174282_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_13_163051_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_2);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_3);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_4);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_5);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_6);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_7);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_8);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_9);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_10);
	LV_IMG_DECLARE(face_dial_dog_dial_img_27_164278_11);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_2);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_3);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_4);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_5);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_6);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_7);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_8);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_9);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_10);
	LV_IMG_DECLARE(face_dial_dog_dial_img_28_170072_11);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_2);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_3);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_4);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_5);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_6);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_7);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_8);
	LV_IMG_DECLARE(face_dial_dog_dial_img_29_163074_9);
	LV_IMG_DECLARE(face_dial_dog_dial_img_31_175338_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_2);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_3);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_4);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_5);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_6);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_7);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_8);
	LV_IMG_DECLARE(face_dial_dog_dial_img_32_175484_9);
	LV_IMG_DECLARE(face_dial_dog_dial_img_36_187118_0);
	LV_IMG_DECLARE(face_dial_dog_dial_img_36_187118_1);
	LV_IMG_DECLARE(face_dial_dog_dial_img_36_187118_2);
	LV_IMG_DECLARE(face_dial_dog_dial_img_36_187118_3);
	LV_IMG_DECLARE(face_dial_dog_dial_img_36_187118_4);
	LV_IMG_DECLARE(face_dial_dog_dial_img_36_187118_5);
	LV_IMG_DECLARE(face_dial_dog_dial_img_36_187118_6);
	LV_IMG_DECLARE(face_dial_dog_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_dial_dog(void (*callback)(const char *name, const lv_img_dsc_t *preview, lv_obj_t **watchface, int anim_img_num, lv_obj_t *anim_img, const lv_img_dsc_t **anim_img_group));
    void update_time_dial_dog(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_dial_dog(int temp, int icon);
    void update_status_dial_dog(int battery, bool connection);
    void update_activity_dial_dog(int steps, int distance, int kcal);
    void update_health_dial_dog(int bpm, int oxygen);
    void update_all_dial_dog(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_dial_dog(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
