
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_DOG

#include "../dial_dog.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_dial_dog_dial_img_13_163051_data_0[] = {
	0x84,0x30,0xFF,0xD6,0xBA,0xFF,0x52,0xAA,0xFF,0xA5,0x14,0xFF,0xFF,0xFF,0xFF,0x63,0x2C,0xFF,0x63,0x2C,0xFF,0xA5,0x14,0xFF,0x39,0xE7,0xFF,
    };
        


const lv_img_dsc_t face_dial_dog_dial_img_13_163051_0 = {
    .header.always_zero = 0,
    .header.w = 3,
    .header.h = 3,
    .data_size = sizeof(face_dial_dog_dial_img_13_163051_data_0),
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data = face_dial_dog_dial_img_13_163051_data_0};

    