
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_BLACKBOARD

#include "dial_blackboard.h"

#ifdef ENABLE_FACE_DIAL_BLACKBOARD

lv_obj_t *face_dial_blackboard;
lv_obj_t *face_dial_blackboard_0_4206;
lv_obj_t *face_dial_blackboard_2_88113;
lv_obj_t *face_dial_blackboard_12_90735;
lv_obj_t *face_dial_blackboard_14_96385;
lv_obj_t *face_dial_blackboard_15_924;
lv_obj_t *face_dial_blackboard_16_88469;
lv_obj_t *face_dial_blackboard_17_88469;
lv_obj_t *face_dial_blackboard_18_88469;
lv_obj_t *face_dial_blackboard_19_4100;
lv_obj_t *face_dial_blackboard_20_89223;
lv_obj_t *face_dial_blackboard_21_89223;
lv_obj_t *face_dial_blackboard_22_88469;
lv_obj_t *face_dial_blackboard_23_88469;
lv_obj_t *face_dial_blackboard_24_88469;
lv_obj_t *face_dial_blackboard_25_88469;
lv_obj_t *face_dial_blackboard_26_88469;
lv_obj_t *face_dial_blackboard_27_88469;
lv_obj_t *face_dial_blackboard_28_88469;
lv_obj_t *face_dial_blackboard_29_88469;
lv_obj_t *face_dial_blackboard_30_88469;
lv_obj_t *face_dial_blackboard_31_88469;
lv_obj_t *face_dial_blackboard_32_88469;
lv_obj_t *face_dial_blackboard_33_88469;
lv_obj_t *face_dial_blackboard_34_103067;
lv_obj_t *face_dial_blackboard_35_103067;
lv_obj_t *face_dial_blackboard_36_123509;
lv_obj_t *face_dial_blackboard_37_113241;
lv_obj_t *face_dial_blackboard_38_19117;
lv_obj_t *face_dial_blackboard_39_19117;
lv_obj_t *face_dial_blackboard_40_88469;
lv_obj_t *face_dial_blackboard_41_88469;
lv_obj_t *face_dial_blackboard_42_88469;
lv_obj_t *face_dial_blackboard_43_75746;
lv_obj_t *face_dial_blackboard_44_90517;
lv_obj_t *face_dial_blackboard_45_133743;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 for watchfaces"
#endif


const lv_img_dsc_t *face_dial_blackboard_dial_img_weather[] = {
	&face_dial_blackboard_dial_img_2_88113_0,
	&face_dial_blackboard_dial_img_3_102727_0,
	&face_dial_blackboard_dial_img_4_102391_0,
	&face_dial_blackboard_dial_img_5_101837_0,
	&face_dial_blackboard_dial_img_6_101545_0,
	&face_dial_blackboard_dial_img_7_102169_0,
	&face_dial_blackboard_dial_img_8_133748_0,
	&face_dial_blackboard_dial_img_9_101001_0,
	&face_dial_blackboard_dial_img_10_101255_0,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_11_75988_group[] = {
	&face_dial_blackboard_dial_img_11_75988_0,
	&face_dial_blackboard_dial_img_11_75988_1,
	&face_dial_blackboard_dial_img_11_75988_2,
	&face_dial_blackboard_dial_img_11_75988_3,
	&face_dial_blackboard_dial_img_11_75988_4,
	&face_dial_blackboard_dial_img_11_75988_5,
	&face_dial_blackboard_dial_img_11_75988_6,
	&face_dial_blackboard_dial_img_11_75988_7,
	&face_dial_blackboard_dial_img_11_75988_8,
	&face_dial_blackboard_dial_img_11_75988_9,
	&face_dial_blackboard_dial_img_11_75988_10,
	&face_dial_blackboard_dial_img_11_75988_11,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_12_90735_group[] = {
	&face_dial_blackboard_dial_img_12_90735_0,
	&face_dial_blackboard_dial_img_12_90735_1,
	&face_dial_blackboard_dial_img_12_90735_2,
	&face_dial_blackboard_dial_img_12_90735_3,
	&face_dial_blackboard_dial_img_12_90735_4,
	&face_dial_blackboard_dial_img_12_90735_5,
	&face_dial_blackboard_dial_img_12_90735_6,
	&face_dial_blackboard_dial_img_12_90735_7,
	&face_dial_blackboard_dial_img_12_90735_8,
	&face_dial_blackboard_dial_img_12_90735_9,
	&face_dial_blackboard_dial_img_12_90735_10,
	&face_dial_blackboard_dial_img_12_90735_11,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_13_83402_group[] = {
	&face_dial_blackboard_dial_img_13_83402_0,
	&face_dial_blackboard_dial_img_13_83402_1,
	&face_dial_blackboard_dial_img_13_83402_2,
	&face_dial_blackboard_dial_img_13_83402_3,
	&face_dial_blackboard_dial_img_13_83402_4,
	&face_dial_blackboard_dial_img_13_83402_5,
	&face_dial_blackboard_dial_img_13_83402_6,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_14_96385_group[] = {
	&face_dial_blackboard_dial_img_14_96385_0,
	&face_dial_blackboard_dial_img_14_96385_1,
	&face_dial_blackboard_dial_img_14_96385_2,
	&face_dial_blackboard_dial_img_14_96385_3,
	&face_dial_blackboard_dial_img_14_96385_4,
	&face_dial_blackboard_dial_img_14_96385_5,
	&face_dial_blackboard_dial_img_14_96385_6,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_15_924_group[] = {
	&face_dial_blackboard_dial_img_15_924_0,
	&face_dial_blackboard_dial_img_15_924_1,
	&face_dial_blackboard_dial_img_15_924_2,
	&face_dial_blackboard_dial_img_15_924_3,
	&face_dial_blackboard_dial_img_15_924_4,
	&face_dial_blackboard_dial_img_15_924_5,
	&face_dial_blackboard_dial_img_15_924_6,
	&face_dial_blackboard_dial_img_15_924_7,
	&face_dial_blackboard_dial_img_15_924_8,
	&face_dial_blackboard_dial_img_15_924_9,
	&face_dial_blackboard_dial_img_15_924_10,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_16_88469_group[] = {
	&face_dial_blackboard_dial_img_16_88469_0,
	&face_dial_blackboard_dial_img_16_88469_1,
	&face_dial_blackboard_dial_img_16_88469_2,
	&face_dial_blackboard_dial_img_16_88469_3,
	&face_dial_blackboard_dial_img_16_88469_4,
	&face_dial_blackboard_dial_img_16_88469_5,
	&face_dial_blackboard_dial_img_16_88469_6,
	&face_dial_blackboard_dial_img_16_88469_7,
	&face_dial_blackboard_dial_img_16_88469_8,
	&face_dial_blackboard_dial_img_16_88469_9,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_20_89223_group[] = {
	&face_dial_blackboard_dial_img_20_89223_0,
	&face_dial_blackboard_dial_img_20_89223_1,
	&face_dial_blackboard_dial_img_20_89223_2,
	&face_dial_blackboard_dial_img_20_89223_3,
	&face_dial_blackboard_dial_img_20_89223_4,
	&face_dial_blackboard_dial_img_20_89223_5,
	&face_dial_blackboard_dial_img_20_89223_6,
	&face_dial_blackboard_dial_img_20_89223_7,
	&face_dial_blackboard_dial_img_20_89223_8,
	&face_dial_blackboard_dial_img_20_89223_9,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_34_103067_group[] = {
	&face_dial_blackboard_dial_img_34_103067_0,
	&face_dial_blackboard_dial_img_34_103067_1,
	&face_dial_blackboard_dial_img_34_103067_2,
	&face_dial_blackboard_dial_img_34_103067_3,
	&face_dial_blackboard_dial_img_34_103067_4,
	&face_dial_blackboard_dial_img_34_103067_5,
	&face_dial_blackboard_dial_img_34_103067_6,
	&face_dial_blackboard_dial_img_34_103067_7,
	&face_dial_blackboard_dial_img_34_103067_8,
	&face_dial_blackboard_dial_img_34_103067_9,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_36_123509_group[] = {
	&face_dial_blackboard_dial_img_36_123509_0,
	&face_dial_blackboard_dial_img_36_123509_1,
	&face_dial_blackboard_dial_img_36_123509_2,
	&face_dial_blackboard_dial_img_36_123509_3,
	&face_dial_blackboard_dial_img_36_123509_4,
	&face_dial_blackboard_dial_img_36_123509_5,
	&face_dial_blackboard_dial_img_36_123509_6,
	&face_dial_blackboard_dial_img_36_123509_7,
	&face_dial_blackboard_dial_img_36_123509_8,
	&face_dial_blackboard_dial_img_36_123509_9,
};
const lv_img_dsc_t *face_dial_blackboard_dial_img_37_113241_group[] = {
	&face_dial_blackboard_dial_img_37_113241_0,
	&face_dial_blackboard_dial_img_37_113241_1,
	&face_dial_blackboard_dial_img_37_113241_2,
	&face_dial_blackboard_dial_img_37_113241_3,
	&face_dial_blackboard_dial_img_37_113241_4,
	&face_dial_blackboard_dial_img_37_113241_5,
	&face_dial_blackboard_dial_img_37_113241_6,
	&face_dial_blackboard_dial_img_37_113241_7,
	&face_dial_blackboard_dial_img_37_113241_8,
	&face_dial_blackboard_dial_img_37_113241_9,
};


#endif

void init_face_dial_blackboard(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **)){
#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    face_dial_blackboard = lv_obj_create(NULL);
    lv_obj_clear_flag(face_dial_blackboard, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_dial_blackboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_dial_blackboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_dial_blackboard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_dial_blackboard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_dial_blackboard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_dial_blackboard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_dial_blackboard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_dial_blackboard, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_dial_blackboard_0_4206 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_0_4206, &face_dial_blackboard_dial_img_0_4206_0);
    lv_obj_set_width(face_dial_blackboard_0_4206, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_0_4206, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_0_4206, 0);
    lv_obj_set_y(face_dial_blackboard_0_4206, 0);
    lv_obj_add_flag(face_dial_blackboard_0_4206, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_0_4206, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_2_88113 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_2_88113, &face_dial_blackboard_dial_img_2_88113_0);
    lv_obj_set_width(face_dial_blackboard_2_88113, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_2_88113, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_2_88113, 153);
    lv_obj_set_y(face_dial_blackboard_2_88113, 9);
    lv_obj_add_flag(face_dial_blackboard_2_88113, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_2_88113, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_12_90735 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_12_90735, &face_dial_blackboard_dial_img_12_90735_0);
    lv_obj_set_width(face_dial_blackboard_12_90735, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_12_90735, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_12_90735, 97);
    lv_obj_set_y(face_dial_blackboard_12_90735, 198);
    lv_obj_add_flag(face_dial_blackboard_12_90735, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_12_90735, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_14_96385 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_14_96385, &face_dial_blackboard_dial_img_14_96385_0);
    lv_obj_set_width(face_dial_blackboard_14_96385, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_14_96385, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_14_96385, 27);
    lv_obj_set_y(face_dial_blackboard_14_96385, 168);
    lv_obj_add_flag(face_dial_blackboard_14_96385, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_14_96385, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_15_924 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_15_924, &face_dial_blackboard_dial_img_15_924_0);
    lv_obj_set_width(face_dial_blackboard_15_924, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_15_924, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_15_924, 197);
    lv_obj_set_y(face_dial_blackboard_15_924, 201);
    lv_obj_add_flag(face_dial_blackboard_15_924, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_15_924, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_16_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_16_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_16_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_16_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_16_88469, 207);
    lv_obj_set_y(face_dial_blackboard_16_88469, 216);
    lv_obj_add_flag(face_dial_blackboard_16_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_16_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_17_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_17_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_17_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_17_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_17_88469, 200);
    lv_obj_set_y(face_dial_blackboard_17_88469, 216);
    lv_obj_add_flag(face_dial_blackboard_17_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_17_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_18_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_18_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_18_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_18_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_18_88469, 194);
    lv_obj_set_y(face_dial_blackboard_18_88469, 216);
    lv_obj_add_flag(face_dial_blackboard_18_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_18_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_19_4100 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_19_4100, &face_dial_blackboard_dial_img_19_4100_0);
    lv_obj_set_width(face_dial_blackboard_19_4100, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_19_4100, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_19_4100, 214);
    lv_obj_set_y(face_dial_blackboard_19_4100, 217);
    lv_obj_add_flag(face_dial_blackboard_19_4100, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_19_4100, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_20_89223 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_20_89223, &face_dial_blackboard_dial_img_20_89223_0);
    lv_obj_set_width(face_dial_blackboard_20_89223, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_20_89223, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_20_89223, 81);
    lv_obj_set_y(face_dial_blackboard_20_89223, 171);
    lv_obj_add_flag(face_dial_blackboard_20_89223, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_20_89223, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_21_89223 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_21_89223, &face_dial_blackboard_dial_img_20_89223_0);
    lv_obj_set_width(face_dial_blackboard_21_89223, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_21_89223, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_21_89223, 71);
    lv_obj_set_y(face_dial_blackboard_21_89223, 171);
    lv_obj_add_flag(face_dial_blackboard_21_89223, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_21_89223, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_22_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_22_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_22_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_22_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_22_88469, 124);
    lv_obj_set_y(face_dial_blackboard_22_88469, 5);
    lv_obj_add_flag(face_dial_blackboard_22_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_22_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_23_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_23_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_23_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_23_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_23_88469, 117);
    lv_obj_set_y(face_dial_blackboard_23_88469, 5);
    lv_obj_add_flag(face_dial_blackboard_23_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_23_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_24_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_24_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_24_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_24_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_24_88469, 110);
    lv_obj_set_y(face_dial_blackboard_24_88469, 5);
    lv_obj_add_flag(face_dial_blackboard_24_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_24_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_25_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_25_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_25_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_25_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_25_88469, 214);
    lv_obj_set_y(face_dial_blackboard_25_88469, 113);
    lv_obj_add_flag(face_dial_blackboard_25_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_25_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_26_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_26_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_26_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_26_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_26_88469, 207);
    lv_obj_set_y(face_dial_blackboard_26_88469, 113);
    lv_obj_add_flag(face_dial_blackboard_26_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_26_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_27_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_27_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_27_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_27_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_27_88469, 200);
    lv_obj_set_y(face_dial_blackboard_27_88469, 113);
    lv_obj_add_flag(face_dial_blackboard_27_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_27_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_28_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_28_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_28_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_28_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_28_88469, 193);
    lv_obj_set_y(face_dial_blackboard_28_88469, 113);
    lv_obj_add_flag(face_dial_blackboard_28_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_28_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_29_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_29_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_29_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_29_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_29_88469, 84);
    lv_obj_set_y(face_dial_blackboard_29_88469, 40);
    lv_obj_add_flag(face_dial_blackboard_29_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_29_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_30_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_30_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_30_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_30_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_30_88469, 77);
    lv_obj_set_y(face_dial_blackboard_30_88469, 40);
    lv_obj_add_flag(face_dial_blackboard_30_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_30_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_31_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_31_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_31_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_31_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_31_88469, 70);
    lv_obj_set_y(face_dial_blackboard_31_88469, 40);
    lv_obj_add_flag(face_dial_blackboard_31_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_31_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_32_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_32_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_32_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_32_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_32_88469, 63);
    lv_obj_set_y(face_dial_blackboard_32_88469, 40);
    lv_obj_add_flag(face_dial_blackboard_32_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_32_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_33_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_33_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_33_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_33_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_33_88469, 56);
    lv_obj_set_y(face_dial_blackboard_33_88469, 40);
    lv_obj_add_flag(face_dial_blackboard_33_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_33_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_34_103067 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_34_103067, &face_dial_blackboard_dial_img_34_103067_0);
    lv_obj_set_width(face_dial_blackboard_34_103067, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_34_103067, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_34_103067, 66);
    lv_obj_set_y(face_dial_blackboard_34_103067, 115);
    lv_obj_add_flag(face_dial_blackboard_34_103067, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_34_103067, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_35_103067 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_35_103067, &face_dial_blackboard_dial_img_34_103067_0);
    lv_obj_set_width(face_dial_blackboard_35_103067, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_35_103067, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_35_103067, 46);
    lv_obj_set_y(face_dial_blackboard_35_103067, 115);
    lv_obj_add_flag(face_dial_blackboard_35_103067, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_35_103067, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_36_123509 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_36_123509, &face_dial_blackboard_dial_img_36_123509_0);
    lv_obj_set_width(face_dial_blackboard_36_123509, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_36_123509, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_36_123509, 112);
    lv_obj_set_y(face_dial_blackboard_36_123509, 116);
    lv_obj_add_flag(face_dial_blackboard_36_123509, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_36_123509, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_37_113241 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_37_113241, &face_dial_blackboard_dial_img_37_113241_0);
    lv_obj_set_width(face_dial_blackboard_37_113241, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_37_113241, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_37_113241, 92);
    lv_obj_set_y(face_dial_blackboard_37_113241, 116);
    lv_obj_add_flag(face_dial_blackboard_37_113241, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_37_113241, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_38_19117 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_38_19117, &face_dial_blackboard_dial_img_38_19117_0);
    lv_obj_set_width(face_dial_blackboard_38_19117, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_38_19117, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_38_19117, 184);
    lv_obj_set_y(face_dial_blackboard_38_19117, 14);
    lv_obj_add_flag(face_dial_blackboard_38_19117, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_38_19117, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_39_19117 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_39_19117, &face_dial_blackboard_dial_img_38_19117_0);
    lv_obj_set_width(face_dial_blackboard_39_19117, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_39_19117, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_39_19117, 177);
    lv_obj_set_y(face_dial_blackboard_39_19117, 14);
    lv_obj_add_flag(face_dial_blackboard_39_19117, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_39_19117, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_40_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_40_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_40_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_40_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_40_88469, 184);
    lv_obj_set_y(face_dial_blackboard_40_88469, 9);
    lv_obj_add_flag(face_dial_blackboard_40_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_40_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_41_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_41_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_41_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_41_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_41_88469, 177);
    lv_obj_set_y(face_dial_blackboard_41_88469, 9);
    lv_obj_add_flag(face_dial_blackboard_41_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_41_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_42_88469 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_42_88469, &face_dial_blackboard_dial_img_16_88469_0);
    lv_obj_set_width(face_dial_blackboard_42_88469, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_42_88469, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_42_88469, 170);
    lv_obj_set_y(face_dial_blackboard_42_88469, 9);
    lv_obj_add_flag(face_dial_blackboard_42_88469, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_42_88469, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_43_75746 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_43_75746, &face_dial_blackboard_dial_img_43_75746_0);
    lv_obj_set_width(face_dial_blackboard_43_75746, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_43_75746, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_43_75746, 191);
    lv_obj_set_y(face_dial_blackboard_43_75746, 8);
    lv_obj_add_flag(face_dial_blackboard_43_75746, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_43_75746, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_44_90517 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_44_90517, &face_dial_blackboard_dial_img_44_90517_0);
    lv_obj_set_width(face_dial_blackboard_44_90517, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_44_90517, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_44_90517, 191);
    lv_obj_set_y(face_dial_blackboard_44_90517, 8);
    lv_obj_add_flag(face_dial_blackboard_44_90517, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_44_90517, LV_OBJ_FLAG_SCROLLABLE );

    face_dial_blackboard_45_133743 = lv_img_create(face_dial_blackboard);
    lv_img_set_src(face_dial_blackboard_45_133743, &face_dial_blackboard_dial_img_45_133743_0);
    lv_obj_set_width(face_dial_blackboard_45_133743, LV_SIZE_CONTENT);
    lv_obj_set_height(face_dial_blackboard_45_133743, LV_SIZE_CONTENT);
    lv_obj_set_x(face_dial_blackboard_45_133743, 172);
    lv_obj_set_y(face_dial_blackboard_45_133743, 14);
    lv_obj_add_flag(face_dial_blackboard_45_133743, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_dial_blackboard_45_133743, LV_OBJ_FLAG_SCROLLABLE );


    callback("dial blackboard", &face_dial_blackboard_dial_img_preview_0, &face_dial_blackboard);

#endif
}

void update_time_dial_blackboard(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    if (!face_dial_blackboard)
    {
        return;
    }
	lv_img_set_src(face_dial_blackboard_12_90735, face_dial_blackboard_dial_img_12_90735_group[((month - 1) / 1) % 12]);
	lv_img_set_src(face_dial_blackboard_14_96385, face_dial_blackboard_dial_img_14_96385_group[((weekday + 6) / 1) % 7]);
	lv_img_set_src(face_dial_blackboard_20_89223, face_dial_blackboard_dial_img_20_89223_group[(day / 1) % 10]);
	lv_img_set_src(face_dial_blackboard_21_89223, face_dial_blackboard_dial_img_20_89223_group[(day / 10) % 10]);
	lv_img_set_src(face_dial_blackboard_34_103067, face_dial_blackboard_dial_img_34_103067_group[(hour / 1) % 10]);
	lv_img_set_src(face_dial_blackboard_35_103067, face_dial_blackboard_dial_img_34_103067_group[(hour / 10) % 10]);
	lv_img_set_src(face_dial_blackboard_36_123509, face_dial_blackboard_dial_img_36_123509_group[(minute / 1) % 10]);
	lv_img_set_src(face_dial_blackboard_37_113241, face_dial_blackboard_dial_img_37_113241_group[(minute / 10) % 10]);

#endif
}

void update_weather_dial_blackboard(int temp, int icon)
{
#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    if (!face_dial_blackboard)
    {
        return;
    }
	lv_img_set_src(face_dial_blackboard_2_88113, face_dial_blackboard_dial_img_weather[icon % 8]);

#endif
}

void update_status_dial_blackboard(int battery, bool connection){
#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    if (!face_dial_blackboard)
    {
        return;
    }
	lv_img_set_src(face_dial_blackboard_15_924, face_dial_blackboard_dial_img_15_924_group[(battery / (100 / 11)) % 11]);
	lv_img_set_src(face_dial_blackboard_16_88469, face_dial_blackboard_dial_img_16_88469_group[(battery / 10) % 10]);
	lv_img_set_src(face_dial_blackboard_17_88469, face_dial_blackboard_dial_img_16_88469_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_dial_blackboard_17_88469, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_dial_blackboard_17_88469, LV_OBJ_FLAG_HIDDEN);
	}
	lv_img_set_src(face_dial_blackboard_18_88469, face_dial_blackboard_dial_img_16_88469_group[(battery / 1000) % 10]);

#endif
}

void update_activity_dial_blackboard(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    if (!face_dial_blackboard)
    {
        return;
    }
	lv_img_set_src(face_dial_blackboard_25_88469, face_dial_blackboard_dial_img_16_88469_group[(kcal / 1) % 10]);
	lv_img_set_src(face_dial_blackboard_26_88469, face_dial_blackboard_dial_img_16_88469_group[(kcal / 10) % 10]);
	lv_img_set_src(face_dial_blackboard_27_88469, face_dial_blackboard_dial_img_16_88469_group[(kcal / 100) % 10]);
	lv_img_set_src(face_dial_blackboard_28_88469, face_dial_blackboard_dial_img_16_88469_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_dial_blackboard_29_88469, face_dial_blackboard_dial_img_16_88469_group[(steps / 1) % 10]);
	lv_img_set_src(face_dial_blackboard_30_88469, face_dial_blackboard_dial_img_16_88469_group[(steps / 10) % 10]);
	lv_img_set_src(face_dial_blackboard_31_88469, face_dial_blackboard_dial_img_16_88469_group[(steps / 100) % 10]);
	lv_img_set_src(face_dial_blackboard_32_88469, face_dial_blackboard_dial_img_16_88469_group[(steps / 1000) % 10]);
	lv_img_set_src(face_dial_blackboard_33_88469, face_dial_blackboard_dial_img_16_88469_group[(steps / 10000) % 10]);

#endif
}

void update_health_dial_blackboard(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    if (!face_dial_blackboard)
    {
        return;
    }
	lv_img_set_src(face_dial_blackboard_22_88469, face_dial_blackboard_dial_img_16_88469_group[(bpm / 1) % 10]);
	lv_img_set_src(face_dial_blackboard_23_88469, face_dial_blackboard_dial_img_16_88469_group[(bpm / 10) % 10]);
	lv_img_set_src(face_dial_blackboard_24_88469, face_dial_blackboard_dial_img_16_88469_group[(bpm / 100) % 10]);

#endif
}

void update_all_dial_blackboard(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    update_time_dial_blackboard(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_blackboard(temp, icon);
    update_status_dial_blackboard(battery, connection);
    update_activity_dial_blackboard(steps, distance, kcal);
    update_health_dial_blackboard(bpm, oxygen);
#endif
}

void update_check_dial_blackboard(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    if (root != face_dial_blackboard)
    {
        return;
    }
    update_time_dial_blackboard(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_dial_blackboard(temp, icon);
    update_status_dial_blackboard(battery, connection);
    update_activity_dial_blackboard(steps, distance, kcal);
    update_health_dial_blackboard(bpm, oxygen);
#endif
}


