
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: DIAL_BLACKBOARD

#ifndef _FACE_DIAL_BLACKBOARD_H
#define _FACE_DIAL_BLACKBOARD_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#define ENABLE_FACE_DIAL_BLACKBOARD // (dial blackboard) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_DIAL_BLACKBOARD
    extern lv_obj_t *face_dial_blackboard;
	extern lv_obj_t *face_dial_blackboard_0_4206;
	extern lv_obj_t *face_dial_blackboard_2_88113;
	extern lv_obj_t *face_dial_blackboard_12_90735;
	extern lv_obj_t *face_dial_blackboard_14_96385;
	extern lv_obj_t *face_dial_blackboard_15_924;
	extern lv_obj_t *face_dial_blackboard_16_88469;
	extern lv_obj_t *face_dial_blackboard_17_88469;
	extern lv_obj_t *face_dial_blackboard_18_88469;
	extern lv_obj_t *face_dial_blackboard_19_4100;
	extern lv_obj_t *face_dial_blackboard_20_89223;
	extern lv_obj_t *face_dial_blackboard_21_89223;
	extern lv_obj_t *face_dial_blackboard_22_88469;
	extern lv_obj_t *face_dial_blackboard_23_88469;
	extern lv_obj_t *face_dial_blackboard_24_88469;
	extern lv_obj_t *face_dial_blackboard_25_88469;
	extern lv_obj_t *face_dial_blackboard_26_88469;
	extern lv_obj_t *face_dial_blackboard_27_88469;
	extern lv_obj_t *face_dial_blackboard_28_88469;
	extern lv_obj_t *face_dial_blackboard_29_88469;
	extern lv_obj_t *face_dial_blackboard_30_88469;
	extern lv_obj_t *face_dial_blackboard_31_88469;
	extern lv_obj_t *face_dial_blackboard_32_88469;
	extern lv_obj_t *face_dial_blackboard_33_88469;
	extern lv_obj_t *face_dial_blackboard_34_103067;
	extern lv_obj_t *face_dial_blackboard_35_103067;
	extern lv_obj_t *face_dial_blackboard_36_123509;
	extern lv_obj_t *face_dial_blackboard_37_113241;
	extern lv_obj_t *face_dial_blackboard_38_19117;
	extern lv_obj_t *face_dial_blackboard_39_19117;
	extern lv_obj_t *face_dial_blackboard_40_88469;
	extern lv_obj_t *face_dial_blackboard_41_88469;
	extern lv_obj_t *face_dial_blackboard_42_88469;
	extern lv_obj_t *face_dial_blackboard_43_75746;
	extern lv_obj_t *face_dial_blackboard_44_90517;
	extern lv_obj_t *face_dial_blackboard_45_133743;


	LV_IMG_DECLARE(face_dial_blackboard_dial_img_0_4206_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_2_88113_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_3_102727_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_4_102391_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_5_101837_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_6_101545_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_7_102169_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_8_133748_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_9_101001_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_10_101255_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_7);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_8);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_9);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_10);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_11_75988_11);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_7);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_8);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_9);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_10);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_12_90735_11);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_13_83402_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_13_83402_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_13_83402_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_13_83402_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_13_83402_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_13_83402_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_13_83402_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_14_96385_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_14_96385_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_14_96385_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_14_96385_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_14_96385_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_14_96385_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_14_96385_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_7);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_8);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_9);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_15_924_10);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_7);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_8);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_16_88469_9);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_19_4100_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_7);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_8);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_20_89223_9);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_7);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_8);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_34_103067_9);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_7);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_8);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_36_123509_9);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_1);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_2);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_3);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_4);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_5);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_6);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_7);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_8);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_37_113241_9);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_38_19117_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_43_75746_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_44_90517_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_45_133743_0);
	LV_IMG_DECLARE(face_dial_blackboard_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_dial_blackboard(void (*callback)(const char *name, const lv_img_dsc_t *preview, lv_obj_t **watchface, int anim_img_num, lv_obj_t *anim_img, const lv_img_dsc_t **anim_img_group));
    void update_time_dial_blackboard(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_dial_blackboard(int temp, int icon);
    void update_status_dial_blackboard(int battery, bool connection);
    void update_activity_dial_blackboard(int steps, int distance, int kcal);
    void update_health_dial_blackboard(int bpm, int oxygen);
    void update_all_dial_blackboard(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_dial_blackboard(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
